package net.tfminecraft.rpcharacters;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.nio.file.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.mockbukkit.mockbukkit.*;

class RPCharactersLifecycleTest {
    ServerMock server;RuntimeTestState state;TestPlugin plugin;
    public static class TestPlugin extends RPCharacters {
        @Override public void onEnable() {}
        @Override public void onDisable() {}
    }
    @BeforeEach void setup(){server=MockBukkit.mock();state=new RuntimeTestState(RPCharacters.class,net.tfminecraft.rpcharacters.managers.PlayerManager.class);RPCharacters.plugin=mock(RPCharacters.class);when(RPCharacters.plugin.namespace()).thenReturn("rpcharacters");plugin=spy(MockBukkit.loadSimple(TestPlugin.class));RPCharacters.plugin=plugin;}
    @AfterEach void cleanup(){state.close();MockBukkit.unmock();}
    @Test void initialConfigurationCreatesAllBundledFilesAndPreservesUserChanges()throws Exception{plugin.createFolders();plugin.createConfigs();var root=plugin.getDataFolder().toPath();for(String dir:new String[]{"traits","data/playerdata","data/characterdata","professions","assets","graves"})assertTrue(Files.isDirectory(root.resolve(dir)));for(String file:new String[]{"chat.yml","stages.yml","kits.yml","traits/injury-traits.yml","assets/masked.png"})assertTrue(Files.size(root.resolve(file))>0);Files.writeString(root.resolve("config.yml"),"custom: true\n");plugin.createFolders();plugin.createConfigs();assertEquals("custom: true\n",Files.readString(root.resolve("config.yml")));assertSame(plugin.getPlaceClueManager(),RPCharacters.getPlaceClueManager());assertNotNull(RPCharacters.getPlayerManager());assertSame(RPCharacters.getSpawnedClueManager(),RPCharacters.getSpawnedClueManager());}
    @Test void legacyChatMigrationAddsRoocAndPreservesExistingChannels()throws Exception{plugin.createFolders();plugin.createConfigs();var file=plugin.getDataFolder().toPath().resolve("chat.yml");Files.writeString(file,"channels:\n  custom:\n    range: 12\n");plugin.createConfigs();var cfg=YamlConfiguration.loadConfiguration(file.toFile());assertEquals(12,cfg.getInt("channels.custom.range"));assertTrue(cfg.isConfigurationSection("channels.rooc"));}
    @Test void absentBundledMigrationDefaultsAndUnreadableResourcesLeaveChatUntouched()throws Exception{plugin.createFolders();plugin.createConfigs();var file=plugin.getDataFolder().toPath().resolve("chat.yml");String previous="channels: {custom: {range: 7}}\n";Files.writeString(file,previous);doAnswer(c->new ByteArrayInputStream("channels: {}\n".getBytes(StandardCharsets.UTF_8))).when(plugin).getResource("chat.yml");plugin.createConfigs();assertEquals(previous,Files.readString(file));doReturn(null).when(plugin).getResource("chat.yml");assertDoesNotThrow(plugin::createConfigs);assertEquals(previous,Files.readString(file));}
    @Test void publicAccountAndCharacterQueriesHandleMissingAndActiveData(){var player=server.addPlayer();var data=new net.tfminecraft.rpcharacters.objects.PlayerData(player);var cfg=new YamlConfiguration();cfg.set("name","Human");var character=new net.tfminecraft.rpcharacters.objects.RPCharacter(player,java.util.UUID.randomUUID().toString(),"Scout",true,net.tfminecraft.rpcharacters.enums.Status.ALIVE,new net.tfminecraft.rpcharacters.objects.races.Race("human",cfg),new java.util.ArrayList<>(),null);
        try(var players=mockStatic(net.tfminecraft.rpcharacters.managers.PlayerManager.class)){
            assertEquals(0,RPCharacters.getAccountAgeSeconds(null));assertEquals(0,RPCharacters.getAccountAgeSeconds(player));assertNull(RPCharacters.getActiveCharacter(null));assertNull(RPCharacters.getActiveCharacter(player));assertEquals(0,RPCharacters.getAccountAttributePointsTotal(null));assertEquals(0,RPCharacters.getAccountAttributePointsTotal(player));assertEquals(0,RPCharacters.getFreeAttributePoints(null));assertEquals(0,RPCharacters.getFreeAttributePoints(player));assertEquals(0,RPCharacters.getCharacterAgeSeconds(null));assertEquals(0,RPCharacters.getConversationCount(null,"other"));
            players.when(()->net.tfminecraft.rpcharacters.managers.PlayerManager.get(player)).thenReturn(data);data.setCreatedAtEpochSeconds(1);data.setAccountAttributePointsTotal(7);assertTrue(RPCharacters.getAccountAgeSeconds(player)>100);assertEquals(7,RPCharacters.getAccountAttributePointsTotal(player));assertEquals(7,RPCharacters.getFreeAttributePoints(player));data.getCharacters().add(character);assertSame(character,RPCharacters.getActiveCharacter(player));character.setCreatedAtEpochSeconds(1);assertTrue(RPCharacters.getCharacterAgeSeconds(character)>100);character.setExtraAttributeAllocation(java.util.Map.of("strength",3));assertEquals(4,RPCharacters.getFreeAttributePoints(player));character.setConversationCounts(java.util.Map.of("other",4));assertEquals(4,RPCharacters.getConversationCount(character,"other"));assertEquals(java.util.List.of(java.util.Map.entry("other",4)),RPCharacters.getTopConversationPartners(character,1));
        }
    }
    @Test void publicIntegrationFacadesPreserveArgumentsAndResults(){var player=server.addPlayer();var head=new org.bukkit.inventory.ItemStack(org.bukkit.Material.PLAYER_HEAD);var id=player.getUniqueId();var location=player.getLocation();Runnable callback=()->{};
        try(var skull=mockStatic(net.tfminecraft.rpcharacters.api.CharacterSkull.class);var mail=mockStatic(net.tfminecraft.rpcharacters.mail.MailRecipientDirectory.class);var identity=mockStatic(net.tfminecraft.rpcharacters.identity.DisplayIdentityService.class);var attributes=mockStatic(net.tfminecraft.rpcharacters.mmocore.AttributePointService.class)){
            skull.when(()->net.tfminecraft.rpcharacters.api.CharacterSkull.ofActive(player)).thenReturn(head);assertSame(head,RPCharacters.getSkull(player));mail.when(net.tfminecraft.rpcharacters.mail.MailRecipientDirectory::listMailTargets).thenReturn(java.util.List.of());assertTrue(RPCharacters.listMailTargets().isEmpty());mail.when(()->net.tfminecraft.rpcharacters.mail.MailRecipientDirectory.getMailTargetLocation(id,"char")).thenReturn(location);assertSame(location,RPCharacters.getMailTargetLocation(id,"char"));RPCharacters.refreshMailTargetTexturesAsync(callback);mail.verify(()->net.tfminecraft.rpcharacters.mail.MailRecipientDirectory.refreshMissingTexturesAsync(callback));
            identity.when(()->net.tfminecraft.rpcharacters.identity.DisplayIdentityService.resolveCharacterName(player)).thenReturn("name");identity.when(()->net.tfminecraft.rpcharacters.identity.DisplayIdentityService.resolveDisplay(player)).thenReturn("display");identity.when(()->net.tfminecraft.rpcharacters.identity.DisplayIdentityService.resolveDisplayTab(player)).thenReturn("tab");identity.when(()->net.tfminecraft.rpcharacters.identity.DisplayIdentityService.resolveDisplaySafe(player)).thenReturn("safe");assertEquals("name",RPCharacters.getCharacterName(player));assertEquals("display",RPCharacters.getDisplay(player));assertEquals("tab",RPCharacters.getDisplayTab(player));assertEquals("safe",RPCharacters.getDisplaySafe(player));RPCharacters.grantAttributePoints(player,4);attributes.verify(()->net.tfminecraft.rpcharacters.mmocore.AttributePointService.grantAttributePoints(player,4));
        }
        player.setGameMode(org.bukkit.GameMode.CREATIVE);RPCharacters.setDiscordGate(player,true);assertTrue(RPCharacters.isDiscordGate(id));RPCharacters.setDiscordGate(id,false);assertFalse(RPCharacters.isDiscordGate(id));RPCharacters.setDiscordGate((org.bukkit.entity.Player)null,true);RPCharacters.setDiscordGate((java.util.UUID)null,true);assertNull(RPCharacters.getFocusService());assertFalse(plugin.reloadFocusConfig());RPCharacters.plugin=null;assertNull(RPCharacters.getFocusService());
    }

}
