package net.tfminecraft.rpcharacters.prosthetics;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.nio.file.*;
import java.util.*;
import org.bukkit.*;
import org.bukkit.entity.*;
import org.bukkit.event.block.Action;
import org.bukkit.event.inventory.*;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.mockbukkit.mockbukkit.MockBukkit;
import net.tfminecraft.rpcharacters.injuries.RpInjureServiceTest.Fixture;
import net.tfminecraft.rpcharacters.enums.Status;
import net.tfminecraft.rpcharacters.loaders.*;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.objects.trait.Trait;
import net.tfminecraft.rpcharacters.permadeath.PermadeathService;

class ProstheticInstallListenerTest {
    @TempDir Path folder;Fixture f;ProstheticInstallListener listener;ProstheticRefuelListener refuel;Trait oldArm,newArm;
    @BeforeEach void setup() throws Exception {f=new Fixture(folder);listener=new ProstheticInstallListener();refuel=new ProstheticRefuelListener();oldArm=f.trait("wood_arm","prosthetic",false,null);newArm=f.trait("iron_arm","prosthetic",false,null);replacements("IRON_INGOT");}
    @AfterEach void cleanup() throws Exception {if(f!=null)f.close();else MockBukkit.unmock();}
    void replacements(String item) throws Exception {var path=folder.resolve("prosthetics.yml");Files.writeString(path,"replacements:\n  maimed:\n    wood_arm: OAK_PLANKS\n    iron_arm: "+item+"\n");new ProstheticLoader().load(path.toFile());}
    ItemStack hold(Material material,int amount){var item=new ItemStack(material,amount);f.target.getInventory().setItemInMainHand(item);return f.target.getInventory().getItemInMainHand();}
    PlayerInteractEvent interact(ItemStack item){var event=new PlayerInteractEvent(f.target,Action.RIGHT_CLICK_AIR,item,null,org.bukkit.block.BlockFace.SELF,EquipmentSlot.HAND);event.setCancelled(false);return event;}
    void install(ItemStack item){listener.onPlayerInteract(interact(item));}
    void swap(){f.targetCharacter.addTrait(oldArm);install(hold(Material.IRON_INGOT,2));assertInstanceOf(ProstheticConfirmHolder.class,f.target.getOpenInventory().getTopInventory().getHolder());}
    void confirm(){listener.onInventoryClick(f.click(f.target,11));}
    void assertHeld(Material material,int amount){assertEquals(material,f.target.getInventory().getItemInMainHand().getType());assertEquals(amount,f.target.getInventory().getItemInMainHand().getAmount());}
    Trait fueled(String id,String template,double capacity){var yaml=new YamlConfiguration();yaml.set("name",id);yaml.set("key","prosthetic");yaml.set("fuel-template",template);yaml.set("fuel-capacity",capacity);yaml.createSection("powered").set("name","Powered");yaml.createSection("depowered").set("name","Empty");return f.trait(id,yaml);}
    void fuelConfig(double amount,double rate,String interval) throws Exception {var yaml=new YamlConfiguration();yaml.set("oil.item","COAL");yaml.set("oil.amount-per-item",amount);yaml.set("oil.burn-rate",rate);yaml.set("oil.burn-interval",interval);var path=folder.resolve("fuel.yml");yaml.save(path.toFile());new FuelTemplateLoader().load(path.toFile());}
    void refuel(ItemStack item){refuel.onPlayerInteract(interact(item));}

    @Test void irrelevantActionsOffhandsAndUnmatchedItemsAreIgnored(){var held=hold(Material.DIAMOND,2);var left=new PlayerInteractEvent(f.target,Action.LEFT_CLICK_AIR,held,null,org.bukkit.block.BlockFace.SELF,EquipmentSlot.HAND);left.setCancelled(false);listener.onPlayerInteract(left);assertFalse(left.isCancelled());var off=new PlayerInteractEvent(f.target,Action.RIGHT_CLICK_AIR,held,null,org.bukkit.block.BlockFace.SELF,EquipmentSlot.OFF_HAND);off.setCancelled(false);listener.onPlayerInteract(off);assertFalse(off.isCancelled());var unmatched=interact(held);listener.onPlayerInteract(unmatched);assertFalse(unmatched.isCancelled());install(null);assertHeld(Material.DIAMOND,2);}
    @Test void installationRequiresLoadedActiveCharacterData(){var event=interact(hold(Material.IRON_INGOT,2));f.loaded.remove(f.target);listener.onPlayerInteract(event);assertTrue(event.isCancelled());assertTrue(f.text(f.target).contains("active character"));f.loaded.put(f.target,new PlayerData(f.target));install(f.target.getInventory().getItemInMainHand());assertTrue(f.text(f.target).contains("active character"));assertHeld(Material.IRON_INGOT,2);}
    @Test void installationReplacesInjuryConsumesOneItemAndRetainsOtherTraits(){f.targetCharacter.addTrait(f.permanent);f.targetCharacter.addTrait(f.healing);var event=interact(hold(Material.IRON_INGOT,2));listener.onPlayerInteract(event);assertTrue(event.isCancelled());assertEquals(List.of(f.healing,newArm),f.targetCharacter.getTraits());assertHeld(Material.IRON_INGOT,1);assertTrue(f.text(f.target).contains("gained the trait iron_arm"));verify(f.manager,atLeastOnce()).savePlayer(f.target);}
    @Test void consumingTheLastItemClearsTheHand(){f.targetCharacter.addTrait(f.permanent);install(hold(Material.IRON_INGOT,1));assertTrue(f.target.getInventory().getItemInMainHand().getType().isAir());assertEquals(List.of(newArm),f.targetCharacter.getTraits());}
    @Test void noInjuryAndAlreadyOwnedProstheticsNeverConsumeAnItem(){install(hold(Material.IRON_INGOT,2));assertTrue(f.text(f.target).contains("no injury"));assertHeld(Material.IRON_INGOT,2);f.targetCharacter.addTrait(newArm);install(f.target.getInventory().getItemInMainHand());assertTrue(f.text(f.target).contains("already have"));assertHeld(Material.IRON_INGOT,2);}
    @Test void missingReloadedInstallTraitsPreserveTheExistingInjury(){f.targetCharacter.addTrait(f.permanent);TraitLoader.oList.remove(newArm);install(hold(Material.IRON_INGOT,2));assertEquals(List.of(f.permanent),f.targetCharacter.getTraits());assertHeld(Material.IRON_INGOT,2);}
    @Test void deadCharactersCannotInstallAProsthetic(){f.targetCharacter.addTrait(f.permanent);f.targetCharacter.setStatus(Status.DEAD);install(hold(Material.IRON_INGOT,2));assertEquals(List.of(f.permanent),f.targetCharacter.getTraits(),"Permanent death must not allow character modification");assertHeld(Material.IRON_INGOT,2);}
    @Test void staleInteractionItemCannotConsumeAnUnrelatedCurrentHeldItem(){f.targetCharacter.addTrait(f.permanent);ItemStack clicked=hold(Material.IRON_INGOT,2).clone();hold(Material.DIAMOND,3);install(clicked);assertEquals(List.of(f.permanent),f.targetCharacter.getTraits());assertHeld(Material.DIAMOND,3);}
    @Test void confirmationShowsTheDestructiveSwapAndConsumesOnlyOnConfirm(){swap();var inv=f.target.getOpenInventory().getTopInventory();var holder=(ProstheticConfirmHolder)inv.getHolder();assertSame(f.target,holder.getOwner());assertNull(holder.getInventory());assertEquals(27,inv.getSize());assertEquals(Material.GREEN_CONCRETE,inv.getItem(11).getType());assertEquals(Material.RED_CONCRETE,inv.getItem(15).getType());assertTrue(inv.getItem(11).getItemMeta().getLore().stream().anyMatch(s->s.contains("wood_arm")));assertTrue(inv.getItem(11).getItemMeta().getLore().stream().anyMatch(s->s.contains("destroyed")));assertEquals(Material.GRAY_STAINED_GLASS_PANE,inv.getItem(0).getType());assertEquals(List.of(oldArm),f.targetCharacter.getTraits());confirm();assertEquals(List.of(newArm),f.targetCharacter.getTraits());assertHeld(Material.IRON_INGOT,1);}
    @Test void cancelAndCloseRemovePendingSwapsWithoutConsumingItems(){swap();var view=f.target.getOpenInventory();listener.onInventoryClick(f.click(f.target,15));assertEquals(List.of(oldArm),f.targetCharacter.getTraits());f.target.openInventory(view.getTopInventory());confirm();assertEquals(List.of(oldArm),f.targetCharacter.getTraits());assertHeld(Material.IRON_INGOT,2);install(f.target.getInventory().getItemInMainHand());listener.onInventoryClose(new InventoryCloseEvent(f.target.getOpenInventory()));confirm();assertEquals(List.of(oldArm),f.targetCharacter.getTraits());}
    @Test void quitAndUnrelatedInventoryEventsDoNotApplySwaps(){swap();listener.onQuit(new PlayerQuitEvent(f.target,"quit"));confirm();assertEquals(List.of(oldArm),f.targetCharacter.getTraits());var click=f.click(f.target,0);listener.onInventoryClick(click);assertFalse(click.isCancelled());listener.onInventoryClose(new InventoryCloseEvent(f.target.getOpenInventory()));}
    @Test void pendingSwapRejectsMissingDataAndChangedCharacters(){swap();f.loaded.remove(f.target);confirm();assertTrue(f.text(f.target).contains("active character"));assertHeld(Material.IRON_INGOT,2);f.loaded.put(f.target,f.targetData);install(f.target.getInventory().getItemInMainHand());var another=f.character(f.target,"Other",false);f.targetData.addCharacter(another);f.targetData.setActiveCharacter(another);confirm();assertTrue(f.text(f.target).contains("no longer valid"));assertEquals(List.of(oldArm),f.targetCharacter.getTraits());assertTrue(another.getTraits().isEmpty());}
    @Test void aDeadCharacterCannotConfirmAnEarlierProstheticSwap(){swap();f.targetCharacter.setStatus(Status.DEAD);confirm();assertEquals(List.of(oldArm),f.targetCharacter.getTraits());assertHeld(Material.IRON_INGOT,2);}
    @Test void movedHeldItemOrDifferentProstheticRejectsConfirmation(){swap();hold(Material.DIAMOND,2);confirm();assertTrue(f.text(f.target).contains("keep holding"));assertEquals(List.of(oldArm),f.targetCharacter.getTraits());assertHeld(Material.DIAMOND,2);install(hold(Material.IRON_INGOT,2));hold(Material.OAK_PLANKS,2);confirm();assertTrue(f.text(f.target).contains("keep holding"));assertHeld(Material.OAK_PLANKS,2);}
    @Test void changedConfiguredItemPathInvalidatesPendingConfirmation() throws Exception {swap();replacements("IRON_BLOCK");hold(Material.IRON_BLOCK,2);confirm();assertTrue(f.text(f.target).contains("keep holding"));assertEquals(List.of(oldArm),f.targetCharacter.getTraits());assertHeld(Material.IRON_BLOCK,2);}
    @Test void removedOwnedOrConfiguredTraitDoesNotConsumeTheItem(){swap();f.targetCharacter.removeTrait(oldArm);confirm();assertTrue(f.text(f.target).contains("no longer valid"));assertHeld(Material.IRON_INGOT,2);f.targetCharacter.addTrait(oldArm);install(f.target.getInventory().getItemInMainHand());TraitLoader.oList.remove(newArm);confirm();assertEquals(List.of(oldArm),f.targetCharacter.getTraits());assertHeld(Material.IRON_INGOT,2);}
    @Test void missingSourceOrDestinationDefinitionsDoNotOpenAConfirmation(){f.targetCharacter.addTrait(oldArm);TraitLoader.oList.remove(oldArm);install(hold(Material.IRON_INGOT,2));assertFalse(f.target.getOpenInventory().getTopInventory().getHolder() instanceof ProstheticConfirmHolder);TraitLoader.oList.add(oldArm);TraitLoader.oList.remove(newArm);install(f.target.getInventory().getItemInMainHand());assertFalse(f.target.getOpenInventory().getTopInventory().getHolder() instanceof ProstheticConfirmHolder);}
    @Test void confirmationBlocksBottomOutsideFillerAndDragActions(){swap();for(int slot:new int[]{30,-999,0}){var event=f.click(f.target,slot);listener.onInventoryClick(event);assertTrue(event.isCancelled());}var drag=new InventoryDragEvent(f.target.getOpenInventory(),new ItemStack(Material.DIAMOND),new ItemStack(Material.DIAMOND,2),false,Map.of(0,new ItemStack(Material.DIAMOND)));listener.onInventoryDrag(drag);assertTrue(drag.isCancelled());assertEquals(List.of(oldArm),f.targetCharacter.getTraits());f.target.closeInventory();var ordinary=new InventoryDragEvent(f.target.getOpenInventory(),new ItemStack(Material.DIAMOND),new ItemStack(Material.DIAMOND,2),false,Map.of(0,new ItemStack(Material.DIAMOND)));listener.onInventoryDrag(ordinary);assertFalse(ordinary.isCancelled());}
    @Test void nonPlayerInventoryViewIsIgnored(){var holder=new ProstheticConfirmHolder(f.target);var inventory=Bukkit.createInventory(holder,27);var view=mock(InventoryView.class);when(view.getTopInventory()).thenReturn(inventory);when(view.getPlayer()).thenReturn(mock(HumanEntity.class));var click=new InventoryClickEvent(view,InventoryType.SlotType.CONTAINER,11,ClickType.LEFT,InventoryAction.PICKUP_ALL);listener.onInventoryClick(click);assertFalse(click.isCancelled());listener.onInventoryClose(new InventoryCloseEvent(view));}

    @Test void refuelingIgnoresUnmatchedOffhandAndOtherActions() throws Exception {fuelConfig(25,10,"1m");var held=hold(Material.COAL,2);var left=new PlayerInteractEvent(f.target,Action.LEFT_CLICK_AIR,held,null,org.bukkit.block.BlockFace.SELF,EquipmentSlot.HAND);left.setCancelled(false);refuel.onPlayerInteract(left);assertFalse(left.isCancelled());var off=new PlayerInteractEvent(f.target,Action.RIGHT_CLICK_AIR,held,null,org.bukkit.block.BlockFace.SELF,EquipmentSlot.OFF_HAND);off.setCancelled(false);refuel.onPlayerInteract(off);assertFalse(off.isCancelled());var unknown=interact(new ItemStack(Material.DIAMOND));refuel.onPlayerInteract(unknown);assertFalse(unknown.isCancelled());assertHeld(Material.COAL,2);}
    @Test void refuelingRequiresLoadedCharacterAndMatchingFuelTraits() throws Exception {fuelConfig(25,10,"1m");var item=hold(Material.COAL,2);f.loaded.remove(f.target);refuel(item);assertTrue(f.text(f.target).contains("active character"));f.loaded.put(f.target,new PlayerData(f.target));refuel(item);assertTrue(f.text(f.target).contains("active character"));f.loaded.put(f.target,f.targetData);f.targetCharacter.addTrait(f.healing);f.targetCharacter.addTrait(fueled("other","other",100));refuel(item);assertTrue(f.text(f.target).contains("uses that fuel"));assertHeld(Material.COAL,2);}
    @Test void refuelingUpdatesEveryMatchingProstheticAndConsumesOneItem() throws Exception {fuelConfig(25,10,"1m");Trait one=fueled("engine","OIL",100),two=fueled("other_engine","oil",50);f.targetCharacter.addTrait(one);f.targetCharacter.addTrait(two);f.targetCharacter.setFuel(one.getId(),0);f.targetCharacter.setFuel(two.getId(),40);var event=interact(hold(Material.COAL,2));refuel.onPlayerInteract(event);assertTrue(event.isCancelled());assertEquals(25,f.targetCharacter.getFuel(one.getId()));assertEquals(50,f.targetCharacter.getFuel(two.getId()));assertHeld(Material.COAL,1);assertTrue(f.text(f.target).contains("Fuel:"));verify(f.manager).savePlayer(f.target);assertFalse(f.integrations.constructed().isEmpty());}
    @Test void fullFuelDoesNotConsumeItemsAndOneItemClearsTheHand() throws Exception {fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100);f.targetCharacter.addTrait(engine);refuel(hold(Material.COAL,1));assertTrue(f.text(f.target).contains("already full"));assertHeld(Material.COAL,1);f.targetCharacter.setFuel(engine.getId(),50);refuel(f.target.getInventory().getItemInMainHand());assertEquals(75,f.targetCharacter.getFuel(engine.getId()));assertTrue(f.target.getInventory().getItemInMainHand().getType().isAir());}
    @Test void legacyMissingFuelStateStartsAtZeroWhenRefueled() throws Exception {fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100);f.targetCharacter.setTraits(new ArrayList<>(List.of(engine)));assertEquals(-1,f.targetCharacter.getFuel(engine.getId()));refuel(hold(Material.COAL,2));assertEquals(25,f.targetCharacter.getFuel(engine.getId()));assertHeld(Material.COAL,1);}
    @Test void deadCharactersCannotConsumeFuel() throws Exception {fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100);f.targetCharacter.addTrait(engine);f.targetCharacter.setFuel(engine.getId(),0);f.targetCharacter.setStatus(Status.DEAD);refuel(hold(Material.COAL,2));assertEquals(0,f.targetCharacter.getFuel(engine.getId()));assertHeld(Material.COAL,2);}
    @Test void staleRefuelEventMustNotRefuelWithoutConsumingTheActualFuel() throws Exception {fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100);f.targetCharacter.addTrait(engine);f.targetCharacter.setFuel(engine.getId(),0);var eventItem=hold(Material.COAL,1).clone();hold(Material.DIAMOND,3);refuel(eventItem);assertEquals(0,f.targetCharacter.getFuel(engine.getId()));assertHeld(Material.DIAMOND,3);}
    @Test void fuelTimerBurnsProportionallyAndRefreshesOnlyOnPowerLoss() throws Exception {fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100);f.targetCharacter.addTrait(engine);f.targetCharacter.setFuel(engine.getId(),15);ProstheticFuelService.start();assertEquals(1,f.timers.size());assertEquals(InjuryPoolLoader.getHealingTickIntervalTicks(),f.timers.getFirst().delay());f.timers.getFirst().run().run();assertEquals(5,f.targetCharacter.getFuel(engine.getId()));assertTrue(f.integrations.constructed().isEmpty());f.timers.getFirst().run().run();assertEquals(0,f.targetCharacter.getFuel(engine.getId()));assertEquals(1,f.integrations.constructed().size());verify(f.manager,times(2)).savePlayer(f.target);f.timers.getFirst().run().run();verify(f.manager,times(2)).savePlayer(f.target);}
    @Test void fuelTickSkipsDeadAwaitingUnloadedAndInactivePlayers() throws Exception {fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100);f.targetCharacter.addTrait(engine);PermadeathService.markPendingPermadeathRespawn(f.target);ProstheticFuelService.tick();assertEquals(100,f.targetCharacter.getFuel(engine.getId()));PermadeathService.clearPendingPermadeathRespawn(f.target);f.loaded.remove(f.target);ProstheticFuelService.tick();f.loaded.put(f.target,new PlayerData(f.target));ProstheticFuelService.tick();f.loaded.put(f.target,f.targetData);f.target.setHealth(0);ProstheticFuelService.tick();assertEquals(100,f.targetCharacter.getFuel(engine.getId()));verify(f.manager,never()).savePlayer(f.target);}
    @Test void fuelTickInitializesLegacyFuelAndSkipsUnconfiguredTemplates() throws Exception {fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100),missing=fueled("missing","unknown",100);f.targetCharacter.setTraits(new ArrayList<>(List.of(f.healing,engine,missing)));ProstheticFuelService.tick();assertEquals(90,f.targetCharacter.getFuel(engine.getId()));assertEquals(-1,f.targetCharacter.getFuel(missing.getId()));verify(f.manager).savePlayer(f.target);}
    @Test void underflowingButPositiveConfiguredBurnRateDoesNotChangeFuel() throws Exception {fuelConfig(25,Double.MIN_VALUE,"1h");assertNotNull(FuelTemplateLoader.getByString("oil"));Trait engine=fueled("engine","oil",100);f.targetCharacter.addTrait(engine);ProstheticFuelService.tick();assertEquals(100,f.targetCharacter.getFuel(engine.getId()));verify(f.manager,never()).savePlayer(f.target);}
    @Test void aStatUpdateHookThatConsumesTheItemDoesNotConsumeAnotherStack(){
        f.targetCharacter.addTrait(f.permanent);f.target.getInventory().setItem(1,new ItemStack(Material.DIAMOND,3));
        // MMOCore AttributeInstance.setBase -> MythicLib StatHandler.runUpdates invokes registered plugin listeners.
        f.integrationCallback=player->{if(f.targetCharacter.getTraits().contains(newArm))player.getInventory().setItemInMainHand(null);};
        install(hold(Material.IRON_INGOT,1));assertEquals(List.of(newArm),f.targetCharacter.getTraits());assertTrue(f.target.getInventory().getItemInMainHand().getType().isAir());assertEquals(3,f.target.getInventory().getItem(1).getAmount());
    }
    @Test void aStatUpdateHookThatChangesHeldItemsCannotMakeInstallationConsumeAnUnrelatedItem(){
        f.targetCharacter.addTrait(f.permanent);f.integrationCallback=player->{if(f.targetCharacter.getTraits().contains(newArm))player.getInventory().setItemInMainHand(new ItemStack(Material.DIAMOND,3));};
        install(hold(Material.IRON_INGOT,1));assertEquals(List.of(newArm),f.targetCharacter.getTraits());assertHeld(Material.DIAMOND,3);
    }
    @Test void refuelingConsumesFuelBeforeStatHooksCanReplaceTheHeldItem() throws Exception {
        fuelConfig(25,10,"1m");Trait engine=fueled("engine","oil",100);f.targetCharacter.addTrait(engine);f.targetCharacter.setFuel(engine.getId(),0);
        f.integrationCallback=player->player.getInventory().setItemInMainHand(new ItemStack(Material.DIAMOND,3));
        refuel(hold(Material.COAL,1));assertEquals(25,f.targetCharacter.getFuel(engine.getId()));assertHeld(Material.DIAMOND,3);
    }

}
