package net.tfminecraft.rpcharacters.lifecycle;

import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.event.*;
import org.bukkit.plugin.Plugin;
import org.junit.jupiter.api.*;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.enums.Status;
import net.tfminecraft.rpcharacters.objects.RPCharacter;
import net.tfminecraft.rpcharacters.objects.races.Race;

class CharacterLifecycleRuntimeTest {
    ServerMock server;PlayerMock owner;Plugin plugin;RuntimeTestState state;RPCharacter character,previous;Race race;final List<Event> events=new ArrayList<>();
    @BeforeEach void setup(){server=MockBukkit.mock();state=new RuntimeTestState();Cache.attributes=new ArrayList<>();Cache.professions=new ArrayList<>();Cache.backgroundTraitTypes=new ArrayList<>();owner=server.addPlayer("Owner");plugin=MockBukkit.createMockPlugin("LifecycleTest");var yaml=new YamlConfiguration();yaml.set("name","Human");race=new Race("human",yaml);character=new RPCharacter(owner,UUID.randomUUID().toString(),"Aria",true,Status.ALIVE,race,new ArrayList<>(),"HUMAN");previous=new RPCharacter(owner,UUID.randomUUID().toString(),"Elder",false,Status.ALIVE,race,new ArrayList<>(),"HUMAN");for(var type:List.of(CharacterCreatedEvent.class,CharacterActivatedEvent.class,CharacterClassChangeEvent.class,CharacterRaceChangeEvent.class)){server.getPluginManager().registerEvent(type,new Listener(){},EventPriority.NORMAL,(listener,event)->events.add(event),plugin);}}
    @AfterEach void cleanup(){try{HandlerList.unregisterAll(plugin);if(state!=null)state.close();}finally{MockBukkit.unmock();}}
    @Test void creationEventPublishesTheExactOwnerAndPersistedCharacter(){CharacterLifecycle.fireCreated(owner,owner.getUniqueId(),character);assertEquals(1,events.size());var event=assertInstanceOf(CharacterCreatedEvent.class,events.getFirst());assertSame(owner,event.getOwner());assertEquals(owner.getUniqueId(),event.getOwnerUuid());assertSame(character,event.getCharacter());assertSame(CharacterCreatedEvent.getHandlerList(),event.getHandlers());assertFalse(event.isAsynchronous());}
    @Test void activationEventIncludesThePreviousCharacterWithoutMutatingEitherModel(){CharacterLifecycle.fireActivated(owner,owner.getUniqueId(),character,previous);var event=assertInstanceOf(CharacterActivatedEvent.class,events.getFirst());assertSame(owner,event.getOwner());assertEquals(owner.getUniqueId(),event.getOwnerUuid());assertSame(character,event.getCharacter());assertSame(previous,event.getPrevious());assertSame(CharacterActivatedEvent.getHandlerList(),event.getHandlers());assertTrue(character.isActive());assertFalse(previous.isActive());}
    @Test void classChangesPublishTheirOldAndNewIdsToRegisteredListeners(){CharacterLifecycle.notifyClassChange(owner,owner.getUniqueId(),character,"HUMAN","ARCHER");var event=assertInstanceOf(CharacterClassChangeEvent.class,events.getFirst());assertSame(owner,event.getOwner());assertEquals(owner.getUniqueId(),event.getOwnerUuid());assertSame(character,event.getCharacter());assertEquals("HUMAN",event.getOldClassId());assertEquals("ARCHER",event.getNewClassId());assertSame(CharacterClassChangeEvent.getHandlerList(),event.getHandlers());}
    @Test void raceChangesPublishTheirOldAndNewIdsToRegisteredListeners(){CharacterLifecycle.notifyRaceChange(owner,owner.getUniqueId(),character,"human","elf");var event=assertInstanceOf(CharacterRaceChangeEvent.class,events.getFirst());assertSame(owner,event.getOwner());assertEquals(owner.getUniqueId(),event.getOwnerUuid());assertSame(character,event.getCharacter());assertEquals("human",event.getOldRaceId());assertEquals("elf",event.getNewRaceId());assertSame(CharacterRaceChangeEvent.getHandlerList(),event.getHandlers());assertEquals("human",CharacterLifecycle.raceId(race));assertNull(CharacterLifecycle.raceId(null));}
    @Test void initialAndCaseOnlyClassOrRaceAssignmentsDoNotAnnounceChanges(){CharacterLifecycle.notifyClassChange(owner,owner.getUniqueId(),character,null,"HUMAN");CharacterLifecycle.notifyClassChange(owner,owner.getUniqueId(),character,"HUMAN",null);CharacterLifecycle.notifyClassChange(owner,owner.getUniqueId(),character,"HUMAN","human");CharacterLifecycle.notifyRaceChange(owner,owner.getUniqueId(),character,null,"human");CharacterLifecycle.notifyRaceChange(owner,owner.getUniqueId(),character,"human",null);CharacterLifecycle.notifyRaceChange(owner,owner.getUniqueId(),character,"Human","HUMAN");assertTrue(events.isEmpty());}
    @Test void offlineLifecycleEventsRetainAccountIdentityAndDispatchInOrder(){UUID account=owner.getUniqueId();owner.disconnect();CharacterLifecycle.fireCreated(null,account,character);CharacterLifecycle.fireActivated(null,account,character,null);CharacterLifecycle.notifyClassChange(null,account,character,"HUMAN","ARCHER");CharacterLifecycle.notifyRaceChange(null,account,character,"human","elf");assertEquals(List.of(CharacterCreatedEvent.class,CharacterActivatedEvent.class,CharacterClassChangeEvent.class,CharacterRaceChangeEvent.class),events.stream().map(Event::getClass).toList());var created=(CharacterCreatedEvent)events.get(0);assertNull(created.getOwner());assertEquals(account,created.getOwnerUuid());var activated=(CharacterActivatedEvent)events.get(1);assertNull(activated.getOwner());assertNull(activated.getPrevious());assertEquals(account,activated.getOwnerUuid());assertNull(((CharacterClassChangeEvent)events.get(2)).getOwner());assertNull(((CharacterRaceChangeEvent)events.get(3)).getOwner());}
}
