package net.tfminecraft.rpcharacters.conversation;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.util.*;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.chat.*;
import net.tfminecraft.rpcharacters.identity.MaskService;
import net.tfminecraft.rpcharacters.loaders.ChatLoader;
import net.tfminecraft.rpcharacters.managers.PlayerManager;
import net.tfminecraft.rpcharacters.objects.*;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.mockito.MockedStatic;
import org.mockbukkit.mockbukkit.MockBukkit;

class ConversationManagerTest {
    RuntimeTestState state;World world;Player alice,bob,third;RPCharacter a,b,c;ChatChannel channel;
    final List<AutoCloseable> boundaries=new ArrayList<>();final List<Player> residents=new ArrayList<>();
    final Map<Player,PlayerData> accounts=new HashMap<>();final Map<UUID,Player> online=new HashMap<>();
    final Set<Player> masked=new HashSet<>();final Map<Player,Location> locations=new HashMap<>();
    @BeforeEach void setup(){MockBukkit.mock();state=new RuntimeTestState(ConversationManager.class);Cache.attributes=new ArrayList<>();Cache.professions=new ArrayList<>();Cache.conversationReplyTimeoutSeconds=60;Cache.conversationPairCooldownHours=1;world=mock(World.class);when(world.getPlayers()).thenReturn(residents);alice=player("Alice",0);bob=player("Bob",5);third=player("Third",10);a=active(alice,"a");b=active(bob,"b");c=active(third,"c");channel=channel(10);boundary(PlayerManager.class).when(()->PlayerManager.get(any(Player.class))).thenAnswer(call->accounts.get(call.getArgument(0)));boundary(MaskService.class).when(()->MaskService.isMasked(any())).thenAnswer(call->masked.contains(call.getArgument(0)));boundary(ChatLoader.class).when(()->ChatLoader.getChannel(any())).thenAnswer(call->"rp".equalsIgnoreCase(call.getArgument(0))?channel:null);boundary(Bukkit.class).when(()->Bukkit.getPlayer(any(UUID.class))).thenAnswer(call->online.get(call.getArgument(0)));}
    @AfterEach void cleanup() throws Exception {for(int i=boundaries.size()-1;i>=0;i--)boundaries.get(i).close();MockBukkit.unmock();state.close();}
    <T> MockedStatic<T> boundary(Class<T> type){var m=mockStatic(type);boundaries.add(m);return m;}
    Player player(String name,int x){var p=mock(Player.class);when(p.getName()).thenReturn(name);when(p.getUniqueId()).thenReturn(UUID.randomUUID());when(p.isOnline()).thenReturn(true);when(p.getWorld()).thenAnswer(call->locations.get(p).getWorld());when(p.getGameMode()).thenReturn(GameMode.SURVIVAL);locations.put(p,new Location(world,x,64,0));when(p.getLocation()).thenAnswer(call->locations.get(p).clone());residents.add(p);online.put(p.getUniqueId(),p);return p;}
    RPCharacter active(Player p,String id){var ch=spy(new RPCharacter(p));ch.setId(id);ch.setName(id);doReturn(true).when(ch).isActive();var data=new PlayerData(p);data.addCharacter(ch);accounts.put(p,data);return ch;}
    ChatChannel channel(int range){var yaml=new YamlConfiguration();yaml.set("range",range);return new ChatChannel("rp",yaml);}
    void say(Player p){ConversationManager.recordChannelMessage(p,channel);}
    CharacterChatEvent event(Player p,String channelId,boolean mask,Set<Player> recipients){return new CharacterChatEvent(p,accounts.get(p)==null?null:accounts.get(p).getActiveCharacter(),channelId,"Hello","Name",recipients,mask,false);}
    @Test void replyCountsBothCharactersAndRefreshesSessionWithoutDoubleCounting(){say(alice);assertEquals(0,a.getConversationCount("b"));say(bob);assertEquals(1,a.getConversationCount("b"));assertEquals(1,b.getConversationCount("a"));assertTrue(ConversationManager.isInActiveConversation(a,System.currentTimeMillis()));assertEquals(1,ConversationManager.countActiveSessions(a,System.currentTimeMillis()));say(alice);say(bob);assertEquals(1,a.getConversationCount("b"));assertNotNull(a.getConversationLastAtMs().get("b"));a.setConversationLastAtMs(Map.of("b",1L));b.setConversationLastAtMs(Map.of("a",1L));say(alice);say(bob);assertEquals(2,a.getConversationCount("b"));assertEquals(2,b.getConversationCount("a"));}
    @Test void differentRepliersOnlyCompleteTheirOwnPendingConversations(){say(alice);say(third);assertEquals(1,a.getConversationCount("c"));assertEquals(0,a.getConversationCount("b"));say(bob);assertEquals(1,a.getConversationCount("b"));assertEquals(1,b.getConversationCount("c"));assertEquals(2,ConversationManager.countActiveSessions(b,System.currentTimeMillis()));}
    @Test void eventListenerSkipsOocMaskedNonSurvivalAndUnknownChannels(){var manager=new ConversationManager();for(String id:Arrays.asList(null,"LOOC","OOC","missing"))manager.onCharacterChat(event(alice,id,false,Set.of(bob)));manager.onCharacterChat(event(alice,"rp",true,Set.of(bob)));manager.onCharacterChat(event(null,"rp",false,Set.of(bob)));when(alice.getGameMode()).thenReturn(GameMode.CREATIVE);manager.onCharacterChat(event(alice,"rp",false,Set.of(bob)));when(alice.getGameMode()).thenReturn(GameMode.SURVIVAL);say(bob);assertEquals(0,a.getConversationCount("b"));manager.onCharacterChat(event(alice,"RP",false,Set.of(bob)));assertEquals(1,a.getConversationCount("b"));}
    @Test void recipientsWhoNeverHeardTheInitialMessageDoNotEarnConversationCredit(){var manager=new ConversationManager();manager.onCharacterChat(event(alice,"rp",false,Set.of(alice)));manager.onCharacterChat(event(bob,"rp",false,Set.of(alice,bob)));assertEquals(0,a.getConversationCount("b"),"The event recipient list records who could actually hear the first message");assertEquals(0,b.getConversationCount("a"));}
    @Test void publicInputAndMissingAccountGuardsLeaveCountsUntouched(){ConversationManager.recordChannelMessage(null,channel);ConversationManager.recordChannelMessage(alice,null);accounts.remove(alice);say(alice);accounts.put(alice,new PlayerData(alice));say(alice);assertTrue(a.getConversationCounts().isEmpty());ConversationManager.recordChannelMessage(bob,channel(0));say(alice);assertTrue(b.getConversationCounts().isEmpty());}
    @Test void outboundCandidatesMustBeSurvivalUnmaskedNearbyAndLoaded(){when(bob.getGameMode()).thenReturn(GameMode.CREATIVE);say(alice);when(bob.getGameMode()).thenReturn(GameMode.SURVIVAL);say(bob);assertEquals(0,a.getConversationCount("b"));masked.add(bob);say(alice);masked.remove(bob);accounts.remove(bob);say(alice);accounts.put(bob,new PlayerData(bob));say(alice);locations.put(third,new Location(world,11,64,0));say(alice);assertEquals(0,a.getConversationCount("c"));}
    @Test void replyWaitsWhileOriginalSpeakerIsOfflineMissingOrMasked(){say(alice);online.remove(alice.getUniqueId());say(bob);assertEquals(0,b.getConversationCount("a"));online.put(alice.getUniqueId(),alice);when(alice.isOnline()).thenReturn(false);say(bob);assertEquals(0,b.getConversationCount("a"));when(alice.isOnline()).thenReturn(true);masked.add(alice);say(bob);assertEquals(0,b.getConversationCount("a"));masked.clear();say(bob);assertEquals(1,b.getConversationCount("a"));}
    @Test void replyMustReachTheOriginalSpeakerInTheSameWorldAndRange(){say(alice);locations.put(alice,new Location(mock(World.class),0,64,0));residents.remove(alice);new ConversationManager().onCharacterChat(event(bob,"rp",false,Set.of(alice,bob)));assertEquals(0,b.getConversationCount("a"));locations.put(alice,new Location(world,100,64,0));residents.add(alice);say(bob);assertEquals(0,b.getConversationCount("a"));locations.put(alice,new Location(world,0,64,0));say(bob);assertEquals(1,b.getConversationCount("a"));}
    @Test void repliesDoNotAttachAnOldCharactersMessageToANewActiveCharacter(){say(alice);accounts.remove(alice);say(bob);accounts.put(alice,new PlayerData(alice));say(bob);var replacement=active(alice,"replacement");say(bob);assertTrue(replacement.getConversationCounts().isEmpty());assertTrue(a.getConversationCounts().isEmpty());assertEquals(0,b.getConversationCount("replacement"));}
    @Test void expiredPendingMessagesAndSessionsArePrunedBeforeANewConversation(){Cache.conversationReplyTimeoutSeconds=-1;say(alice);say(bob);assertTrue(a.getConversationCounts().isEmpty());ConversationManager.refreshActiveSession(a,b,System.currentTimeMillis());assertFalse(ConversationManager.isInActiveConversation(a,System.currentTimeMillis()));assertEquals(0,ConversationManager.countActiveSessions(a,System.currentTimeMillis()));say(third);Cache.conversationReplyTimeoutSeconds=60;say(alice);say(bob);assertEquals(1,a.getConversationCount("b"));}
    @Test void sessionsExpireAtDeadlineAndRefreshingReusesOneUnorderedPair(){Cache.conversationReplyTimeoutSeconds=1;ConversationManager.refreshActiveSession(a,b,1000);assertTrue(ConversationManager.isInActiveConversation(a,1999));assertTrue(ConversationManager.isInActiveConversation(b,1999));assertFalse(ConversationManager.isInActiveConversation(c,1999));assertFalse(ConversationManager.isInActiveConversation(a,2000));assertEquals(0,ConversationManager.countActiveSessions(a,2000));ConversationManager.refreshActiveSession(b,a,1500);assertEquals(1,ConversationManager.countActiveSessions(a,2000));assertEquals(1,ConversationManager.countActiveSessions(b,2000));assertEquals(0,ConversationManager.countActiveSessions(c,2000));}
    @Test void sessionPublicGuardsRejectNullAndBlankCharacterIds(){ConversationManager.refreshActiveSession(null,b,0);ConversationManager.refreshActiveSession(a,null,0);assertFalse(ConversationManager.isInActiveConversation(null,0));assertEquals(0,ConversationManager.countActiveSessions(null,0));var malformed=new RPCharacter(null);for(String id:Arrays.asList(null," ")){malformed.setId(id);ConversationManager.refreshActiveSession(malformed,b,0);ConversationManager.refreshActiveSession(a,malformed,0);assertFalse(ConversationManager.isInActiveConversation(malformed,0));assertEquals(0,ConversationManager.countActiveSessions(malformed,0));}assertEquals(0,ConversationManager.countActiveSessions(a,0));}
    @Test void topPartnersAreDescendingLimitedAndDoNotReorderCharacterState(){a.setConversationCounts(Map.of("one",1,"seven",7,"three",3));assertTrue(ConversationManager.getTopPartners(null,2).isEmpty());assertTrue(ConversationManager.getTopPartners(a,0).isEmpty());assertEquals(List.of(Map.entry("seven",7),Map.entry("three",3)),ConversationManager.getTopPartners(a,2));assertEquals(List.of(Map.entry("seven",7),Map.entry("three",3),Map.entry("one",1)),ConversationManager.getTopPartners(a,10));assertEquals(Map.of("one",1,"seven",7,"three",3),a.getConversationCounts());}
    @Test void pendingConversationPreservesIdentityAndExpiry(){var pending=new PendingConversation("first","second",alice.getUniqueId(),100);assertEquals("first",pending.getSpeakerCharacterId());assertEquals("second",pending.getListenerCharacterId());assertEquals(alice.getUniqueId(),pending.getSpeakerPlayerId());assertEquals(100,pending.getExpiresAtMs());assertFalse(pending.isExpired(99));assertTrue(pending.isExpired(101));assertEquals("second:first",PendingConversation.key("second","first"));}
    @Test void aCharacterWithoutAnIdentityDoesNotCreateAnActiveSession(){a.setId(null);say(alice);assertFalse(ConversationManager.isInActiveConversation(a,System.currentTimeMillis()));assertEquals(0,ConversationManager.countActiveSessions(b,System.currentTimeMillis()));}
    @Test void theInitialSpeakerMustAlsoHearTheReply(){var manager=new ConversationManager();manager.onCharacterChat(event(alice,"rp",false,Set.of(bob)));manager.onCharacterChat(event(bob,"rp",false,Set.of(bob)));assertEquals(0,a.getConversationCount("b"));assertEquals(0,b.getConversationCount("a"));}

}
