package net.tfminecraft.rpcharacters.persona;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.*;
import org.bukkit.*;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.event.player.PlayerQuitEvent;
import org.junit.jupiter.api.*;
import org.mockito.*;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.managers.PlayerManager;
import net.tfminecraft.rpcharacters.identity.NameColour;
import net.tfminecraft.rpcharacters.objects.*;

class PersonaRuntimeTest {
 ServerMock server;PlayerMock player;RPCharacters plugin;RuntimeTestState state;PlayerData data;RPCharacter character;PlayerManager manager;MockedStatic<RPCharacters> api;
 @BeforeEach void setup(){server=MockBukkit.mock();state=new RuntimeTestState(RPCharacters.class);plugin=mock(RPCharacters.class);when(plugin.isEnabled()).thenReturn(true);RPCharacters.plugin=plugin;player=server.addPlayer();data=new PlayerData(player);character=new RPCharacter(player);data.getCharacters().add(character);Cache.permissionGroups=new ArrayList<>();Cache.permissionGroupDefaults=new HashMap<>(Map.of("name-colour-stops",0,"character-switch-cooldown-days",14,"max-alive-characters",2,"wardrobe-skin-slots",1));manager=mock(PlayerManager.class);api=mockStatic(RPCharacters.class);api.when(RPCharacters::getPlayerManager).thenReturn(manager);}
 @AfterEach void cleanup(){PersonaCooldownManager.get().clear(player);api.close();state.close();MockBukkit.unmock();}
 PermissionGroupDefinition group(String id,int tier,boolean visible,String display,Map<String,Integer> perks){return new PermissionGroupDefinition(id,"rank."+id,display,tier,visible,perks);}
 @Test void rankPerksAggregateUsingMaxBenefitsAndMinCooldown(){assertEquals(0,PermissionGroupService.getNameColourStops(null));assertEquals(14,PermissionGroupService.getCharacterSwitchCooldownDays(player));assertEquals(2,PermissionGroupService.getMaxAliveCharacters(player));assertEquals(1,PermissionGroupService.getWardrobeSkinSlots(player));assertFalse(PermissionGroupService.canUseNameColour(player));Cache.permissionGroups.add(new PermissionGroupDefinition("bad",null,"Bad",0,true,Map.of()));Cache.permissionGroups.add(new PermissionGroupDefinition("blank"," ","Blank",0,true,Map.of()));Cache.permissionGroups.add(group("gold",2,true,"Gold",Map.of("name-colour-stops",2,"character-switch-cooldown-days",7,"max-alive-characters",4,"wardrobe-skin-slots",3)));assertEquals(0,PermissionGroupService.getNameColourStops(player));player.addAttachment(plugin,"rank.gold",true);assertEquals(2,PermissionGroupService.getNameColourStops(player));assertTrue(PermissionGroupService.canUseNameColour(player));assertEquals(7,PermissionGroupService.getCharacterSwitchCooldownDays(player));assertEquals(4,PermissionGroupService.getMaxAliveCharacters(player));assertEquals(3,PermissionGroupService.getWardrobeSkinSlots(player));}
 @Test void colourValidationHonoursLimitsAndStaffOverride(){assertTrue(PermissionGroupService.validateNameColourHexes(player,null,false).isPresent());assertTrue(PermissionGroupService.validateNameColourHexes(player,List.of(),true).isPresent());assertTrue(PermissionGroupService.validateNameColourHexes(player,List.of("a"),false).isPresent());assertTrue(PermissionGroupService.validateNameColourHexes(player,List.of("a"),true).isEmpty());Cache.permissionGroupDefaults.put("name-colour-stops",1);assertTrue(PermissionGroupService.validateNameColourHexes(player,List.of("a","b"),false).isPresent());assertTrue(PermissionGroupService.validateNameColourHexes(player,List.of("a"),false).isEmpty());}
 @Test void downgradeTrimsOrRemovesOnlyNonStaffColours(){PermissionGroupService.enforceNameColourOnLogin(null,data);PermissionGroupService.enforceNameColourOnLogin(player,null);var staff=new RPCharacter(player);staff.setNameColour(NameColour.solid("#123456"));staff.setNameColourStaffOverride(true);data.getCharacters().add(staff);data.getCharacters().add(null);data.getCharacters().add(new RPCharacter(player));character.setNameColour(NameColour.of(List.of("#112233","#445566")));Cache.permissionGroupDefaults.put("name-colour-stops",1);PermissionGroupService.enforceNameColourOnLogin(player,data);assertEquals(List.of("#112233"),character.getNameColour().getHexCodes());verify(manager).savePlayer(player);PermissionGroupService.enforceNameColourOnLogin(player,data);verify(manager).savePlayer(player);Cache.permissionGroupDefaults.put("name-colour-stops",0);PermissionGroupService.enforceNameColourOnLogin(player,data);assertNull(character.getNameColour());assertNotNull(staff.getNameColour());verify(manager,times(2)).savePlayer(player);}
 @Test void switchCooldownsHandleMissingExpiredAndDisabledValues(){assertFalse(PermissionGroupService.hasCharacterSwitchCooldown(null,data));assertFalse(PermissionGroupService.hasCharacterSwitchCooldown(player,null));assertEquals(0,PermissionGroupService.getRemainingCooldownMinutes(null,data));assertEquals(0,PermissionGroupService.getRemainingCooldownMinutes(player,null));assertFalse(PermissionGroupService.hasCharacterSwitchCooldown(player,data));assertEquals(0,PermissionGroupService.getRemainingCooldownMinutes(player,data));data.setLastCharacterSwitchAtMs(System.currentTimeMillis());assertTrue(PermissionGroupService.hasCharacterSwitchCooldown(player,data));assertTrue(PermissionGroupService.getRemainingCooldownMinutes(player,data)>0);data.setLastCharacterSwitchAtMs(1L);assertFalse(PermissionGroupService.hasCharacterSwitchCooldown(player,data));assertEquals(0,PermissionGroupService.getRemainingCooldownMinutes(player,data));Cache.permissionGroupDefaults.put("character-switch-cooldown-days",0);assertFalse(PermissionGroupService.hasCharacterSwitchCooldown(player,data));assertEquals(0,PermissionGroupService.getRemainingCooldownMinutes(player,data));assertNull(PermissionGroupService.migrateLegacyCooldownMinutes(0));assertTrue(PermissionGroupService.migrateLegacyCooldownMinutes(60)<System.currentTimeMillis());assertTrue(PermissionGroupService.migrateLegacyCooldownMinutes(Integer.MAX_VALUE)<=System.currentTimeMillis());}
 @Test void slotsRespectHardCapsAndLivingCharacterCounts(){Cache.maxCharacterSlots=0;assertEquals(10,CharacterSlotService.getHardSlotCap());Cache.characterSlots=null;assertEquals(0,CharacterSlotService.getDisplaySlotCount());Cache.characterSlots=new ArrayList<>(List.of(1,2,3,4,5,6));Cache.maxCharacterSlots=4;Cache.baseCharacterSlotCount=0;assertEquals(4,CharacterSlotService.getDisplaySlotCount());assertEquals(4,CharacterSlotService.getBaseRowSlotCount());Cache.baseCharacterSlotCount=3;assertEquals(3,CharacterSlotService.getBaseRowSlotCount());assertTrue(CharacterSlotService.shouldShowLockedSlot(2,2));assertFalse(CharacterSlotService.shouldShowLockedSlot(3,2));assertFalse(CharacterSlotService.hasFreeSlot(null,data));assertFalse(CharacterSlotService.hasFreeSlot(player,null));assertFalse(CharacterSlotService.isOverSlotLimit(null,data));assertFalse(CharacterSlotService.isOverSlotLimit(player,null));assertTrue(CharacterSlotService.hasFreeSlot(player,data));assertTrue(CharacterSlotService.isSlotUnlocked(player,0));data.getCharacters().add(new RPCharacter(player));assertFalse(CharacterSlotService.hasFreeSlot(player,data));data.getCharacters().add(new RPCharacter(player));assertTrue(CharacterSlotService.isOverSlotLimit(player,data));}
 @Test void lockedSlotLoreUsesTheLowestVisibleRankAndDisplayFallback(){assertTrue(CharacterSlotService.getUnlockRequirementLore(2).contains("higher rank"));Cache.permissionGroups.add(group("hidden",0,false,"Hidden",Map.of("max-alive-characters",4)));Cache.permissionGroups.add(group("gold",2,true,"&6Gold",Map.of("max-alive-characters",4)));assertEquals("gold",CharacterSlotService.getMinimumVisibleUnlockGroup(2).orElseThrow().getId());assertTrue(CharacterSlotService.getUnlockRequirementLore(2).contains("Gold"));Cache.permissionGroups.clear();Cache.permissionGroups.add(group("fallback",1,true," ",Map.of("max-alive-characters",4)));assertTrue(CharacterSlotService.getUnlockRequirementLore(2).contains("fallback"));assertNull(CharacterSlotService.formatGroupDisplayName(null));assertEquals(" ",CharacterSlotService.formatGroupDisplayName(" "));}
 @Test void negativeSlotIndicesCannotBeUnlocked(){assertFalse(CharacterSlotService.isSlotUnlocked(player,-1));}
 @Test void cooldownsArePerFieldAndQuitClearsThem(){var c=PersonaCooldownManager.get();assertFalse(c.isOnCooldown(null,"alias",10));assertFalse(c.isOnCooldown(player,"alias",0));assertFalse(c.isOnCooldown(player,"alias",10));assertEquals(0,c.getRemainingSeconds(player,"alias"));c.applyCooldown(null,"alias",10);c.applyCooldown(player,"alias",0);c.applyCooldown(player,"alias",10);assertTrue(c.isOnCooldown(player,"alias",10));assertFalse(c.isOnCooldown(player,"other",10));assertEquals(0,c.getRemainingSeconds(player,"other"));assertTrue(c.getRemainingSeconds(player,"alias")>0);c.clear(null);c.onQuit(new PlayerQuitEvent(player,"quit"));assertFalse(c.isOnCooldown(player,"alias",10));} @Test void elapsedFieldCooldownsReportZero()throws Exception{var c=PersonaCooldownManager.get();c.applyCooldown(player,"alias",1);Thread.sleep(1100);assertFalse(c.isOnCooldown(player,"alias",1));assertEquals(0,c.getRemainingSeconds(player,"alias"));}

}
