package net.tfminecraft.rpcharacters.playtime;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.nio.file.*;
import java.util.*;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.scheduler.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.*;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.database.PlaytimeIndexDatabase;
import net.tfminecraft.rpcharacters.managers.PlayerManager;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.objects.races.Race;
import net.tfminecraft.rpcharacters.enums.Status;

class PlaytimeRuntimeTest {
 @TempDir Path folder;ServerMock server;RuntimeTestState state;RPCharacters plugin;PlayerMock player;PlayerData data;RPCharacter character;Map<Player,PlayerData> loaded=new HashMap<>();List<Runnable> ticks=new ArrayList<>();MockedStatic<PlayerManager> players;MockedStatic<Bukkit> bukkit;Path file;
 @BeforeEach void setup(){server=MockBukkit.mock();state=new RuntimeTestState(RPCharacters.class,PlaytimeService.class);Cache.attributes=new ArrayList<>();Cache.professions=new ArrayList<>();plugin=mock(RPCharacters.class);when(plugin.getDataFolder()).thenReturn(folder.toFile());RPCharacters.plugin=plugin;player=server.addPlayer("Player");data=new PlayerData(player);var cfg=new YamlConfiguration();cfg.set("name","Human");character=new RPCharacter(player,UUID.randomUUID().toString(),"Character",true,Status.ALIVE,new Race("human",cfg),new ArrayList<>(),null);data.getCharacters().add(character);loaded.put(player,data);players=mockStatic(PlayerManager.class);players.when(()->PlayerManager.get(any(Player.class))).thenAnswer(c->loaded.get(c.getArgument(0)));var scheduler=mock(BukkitScheduler.class);when(scheduler.runTaskTimer(eq(plugin),any(Runnable.class),anyLong(),anyLong())).thenAnswer(c->{ticks.add(c.getArgument(1));return mock(BukkitTask.class);});bukkit=mockStatic(Bukkit.class,CALLS_REAL_METHODS);bukkit.when(Bukkit::getScheduler).thenReturn(scheduler);file=folder.resolve("data/playtime-index.json");PlaytimeService.loadAllFromDisk();}
 @AfterEach void cleanup(){bukkit.close();players.close();state.close();MockBukkit.unmock();}
 void write(String body)throws Exception{Files.createDirectories(file.getParent());Files.writeString(file,body);}
 String row(UUID uuid,String name,String seconds){return "{\"uuid\":\""+uuid+"\",\"name\":\""+name+"\",\"seconds\":"+seconds+"}";}
 @Test void indexRoundTripsUtf8AndIgnoresIncompleteEntries(){var owner=UUID.randomUUID();PlaytimeIndexDatabase.saveAll(Arrays.asList(null,new PlaytimeIndexDatabase.Entry(null,"invalid",2),new PlaytimeIndexDatabase.Entry(owner,null,2),new PlaytimeIndexDatabase.Entry(owner,"Éowyn",-3)));var result=PlaytimeIndexDatabase.loadAll();assertEquals(1,result.size());assertEquals(owner,result.getFirst().getUuid());assertEquals("Éowyn",result.getFirst().getName());assertEquals(0,result.getFirst().getSeconds());assertTrue(Files.exists(file));}
 @Test void malformedRowsCannotHideFollowingValidRecords()throws Exception{var owner=UUID.randomUUID();write("[null,{},true,{\"uuid\":\"bad\",\"name\":\"Bad\"},"+row(owner,"BadNumber","\"oops\"")+","+row(owner,"Good","15")+"]");var result=PlaytimeIndexDatabase.loadAll();assertEquals(1,result.size());assertEquals("Good",result.getFirst().getName());assertEquals(15,result.getFirst().getSeconds());}
 @Test void missingSecondsDefaultToZeroAndInvalidWholeFileDoesNotThrow()throws Exception{var owner=UUID.randomUUID();write("[{\"uuid\":\""+owner+"\",\"name\":\"Legacy\"}]");assertEquals(0,PlaytimeIndexDatabase.loadAll().getFirst().getSeconds());write("{");assertTrue(PlaytimeIndexDatabase.loadAll().isEmpty());write("{}");assertTrue(PlaytimeIndexDatabase.loadAll().isEmpty());}
 @Test void oversizedStoredSecondsSaturateInsteadOfWrapping()throws Exception{write("["+row(UUID.randomUUID(),"Large","2147483648")+"]");assertEquals(Integer.MAX_VALUE,PlaytimeIndexDatabase.loadAll().getFirst().getSeconds());}
 @Test void persistenceFailurePreservesThePreviousIndex()throws Exception{var entry=new PlaytimeIndexDatabase.Entry(UUID.randomUUID(),"Before",5);PlaytimeIndexDatabase.saveAll(List.of(entry));String previous=Files.readString(file);var broken=new AbstractCollection<PlaytimeIndexDatabase.Entry>(){public int size(){return 1;}public Iterator<PlaytimeIndexDatabase.Entry> iterator(){throw new IllegalStateException("serialization failed");}};assertDoesNotThrow(()->PlaytimeIndexDatabase.saveAll(broken));assertEquals(previous,Files.readString(file));}
 @Test void refreshPublishesKnownAndMissingCharactersWithoutAddingTime(){assertNull(PlaytimeService.getSeconds((String)null));assertNull(PlaytimeService.getSeconds(" "));assertNull(PlaytimeService.getSeconds((UUID)null));assertNull(PlaytimeService.getSeconds(UUID.randomUUID()));assertNull(PlaytimeService.getSeconds("Unknown"));PlaytimeService.refresh(null);character.setOnlinePlaytimeSeconds(123);PlaytimeService.refresh(player);assertEquals(123,PlaytimeService.getSeconds(player.getUniqueId()));assertEquals(123,PlaytimeService.getSeconds("PLAYER"));assertEquals(123,character.getOnlinePlaytimeSeconds());PlaytimeService.refresh(player);assertEquals(1,PlaytimeService.getAll().size());loaded.remove(player);PlaytimeService.refresh(player);assertEquals(0,PlaytimeService.getSeconds("Player"));loaded.put(player,new PlayerData(player));PlaytimeService.refresh(player);assertEquals(0,PlaytimeService.getSeconds("Player"));PlaytimeService.shutdown();PlaytimeService.loadAllFromDisk();assertEquals(0,PlaytimeService.getSeconds(player.getUniqueId()));}
 @Test void aRenamedAccountRemovesItsOldNameAndCaseOnlyChangesPersist()throws Exception{write("["+row(player.getUniqueId(),"Previous","4")+"]");PlaytimeService.loadAllFromDisk();assertEquals(4,PlaytimeService.getSeconds("Previous"));PlaytimeService.refresh(player);assertNull(PlaytimeService.getSeconds("Previous"));assertEquals(0,PlaytimeService.getSeconds("Player"));write("["+row(player.getUniqueId(),"PLAYER","4")+"]");PlaytimeService.loadAllFromDisk();character.setOnlinePlaytimeSeconds(4);PlaytimeService.refresh(player);assertEquals("Player",PlaytimeService.getAll().getFirst().getName());}
 @Test void timersCreditOnlyTheActiveCharacterAndAutosaveOnlyWhenDirty()throws Exception{PlaytimeService.startTicks();assertEquals(2,ticks.size());ticks.get(1).run();assertFalse(Files.exists(file));ticks.getFirst().run();assertEquals(60,character.getOnlinePlaytimeSeconds());assertEquals(60,PlaytimeService.getSeconds("Player"));ticks.get(1).run();assertTrue(Files.readString(file).contains("60"));Files.delete(file);ticks.get(1).run();assertFalse(Files.exists(file));loaded.remove(player);ticks.getFirst().run();assertEquals(60,character.getOnlinePlaytimeSeconds());assertEquals(0,PlaytimeService.getSeconds("Player"));}
 @Test void deadCharactersCannotAccrueMoreOnlineTime(){character.setStatus(Status.DEAD);character.setOnlinePlaytimeSeconds(12);PlaytimeService.startTicks();ticks.getFirst().run();assertEquals(12,character.getOnlinePlaytimeSeconds());assertEquals(0,PlaytimeService.getSeconds("Player"));}
 @Test void failedAutosaveIsRetriedWithoutAnotherPlaytimeChange()throws Exception{PlaytimeService.startTicks();ticks.getFirst().run();Files.createDirectories(folder);Files.writeString(folder.resolve("data"),"blocks directory");ticks.get(1).run();Files.delete(folder.resolve("data"));ticks.get(1).run();assertTrue(Files.exists(file),"Dirty playtime must survive a failed autosave");} @Test void partialWritesAndFailedMovesPreserveTheIndexAndCleanStagingFiles()throws Exception{var entry=new PlaytimeIndexDatabase.Entry(player.getUniqueId(),"Player",60);PlaytimeIndexDatabase.saveAll(List.of(entry));String previous=Files.readString(file);for(String operation:List.of("writeString","move")){var staged=new java.util.concurrent.atomic.AtomicReference<Path>();try(var files=mockStatic(Files.class,c->{if(c.getMethod().getName().equals(operation)){Path path=c.getArgument(0);staged.set(path);if(operation.equals("writeString"))Files.write(path,"partial".getBytes(java.nio.charset.StandardCharsets.UTF_8));throw new java.io.IOException("disk failure");}return c.callRealMethod();})){assertFalse(PlaytimeIndexDatabase.trySaveAll(List.of(entry)));}assertNotNull(staged.get());assertNotEquals(file,staged.get());assertFalse(Files.exists(staged.get()));assertEquals(previous,Files.readString(file));}}
 @Test void cleanupFailurePreservesTheOriginalIoFailure()throws Exception{var entry=new PlaytimeIndexDatabase.Entry(player.getUniqueId(),"Player",60);PlaytimeIndexDatabase.saveAll(List.of(entry));String previous=Files.readString(file);var failure=new java.io.IOException("disk full");var cleanup=new java.io.IOException("cannot unlink");var staged=new java.util.concurrent.atomic.AtomicReference<Path>();try{try(var files=mockStatic(Files.class,c->{if(c.getMethod().getName().equals("writeString")){staged.set(c.getArgument(0));throw failure;}if(c.getMethod().getName().equals("deleteIfExists"))throw cleanup;return c.callRealMethod();})){assertFalse(PlaytimeIndexDatabase.trySaveAll(List.of(entry)));}assertArrayEquals(new Throwable[]{cleanup},failure.getSuppressed());assertEquals(previous,Files.readString(file));}finally{if(staged.get()!=null)Files.deleteIfExists(staged.get());}}

 @Test void joinAndActivationEventsRefreshTheIndexImmediately(){var listener=new PlaytimeListener();character.setOnlinePlaytimeSeconds(77);listener.onJoin(new org.bukkit.event.player.PlayerJoinEvent(player,(String)null));assertEquals(77,PlaytimeService.getSeconds(player.getUniqueId()));character.setOnlinePlaytimeSeconds(88);listener.onCharacterActivated(new net.tfminecraft.rpcharacters.lifecycle.CharacterActivatedEvent(player,player.getUniqueId(),character,null));assertEquals(88,PlaytimeService.getSeconds(player.getUniqueId()));listener.onCharacterActivated(new net.tfminecraft.rpcharacters.lifecycle.CharacterActivatedEvent(null,player.getUniqueId(),character,null));assertEquals(88,PlaytimeService.getSeconds(player.getUniqueId()));}
}
