package net.tfminecraft.rpcharacters.permadeath;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.nio.*;
import java.nio.file.*;
import java.util.*;
import java.util.zip.GZIPOutputStream;
import org.bukkit.*;
import org.junit.jupiter.api.Test;
import com.sk89q.worldedit.bukkit.BukkitAdapter;
import com.sk89q.worldedit.math.BlockVector3;
import com.sk89q.worldguard.WorldGuard;
import com.sk89q.worldguard.protection.ApplicableRegionSet;
import com.sk89q.worldguard.protection.regions.*;
import net.tfminecraft.rpcharacters.RPCharacters;
import net.tfminecraft.simplefactions.SimpleFactions;
import net.tfminecraft.simplefactions.loaders.RegionLoader;
import net.tfminecraft.simplefactions.map.*;
import net.tfminecraft.simplefactions.map.presence.ProvincePresenceService;
import net.tfminecraft.simplefactions.war.battle.engine.core.*;

class PermadeathBridgesTest extends ZoneBridgeFixture {
    @Test void missingWorldGuardLeavesItsPublicQueriesUnavailable(){WorldGuardBridge.init();assertFalse(WorldGuardBridge.isAvailable());assertNull(WorldGuardBridge.getPermadeathZoneAt(player.getLocation()));assertFalse(WorldGuardBridge.isInPermadeathZone(player.getLocation()));assertTrue(WorldGuardBridge.getRegionIdsAt(player.getLocation()).isEmpty());verify(logger).warning(contains("WorldGuard not found"));}
    @Test void worldGuardInitializationFailureIsLoggedAndDoesNotAdvertiseReadiness(){when(pluginManager.isPluginEnabled("WorldGuard")).thenReturn(true);var api=boundary(WorldGuard.class);api.when(WorldGuard::getInstance).thenThrow(new IllegalStateException("not initialized"));assertDoesNotThrow(WorldGuardBridge::init);assertFalse(WorldGuardBridge.isAvailable());verify(logger).warning(contains("not initialized"));}
    @Test void nullWorldGuardRegionContainerIsNotAReadyBridge(){when(pluginManager.isPluginEnabled("WorldGuard")).thenReturn(true);var guard=mock(WorldGuard.class,RETURNS_DEEP_STUBS);when(guard.getPlatform().getRegionContainer()).thenReturn(null);boundary(WorldGuard.class).when(WorldGuard::getInstance).thenReturn(guard);WorldGuardBridge.init();assertFalse(WorldGuardBridge.isAvailable());}
    @Test void worldGuardLookupKeepsRegionOrderAndIgnoresUnconfiguredRegions(){try(var wg=new WorldGuardBoundary()){var ordinary=new ProtectedCuboidRegion("ordinary",BlockVector3.ZERO,BlockVector3.at(5,100,5));var dangerous=new ProtectedCuboidRegion("REGION_I",BlockVector3.ZERO,BlockVector3.at(5,100,5));when(wg.regions.iterator()).thenAnswer(call->List.<ProtectedRegion>of(ordinary,dangerous).iterator());WorldGuardBridge.init();assertTrue(WorldGuardBridge.isAvailable());assertEquals(List.of("ordinary","region_i"),WorldGuardBridge.getRegionIdsAt(player.getLocation()));assertSame(zone("REGION_I"),WorldGuardBridge.getPermadeathZoneAt(player.getLocation()));assertTrue(WorldGuardBridge.isInPermadeathZone(player.getLocation()));when(wg.regions.iterator()).thenAnswer(call->List.<ProtectedRegion>of(ordinary).iterator());assertNull(WorldGuardBridge.getPermadeathZoneAt(player.getLocation()));assertNull(WorldGuardBridge.getPermadeathZoneAt(null));assertNull(WorldGuardBridge.getPermadeathZoneAt(new Location(null,0,70,0)));assertTrue(WorldGuardBridge.getRegionIdsAt(null).isEmpty());assertTrue(WorldGuardBridge.getRegionIdsAt(new Location(null,0,70,0)).isEmpty());}}
    @Test void failingWorldGuardQueryReturnsNoRegionsAndLogsItsCause(){try(var wg=new WorldGuardBoundary()){WorldGuardBridge.init();when(wg.container.createQuery()).thenThrow(new IllegalStateException("query unavailable"));assertTrue(WorldGuardBridge.getRegionIdsAt(player.getLocation()).isEmpty());verify(logger).warning(contains("query unavailable"));}}
    @Test void absentSimpleFactionsLeavesRegionQueriesUnavailable(){SimpleFactionsRegionBridge.init();assertFalse(SimpleFactionsRegionBridge.isAvailable());assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(player,player.getLocation()));}
    @Test void simpleFactionsBattleExemptionTracksOnlyStartedBattles(){try(var sf=new SimpleFactionsBoundary()){SimpleFactionsRegionBridge.init();assertTrue(SimpleFactionsRegionBridge.isAvailable());var battles=boundary(BattleManager.class);assertFalse(PermadeathBattleExemption.isInStartedBattle(player));var battle=mock(Battle.class);battles.when(()->BattleManager.getBattleByMemberId(player.getUniqueId())).thenReturn(battle);assertFalse(PermadeathBattleExemption.isInStartedBattle(player));when(battle.hasStarted()).thenReturn(true);assertTrue(PermadeathBattleExemption.isInStartedBattle(player));}}
    @Test void optionalBattleApiFailureCannotBreakTheDeathHandler(){try(var sf=new SimpleFactionsBoundary()){SimpleFactionsRegionBridge.init();boundary(BattleManager.class).when(()->BattleManager.getBattleByMemberId(player.getUniqueId())).thenThrow(new NoClassDefFoundError("incompatible battle API"));assertFalse(assertDoesNotThrow(()->PermadeathBattleExemption.isInStartedBattle(player)));}}
    @Test void disablingTheSimpleFactionsBridgeAlsoClearsItsBattleExemption(){try(var sf=new SimpleFactionsBoundary()){SimpleFactionsRegionBridge.init();var battle=mock(Battle.class);when(battle.hasStarted()).thenReturn(true);boundary(BattleManager.class).when(()->BattleManager.getBattleByMemberId(player.getUniqueId())).thenReturn(battle);assertTrue(PermadeathBattleExemption.isInStartedBattle(player));when(pluginManager.isPluginEnabled("SimpleFactions")).thenReturn(false);SimpleFactionsRegionBridge.init();assertFalse(SimpleFactionsRegionBridge.isAvailable());assertFalse(PermadeathBattleExemption.isInStartedBattle(player));}}
    @Test void cachedProvinceResolvesItsConfiguredRegionWhenNoLocationWasProvided(){try(var sf=new SimpleFactionsBoundary()){SimpleFactionsRegionBridge.init();when(sf.presence.getCurrentProvince(player)).thenReturn(7);assertSame(zone("REGION_I"),SimpleFactionsRegionBridge.getPermadeathZoneAt(player,null));}}
    @Test void requestedDestinationTakesPrecedenceOverThePlayersStalePresenceCache() throws Exception {try(var sf=new SimpleFactionsBoundary()){SimpleFactionsRegionBridge.init();when(sf.presence.getCurrentProvince(player)).thenReturn(7);when(sf.plugin.getProvinceGrid()).thenReturn(grid());assertSame(zone("lowlands"),SimpleFactionsRegionBridge.getPermadeathZoneAt(player,new Location(world,1,70,1)),"Movement and teleport checks must use the requested destination, before SF updates presence");}}
    @Test void provinceGridFallbackHandlesMissingCoordinatesPluginAndGrid() throws Exception {try(var sf=new SimpleFactionsBoundary()){SimpleFactionsRegionBridge.init();assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(null,null));assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(player,new Location(null,0,70,0)));sf.entry.when(SimpleFactions::getInstance).thenReturn(null);assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(null,player.getLocation()));sf.entry.when(SimpleFactions::getInstance).thenReturn(sf.plugin);assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(null,player.getLocation()));when(sf.plugin.getProvinceGrid()).thenReturn(grid());assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(null,new Location(world,2,70,2)));assertSame(zone("lowlands"),SimpleFactionsRegionBridge.getPermadeathZoneAt(null,new Location(world,1,70,1)));sf.regions.when(()->RegionLoader.getByProvince(9)).thenReturn(null);assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(null,new Location(world,1,70,1)));}}
    @Test void simpleFactionsLookupFailureIsLoggedWithoutBreakingZoneQueries(){try(var sf=new SimpleFactionsBoundary()){SimpleFactionsRegionBridge.init();when(sf.presence.getCurrentProvince(player)).thenThrow(new IllegalStateException("presence unavailable"));assertNull(SimpleFactionsRegionBridge.getPermadeathZoneAt(player,null));verify(logger).warning(contains("presence unavailable"));}}
    @Test void areaLookupPrefersWorldGuardAndCachesTheOptionalSimpleFactionsMethod(){when(pluginManager.isPluginEnabled("SimpleFactions")).thenReturn(true);var wg=boundary(WorldGuardBridge.class);var sf=boundary(SimpleFactionsRegionBridge.class);wg.when(WorldGuardBridge::isAvailable).thenReturn(true);var wgZone=zone("REGION_I");var sfZone=zone("lowlands");wg.when(()->WorldGuardBridge.getPermadeathZoneAt(player.getLocation())).thenReturn(wgZone);assertSame(wgZone,PermadeathAreaLookup.getPermadeathZoneAt(player,player.getLocation()));sf.verifyNoInteractions();wg.when(()->WorldGuardBridge.getPermadeathZoneAt(player.getLocation())).thenReturn(null);sf.when(()->SimpleFactionsRegionBridge.getPermadeathZoneAt(player,player.getLocation())).thenReturn(sfZone);assertSame(sfZone,PermadeathAreaLookup.getPermadeathZoneAt(player,player.getLocation()));assertTrue(PermadeathAreaLookup.isInPermadeathZone(player,player.getLocation()));sf.when(()->SimpleFactionsRegionBridge.getPermadeathZoneAt(null,player.getLocation())).thenReturn(sfZone);assertSame(sfZone,PermadeathAreaLookup.getPermadeathZoneAt(player.getLocation()));}
    @Test void optionalAreaLookupHandlesAbsentFailedAndIncompatiblePlugins(){var wg=boundary(WorldGuardBridge.class);assertNull(PermadeathAreaLookup.getPermadeathZoneAt(player.getLocation()));when(pluginManager.isPluginEnabled("SimpleFactions")).thenThrow(new NoClassDefFoundError("plugin manager shutting down"));assertNull(PermadeathAreaLookup.getPermadeathZoneAt(player.getLocation()));doReturn(true).when(pluginManager).isPluginEnabled("SimpleFactions");var sf=boundary(SimpleFactionsRegionBridge.class);sf.when(()->SimpleFactionsRegionBridge.getPermadeathZoneAt(any(),any())).thenThrow(new IllegalStateException("SF not ready"));assertNull(PermadeathAreaLookup.getPermadeathZoneAt(player,player.getLocation()));verify(logger).warning(contains("SimpleFactions permadeath lookup failed"));RPCharacters.plugin=null;assertNull(PermadeathAreaLookup.getPermadeathZoneAt(player,player.getLocation()));}

    ProvinceGrid grid() throws Exception {var payload=ByteBuffer.allocate(8+8).order(ByteOrder.LITTLE_ENDIAN);payload.putInt(2).putInt(2).putShort((short)7).putShort((short)0).putShort((short)0).putShort((short)9);var path=folder.resolve("grid.bin.gz");try(var stream=new GZIPOutputStream(Files.newOutputStream(path))){stream.write(payload.array());}return ProvinceGrid.load(path.toFile());}
    final class WorldGuardBoundary implements AutoCloseable {final WorldGuard guard=mock(WorldGuard.class,RETURNS_DEEP_STUBS);final RegionContainer container=mock(RegionContainer.class);final RegionQuery query=mock(RegionQuery.class);final ApplicableRegionSet regions=mock(ApplicableRegionSet.class);WorldGuardBoundary(){when(pluginManager.isPluginEnabled("WorldGuard")).thenReturn(true);when(guard.getPlatform().getRegionContainer()).thenReturn(container);when(container.createQuery()).thenReturn(query);when(query.getApplicableRegions(any(com.sk89q.worldedit.util.Location.class))).thenReturn(regions);when(regions.iterator()).thenAnswer(call->Collections.emptyIterator());boundary(WorldGuard.class).when(WorldGuard::getInstance).thenReturn(guard);var worldEdit=mock(com.sk89q.worldedit.bukkit.WorldEditPlugin.class);var adapter=mock(com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter.class);when(worldEdit.getBukkitImplAdapter()).thenReturn(adapter);boundary(com.sk89q.worldedit.bukkit.WorldEditPlugin.class).when(com.sk89q.worldedit.bukkit.WorldEditPlugin::getInstance).thenReturn(worldEdit);var adapted=new com.sk89q.worldedit.util.Location(mock(com.sk89q.worldedit.world.World.class),0,70,0);boundary(BukkitAdapter.class).when(()->BukkitAdapter.adapt(any(Location.class))).thenReturn(adapted);}public void close(){}}
    final class SimpleFactionsBoundary implements AutoCloseable {final SimpleFactions plugin=mock(SimpleFactions.class);final ProvincePresenceService presence=mock(ProvincePresenceService.class);final org.mockito.MockedStatic<SimpleFactions> entry=boundary(SimpleFactions.class);final org.mockito.MockedStatic<RegionLoader> regions=boundary(RegionLoader.class);SimpleFactionsBoundary(){when(pluginManager.isPluginEnabled("SimpleFactions")).thenReturn(true);entry.when(SimpleFactions::getInstance).thenReturn(plugin);boundary(ProvincePresenceService.class).when(ProvincePresenceService::getInstance).thenReturn(presence);when(presence.getCurrentProvince(any(org.bukkit.entity.Player.class))).thenReturn(ProvincePresenceService.UNKNOWN_PROVINCE);var highlands=new MapRegion("REGION_I","Highlands",Set.of(7));var lowlands=new MapRegion("lowlands","Lowlands",Set.of(9));regions.when(()->RegionLoader.getByProvince(7)).thenReturn(highlands);regions.when(()->RegionLoader.getByProvince(9)).thenReturn(lowlands);}public void close(){}}
}
