package net.tfminecraft.rpcharacters.party;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.nio.file.*;
import java.util.*;
import net.tfminecraft.rpcharacters.RuntimeTestState;
import net.tfminecraft.rpcharacters.chat.*;
import net.tfminecraft.rpcharacters.loaders.PartyLoader;
import org.bukkit.*;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.MockedStatic;
import org.mockbukkit.mockbukkit.MockBukkit;

class PartyCommandTest {
    @TempDir Path folder;RuntimeTestState state;MockedStatic<Bukkit> bukkit;Player leader,member,other,offline;PartyManager manager;
    final Map<UUID,Player> online=new LinkedHashMap<>();final Map<String,Player> byName=new HashMap<>();final Map<UUID,OfflinePlayer> known=new HashMap<>();
    final Map<Player,List<String>> messages=new HashMap<>();final Map<Player,Set<String>> permissions=new HashMap<>();
    @BeforeEach void setup() throws Exception {MockBukkit.mock();state=new RuntimeTestState(PartyLoader.class);PartyManager.clearForTests();manager=PartyManager.get();var config=new YamlConfiguration();config.set("messages.players-only","Players only");config.set("messages.usage","Party usage");config.set("messages.created","Created {name}");config.set("messages.invited-leader","Invited {player} to {name}");config.set("messages.invited-target","{leader} invited you to {name}");config.set("messages.joined","Joined {name}");config.set("messages.joined-notify","{player} joined");config.set("messages.no-invite","You have no party invite");config.set("messages.not-leader","Only the leader can do that");config.set("messages.not-in-party","Not in party");config.set("messages.member-left","{player} left");config.set("messages.disbanded","Party disbanded");config.set("messages.member-kicked","Kicked {player}");config.set("messages.kicked-notify","You were kicked");config.set("messages.target-not-found","Missing {player}");config.set("messages.info-header","Party {name} led by {leader}");config.set("messages.info-line","Member {player}");var file=folder.resolve("party.yml");config.save(file.toFile());new PartyLoader().load(file.toFile());leader=player("Leader");member=player("Member");other=player("Other");offline=player("Offline");bukkit=mockStatic(Bukkit.class,CALLS_REAL_METHODS);bukkit.when(()->Bukkit.getPlayer(any(UUID.class))).thenAnswer(c->online.get(c.getArgument(0)));bukkit.when(()->Bukkit.getPlayerExact(anyString())).thenAnswer(c->byName.get(c.getArgument(0)));bukkit.when(Bukkit::getOnlinePlayers).thenAnswer(c->new ArrayList<>(online.values()));bukkit.when(()->Bukkit.getOfflinePlayer(any(UUID.class))).thenAnswer(c->known.get(c.getArgument(0)));}
    @AfterEach void cleanup(){for(Player p:messages.keySet())ChatChannelPreferenceManager.get().clear(p);bukkit.close();PartyManager.clearForTests();MockBukkit.unmock();state.close();}
    Player player(String name){var p=mock(Player.class);when(p.getUniqueId()).thenReturn(UUID.randomUUID());when(p.getName()).thenReturn(name);when(p.getServer()).thenReturn(Bukkit.getServer());when(p.isOnline()).thenReturn(true);online.put(p.getUniqueId(),p);known.put(p.getUniqueId(),p);byName.put(name,p);messages.put(p,new ArrayList<>());permissions.put(p,new HashSet<>());when(p.hasPermission(anyString())).thenAnswer(c->permissions.get(p).contains(c.getArgument(0)));doAnswer(c->{messages.get(p).add(c.getArgument(0));return null;}).when(p).sendMessage(anyString());return p;}
    void cmd(Player player,String... tail){var args=new ArrayList<>(List.of("party"));args.addAll(Arrays.asList(tail));assertTrue(PartyCommand.handle(player,args.toArray(String[]::new)));}
    String text(Player p){return String.join("\n",messages.get(p));}
    void create(){assertTrue(manager.create(leader.getUniqueId(),"Scouts").ok());}
    void join(Player p){assertTrue(manager.invite(leader.getUniqueId(),p.getUniqueId()).ok());assertTrue(manager.join(p.getUniqueId()).ok());}
    void disconnect(Player p){online.remove(p.getUniqueId());byName.remove(p.getName());when(p.isOnline()).thenReturn(false);}
    @Test void commandEntryUsageAndArgumentValidationDoNotMutateParties(){var console=mock(CommandSender.class);assertTrue(PartyCommand.handle(console,null));verify(console).sendMessage("Players only");assertTrue(PartyCommand.handle(leader,null));assertTrue(PartyCommand.handle(leader,new String[0]));cmd(leader);cmd(leader,"unknown");cmd(leader,"create");cmd(leader,"invite");cmd(leader,"invite","Member","extra");cmd(leader,"kick");cmd(leader,"kick","Member","extra");assertNull(manager.getParty(leader.getUniqueId()));assertEquals(9,messages.get(leader).size());assertTrue(messages.get(leader).stream().allMatch("Party usage"::equals));}
    @Test void createInviteJoinAndInfoDeliverActualManagerResults(){cmd(leader,"CREATE","The","Scouts");assertEquals("The Scouts",manager.getParty(leader.getUniqueId()).getName());assertEquals("Created The Scouts",text(leader));cmd(leader,"invite","missing");assertTrue(text(leader).contains("Missing missing"));cmd(leader,"invite","Member");assertTrue(text(leader).contains("Invited Member to The Scouts"));assertEquals("Leader invited you to The Scouts",text(member));cmd(member,"join");assertTrue(text(member).contains("Joined The Scouts"));assertTrue(text(leader).contains("Member joined"));cmd(member,"info");assertTrue(text(member).contains("Party The Scouts led by Leader"));assertTrue(text(member).contains("Member Member"));cmd(other,"info");assertEquals("Not in party",text(other));cmd(other,"join");assertTrue(text(other).contains("no party invite"));}
    @Test void kickReportsMissingTargetsAndOnlyNotifiesARealRemovedMember(){create();join(member);cmd(member,"kick","Leader");assertTrue(text(member).contains("leader"));cmd(leader,"kick","missing");assertTrue(text(leader).contains("Missing missing"));cmd(leader,"kick","Other");assertTrue(text(leader).contains("Missing Other"));cmd(leader,"kick","Member");assertNull(manager.getParty(member.getUniqueId()));assertTrue(text(leader).contains("Kicked Member"));assertTrue(text(member).contains("You were kicked"));}
    @Test void memberLeaveNotifiesTheRemainingOnlineMembers(){create();join(member);join(offline);disconnect(offline);cmd(member,"leave");assertNull(manager.getParty(member.getUniqueId()));assertEquals("Member left",text(leader));assertTrue(text(offline).isEmpty());}
    @Test void memberLeaveAlsoAcknowledgesTheDepartingPlayer(){create();join(member);cmd(member,"leave");assertTrue(text(member).contains("left"),"The leaving player needs confirmation even when no other member is online");}
    @Test void leaderDisbandNotifiesOnlineMembersOnceAndInvalidatesInvites(){create();join(member);join(offline);manager.invite(leader.getUniqueId(),other.getUniqueId());disconnect(offline);cmd(leader,"leave");assertEquals("Party disbanded",text(leader));assertEquals("Party disbanded",text(member));assertTrue(text(offline).isEmpty());assertNull(manager.getPendingInvite(other.getUniqueId()));assertNull(manager.getParty(member.getUniqueId()));cmd(leader,"leave");assertTrue(text(leader).contains("Not in party"));}
    @Test void joiningWhileTheLeaderIsOfflineStillAddsPersistentMembership(){create();assertTrue(manager.invite(leader.getUniqueId(),member.getUniqueId()).ok());disconnect(leader);cmd(member,"join");assertSame(manager.getParty(leader.getUniqueId()),manager.getParty(member.getUniqueId()));assertEquals("Joined Scouts",text(member));assertTrue(text(leader).isEmpty());}
    @Test void leadersCanKickOfflineMembersWhoseMembershipSurvivesLogout(){create();join(member);disconnect(member);cmd(leader,"kick","Member");assertNull(manager.getParty(member.getUniqueId()),"Persistent party membership must remain manageable while members are offline");assertTrue(text(leader).contains("Kicked Member"));assertTrue(text(member).isEmpty());}
    @Test void completionsAreLocaleIndependentAndInviteOnlyUnattachedPlayers(){Locale.setDefault(Locale.forLanguageTag("tr-TR"));assertTrue(PartyCommand.tabComplete(mock(CommandSender.class),new String[]{"party",""}).isEmpty());assertEquals(List.of("invite","info"),PartyCommand.tabComplete(leader,new String[]{"party","I"}));assertTrue(PartyCommand.tabComplete(leader,new String[]{"party"}).isEmpty());assertTrue(PartyCommand.tabComplete(leader,new String[]{"party","create",""}).isEmpty());assertTrue(PartyCommand.tabComplete(leader,new String[]{"party","invite",""}).isEmpty());create();join(member);assertTrue(PartyCommand.tabComplete(member,new String[]{"party","invite",""}).isEmpty());assertEquals(List.of("Other","Offline"),PartyCommand.tabComplete(leader,new String[]{"party","INVITE","O"}));assertTrue(PartyCommand.tabComplete(leader,new String[]{"party","invite","z"}).isEmpty());}
    @Test void kickCompletionListsOnlyMembersOfTheCurrentParty(){create();join(member);assertEquals(List.of("Member"),PartyCommand.tabComplete(leader,new String[]{"party","kick",""}),"Nonmembers cannot be kicked and should not be suggested");}
    @Test void partyResolverIncludesOnlyOnlineVisibleMembersWithReadPermission(){var resolver=new PartyChatRecipientResolver();var config=new YamlConfiguration();config.set("read-perm","party.read");var channel=new ChatChannel("party",config);assertTrue(resolver.resolve(null,channel).isEmpty());assertTrue(resolver.resolve(leader,null).isEmpty());assertTrue(resolver.resolve(leader,channel).isEmpty());create();join(member);join(offline);disconnect(offline);permissions.get(leader).add("party.read");permissions.get(member).add("party.read");permissions.get(other).add("party.read");assertEquals(Set.of(leader,member),resolver.resolve(leader,channel));ChatChannelPreferenceManager.get().toggleChannelVisibility(member,"party");assertEquals(Set.of(leader),resolver.resolve(leader,channel));permissions.get(leader).clear();assertTrue(resolver.resolve(leader,channel).isEmpty());when(member.isOnline()).thenReturn(false);assertTrue(resolver.resolve(leader,channel).isEmpty());}
    @Test void quitListenerDropsPendingInviteButPreservesExistingMembership(){create();join(member);manager.invite(leader.getUniqueId(),other.getUniqueId());var listener=new PartyListener();listener.onQuit(new PlayerQuitEvent(other,"bye"));assertNull(manager.getPendingInvite(other.getUniqueId()));listener.onQuit(new PlayerQuitEvent(member,"bye"));assertNotNull(manager.getParty(member.getUniqueId()));manager.handleQuit((Player)null);manager.handleQuit((UUID)null);}
}
