package net.tfminecraft.rpcharacters.professions;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.util.*;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.plugin.ServicePriority;
import org.junit.jupiter.api.*;
import org.mockito.MockedStatic;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.luckperms.api.LuckPerms;
import net.luckperms.api.node.Node;
import net.luckperms.api.node.types.PermissionNode;
import net.luckperms.api.model.user.User;
import net.luckperms.api.model.data.NodeMap;
import net.Indyuce.mmocore.MMOCore;
import net.Indyuce.mmocore.api.event.PlayerLevelChangeEvent;
import net.Indyuce.mmocore.api.event.PlayerLevelChangeEvent.Reason;
import net.Indyuce.mmocore.experience.Profession;
import net.tfminecraft.rpcharacters.Cache;
import net.tfminecraft.rpcharacters.objects.PlayerData;

class ProfessionIntegrationsTest extends ProfessionRuntimeFixture {
    final Map<Player,net.Indyuce.mmocore.api.player.PlayerData> mmoPlayers=new HashMap<>();final Map<String,Profession> mmoProfessions=new HashMap<>();MockedStatic<net.Indyuce.mmocore.api.player.PlayerData> mmoBoundary;
    @BeforeEach void setupMmo() throws Exception {MMOCore.plugin=mock(MMOCore.class,RETURNS_DEEP_STUBS);var managerField=MMOCore.class.getField("professionManager");managerField.setAccessible(true);managerField.set(MMOCore.plugin,mock(net.Indyuce.mmocore.manager.profession.ProfessionManager.class));mmoBoundary=boundary(net.Indyuce.mmocore.api.player.PlayerData.class);mmoBoundary.when(()->net.Indyuce.mmocore.api.player.PlayerData.get(any(Player.class))).thenAnswer(call->mmoPlayers.get(call.getArgument(0)));when(MMOCore.plugin.professionManager.get(anyString())).thenAnswer(call->mmoProfessions.get(call.getArgument(0)));}
    Profession mmoProfession(String id){var profession=mock(Profession.class);when(profession.getId()).thenReturn(id);mmoProfessions.put(id,profession);return profession;}
    net.Indyuce.mmocore.api.player.PlayerData levels(Player player,Profession profession,int level){var mmo=mmoPlayers.computeIfAbsent(player,key->mock(net.Indyuce.mmocore.api.player.PlayerData.class,RETURNS_DEEP_STUBS));when(mmo.getCollectionSkills().getLevel(profession)).thenReturn(level);return mmo;}
    PlayerLevelChangeEvent levelEvent(Profession profession,int oldLevel,int newLevel,Reason reason){var event=mock(PlayerLevelChangeEvent.class);when(event.getPlayer()).thenReturn(player);when(event.getReason()).thenReturn(reason);when(event.getProfession()).thenReturn(profession);when(event.getOldLevel()).thenReturn(oldLevel);when(event.getNewLevel()).thenReturn(newLevel);return event;}

    @Test void bootstrapIgnoresNullUnloadedAndAlreadyInitializedAccounts(){ProfessionPointService.bootstrapLifetimeFromMmoCore(null);loaded.clear();ProfessionPointService.bootstrapLifetimeFromMmoCore(player);loaded.put(player,data);data.setProfessionPointsInitialized(true);ProfessionPointService.bootstrapLifetimeFromMmoCore(player);verifyNoInteractions(manager);assertTrue(mmoPlayers.isEmpty());}
    @Test void bootstrapUsesLevelMinusOneWithoutReducingExistingAwardsAndPersistsOnce(){Profession smith=mmoProfession("smith"),mining=mmoProfession("mining"),fishing=mmoProfession("fishing");profession("mining");profession("fishing");profession("missing");levels(player,smith,8);levels(player,mining,2);levels(player,fishing,0);data.setAccountProfessionPoints("mining",10);ProfessionPointService.bootstrapLifetimeFromMmoCore(player);assertEquals(7,data.getAccountProfessionPoints("smith"));assertEquals(10,data.getAccountProfessionPoints("mining"));assertEquals(0,data.getAccountProfessionPoints("fishing"));assertTrue(data.isProfessionPointsInitialized());verify(manager).savePlayer(player);ProfessionPointService.bootstrapLifetimeFromMmoCore(player);verify(manager,times(1)).savePlayer(player);}
    @Test void bootstrapBeforeMmoPlayerDataLoadsRemainsRetryable(){var profession=mmoProfession("smith");assertDoesNotThrow(()->ProfessionPointService.bootstrapLifetimeFromMmoCore(player));assertFalse(data.isProfessionPointsInitialized());verifyNoInteractions(manager);levels(player,profession,6);ProfessionPointService.bootstrapLifetimeFromMmoCore(player);assertEquals(5,data.getAccountProfessionPoints("smith"));assertTrue(data.isProfessionPointsInitialized());}
    @Test void nonLevelUpEventsUnknownProfessionsAndNonpositiveGainsDoNotAwardPoints(){var profession=mmoProfession("smith");ProfessionPointService.onProfessionLevelUp(levelEvent(profession,1,2,Reason.COMMAND));ProfessionPointService.onProfessionLevelUp(levelEvent(null,1,2,Reason.LEVEL_UP));ProfessionPointService.onProfessionLevelUp(levelEvent(mmoProfession("unknown"),1,2,Reason.LEVEL_UP));ProfessionPointService.onProfessionLevelUp(levelEvent(profession,2,2,Reason.LEVEL_UP));ProfessionPointService.onProfessionLevelUp(levelEvent(profession,2,1,Reason.LEVEL_UP));assertEquals(0,data.getAccountProfessionPoints("smith"));verifyNoInteractions(manager);assertEquals("",text(player));}
    @Test void levelUpAwardsEveryGainedLevelWithSingularAndPluralMessages(){var profession=mmoProfession("smith");ProfessionPointService.onProfessionLevelUp(levelEvent(profession,1,2,Reason.LEVEL_UP));assertEquals(1,data.getAccountProfessionPoints("smith"));assertTrue(text(player).contains("1 smith point!"));ProfessionPointService.onProfessionLevelUp(levelEvent(profession,2,5,Reason.LEVEL_UP));assertEquals(4,data.getAccountProfessionPoints("smith"));assertTrue(text(player).contains("3 smith points!"));verify(manager,times(2)).savePlayer(player);}
    @Test void leaderboardRejectsUnknownProfessionsAndSkipsMissingMmoDefinitions(){ProfessionTopService.showTop(player,"unknown");assertTrue(text(player).contains("Not a valid profession"));levels(player,mmoProfession("other"),2);ProfessionTopService.showTop(player,"smith");assertTrue(text(player).contains("SMITH"));}
    @Test void leaderboardSortsDescendingAndLimitsResultsToEleven(){var profession=mmoProfession("smith");levels(player,profession,1);for(int i=0;i<13;i++){PlayerMock other=server.addPlayer("Rank"+i);levels(other,profession,100-i);}ProfessionTopService.showTop(player,"smith");String output=text(player);assertTrue(output.indexOf("Rank0 ")<output.indexOf("Rank1 "));assertTrue(output.contains("Rank10 "));assertFalse(output.contains("Rank11 "));assertFalse(output.contains("Smith ("));assertEquals(12,output.lines().count());}
    @Test void leaderboardHeadersDoNotDependOnServerLocale(){profession("mining");var profession=mmoProfession("mining");levels(player,profession,3);Locale.setDefault(Locale.forLanguageTag("tr-TR"));ProfessionTopService.showTop(player,"mining");assertTrue(text(player).contains("MINING"));}
    @Test void leaderboardSkipsPlayersWhoseMmoDataIsNotReady(){var profession=mmoProfession("smith");levels(player,profession,3);server.addPlayer("StillLoading");assertDoesNotThrow(()->ProfessionTopService.showTop(player,"smith"));String output=text(player);assertTrue(output.contains("Smith"));assertFalse(output.contains("StillLoading"));}

    @Test void missingLuckPermsAndInvalidTargetsLeavePermissionsUntouched(){ProfessionIntegrator.apply(null,character);ProfessionIntegrator.apply(player,null);ProfessionIntegrator.remove(null,character);ProfessionIntegrator.remove(player,null);ProfessionIntegrator.applyUpgrade(null,upgrade("permission","craft.smith"));ProfessionIntegrator.applyUpgrade(player,null);ProfessionIntegrator.removeUpgrade(null,upgrades.getFirst());ProfessionIntegrator.removeUpgrade(player,null);var irrelevant=upgrade("add_stats","weapons.attack_damage.1");ProfessionIntegrator.applyUpgrade(player,irrelevant);ProfessionIntegrator.removeUpgrade(player,irrelevant);ProfessionIntegrator.givePermission(player,"craft.smith");ProfessionIntegrator.removePermission(player,"craft.smith");}
    @Test void professionPermissionsUseTheirServerContextAndPersistChanges(){try(var luck=new LuckBoundary()){var permission=upgrade("permission","craft.smith","craft.forge");upgrade("add_stats","weapons.attack_damage.1");character.addProfessionUpgrade("deleted-upgrade");ProfessionIntegrator.apply(player,character);assertEquals(List.of("craft.smith","craft.forge"),luck.added);assertTrue(luck.contexts.stream().allMatch(c->c.equals("server=realm")));player.addAttachment(plugin,"craft.smith",true);player.addAttachment(plugin,"craft.forge",true);ProfessionIntegrator.remove(player,character);assertEquals(List.of("craft.smith","craft.forge"),luck.removed);ProfessionIntegrator.applyUpgrade(player,permission);ProfessionIntegrator.removeUpgrade(player,permission);verify(luck.api.getUserManager(),times(8)).saveUser(luck.user);}}
    @Test void revocationRemovesStoredProfessionNodesEvenWhenBukkitCurrentlyDeniesThem(){try(var luck=new LuckBoundary()){ProfessionIntegrator.givePermission(player,"craft.smith");assertFalse(player.hasPermission("craft.smith"));ProfessionIntegrator.removePermission(player,"craft.smith");assertEquals(List.of("craft.smith"),luck.removed,"An ineffective contextual grant must still be removed when its character deactivates");}}

    final class LuckBoundary implements AutoCloseable {
        final LuckPerms api=mock(LuckPerms.class,RETURNS_DEEP_STUBS);final User user=mock(User.class);final NodeMap nodeMap=mock(NodeMap.class);final List<String> added=new ArrayList<>(),removed=new ArrayList<>(),contexts=new ArrayList<>();final MockedStatic<Node> nodes=mockStatic(Node.class);
        LuckBoundary(){Cache.professionPermContext="realm";when(api.getPlayerAdapter(Player.class).getUser(player)).thenReturn(user);when(user.data()).thenReturn(nodeMap);server.getServicesManager().register(LuckPerms.class,api,plugin,ServicePriority.Normal);nodes.when(()->Node.builder(anyString())).thenAnswer(call->{String permission=call.getArgument(0);var builder=mock(PermissionNode.Builder.class,RETURNS_SELF);var node=mock(PermissionNode.class);when(node.getKey()).thenReturn(permission);when(builder.withContext(anyString(),anyString())).thenAnswer(context->{contexts.add(context.getArgument(0)+"="+context.getArgument(1));return builder;});when(builder.build()).thenReturn(node);return builder;});when(nodeMap.add(any(Node.class))).thenAnswer(call->{added.add(((Node)call.getArgument(0)).getKey());return net.luckperms.api.model.data.DataMutateResult.SUCCESS;});when(nodeMap.remove(any(Node.class))).thenAnswer(call->{removed.add(((Node)call.getArgument(0)).getKey());return net.luckperms.api.model.data.DataMutateResult.SUCCESS;});}
        public void close(){nodes.close();server.getServicesManager().unregisterAll(plugin);}
    }
}
