package net.tfminecraft.rpcharacters.injuries;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.nio.file.*;
import java.util.*;
import java.util.logging.Logger;
import org.bukkit.*;
import org.bukkit.entity.*;
import org.bukkit.event.Event;
import org.bukkit.event.entity.PlayerDeathEvent;
import org.bukkit.event.inventory.*;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.inventory.*;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.PluginManager;
import org.bukkit.scheduler.*;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.*;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.database.Database;
import net.tfminecraft.rpcharacters.enums.Status;
import net.tfminecraft.rpcharacters.lifecycle.CharacterLifecycle;
import net.tfminecraft.rpcharacters.loaders.*;
import net.tfminecraft.rpcharacters.managers.PlayerManager;
import net.tfminecraft.rpcharacters.mmocore.*;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.objects.races.Race;
import net.tfminecraft.rpcharacters.objects.trait.Trait;
import net.tfminecraft.rpcharacters.permadeath.PermadeathService;
import net.tfminecraft.rpcharacters.professions.ProfessionIntegrator;
import net.tfminecraft.rpcharacters.utils.Integrator;
import net.tfminecraft.tlibs.TLibs;
import net.tfminecraft.tlibs.objects.api.ItemAPI;

public class RpInjureServiceTest {
    @TempDir Path folder;Fixture f;RpInjureListener listener;
    @BeforeEach void setup() throws Exception {f=new Fixture(folder);listener=new RpInjureListener();}
    @AfterEach void cleanup() throws Exception {if(f!=null)f.close();else MockBukkit.unmock();}
    void begin(){assertTrue(RpInjureService.begin(f.attacker,f.target));}
    void request(){begin();RpInjureService.chooseInjury(f.attacker,f.healing.getId());f.runImmediate();}
    void noSession(){assertNull(RpInjureService.getInvolving(f.attacker.getUniqueId()));assertNull(RpInjureService.getInvolving(f.target.getUniqueId()));}

    @Test void nullSelfAndPermissionFailuresDoNotCreateASession(){assertFalse(RpInjureService.begin(null,f.target));assertFalse(RpInjureService.begin(f.attacker,null));assertFalse(RpInjureService.begin(f.attacker,f.attacker));assertTrue(f.text(f.attacker).contains("yourself"));f.attacker.addAttachment(f.plugin,"rpchar.injure",false);assertFalse(RpInjureService.begin(f.attacker,f.target));assertTrue(f.text(f.attacker).contains("cannot injure anyone"));assertNull(RpInjureService.getByAttacker(null));assertNull(RpInjureService.getByTarget(null));noSession();}
    @Test void bothPlayersNeedLoadedLivingActiveCharacters(){f.loaded.remove(f.attacker);assertFalse(RpInjureService.begin(f.attacker,f.target));f.loaded.put(f.attacker,new PlayerData(f.attacker));assertFalse(RpInjureService.begin(f.attacker,f.target));f.loaded.put(f.attacker,f.attackerData);f.attackerCharacter.setStatus(Status.DEAD);assertFalse(RpInjureService.begin(f.attacker,f.target));f.attackerCharacter.setStatus(Status.ALIVE);f.loaded.remove(f.target);assertFalse(RpInjureService.begin(f.attacker,f.target));f.loaded.put(f.target,new PlayerData(f.target));assertFalse(RpInjureService.begin(f.attacker,f.target));f.loaded.put(f.target,f.targetData);f.targetCharacter.setStatus(Status.DEAD);assertFalse(RpInjureService.begin(f.attacker,f.target));noSession();}
    @Test void worldAndWholeOrFractionalRangeAreValidated(){f.target.teleport(new Location(f.server.addSimpleWorld("other"),0,64,0));assertFalse(RpInjureService.begin(f.attacker,f.target));assertTrue(f.text(f.attacker).contains("same world"));f.target.teleport(new Location(f.world,100,64,0));Cache.rpInjureRange=3;assertFalse(RpInjureService.begin(f.attacker,f.target));assertTrue(f.text(f.attacker).contains("within 3 blocks"));Cache.rpInjureRange=3.5;assertFalse(RpInjureService.begin(f.attacker,f.target));assertTrue(f.text(f.attacker).contains("within 3.5 blocks"));}
    @Test void requestsReserveBothPlayersInEitherRole(){begin();var session=RpInjureService.getByAttacker(f.attacker.getUniqueId());assertSame(session,RpInjureService.getByTarget(f.target.getUniqueId()));assertFalse(RpInjureService.begin(f.attacker,f.target));assertTrue(f.text(f.attacker).contains("already have"));assertFalse(RpInjureService.begin(f.target,f.attacker));assertTrue(f.text(f.target).contains("already have"));var other=f.player("Other",2);assertFalse(RpInjureService.begin(other,f.target));assertTrue(f.text(other).contains("already has"));}
    @Test void exhaustedInjuriesPreventOpeningThePicker(){f.targetCharacter.addTrait(f.healing);f.targetCharacter.addTrait(f.permanent);assertFalse(RpInjureService.begin(f.attacker,f.target));assertTrue(f.text(f.attacker).contains("no injuries left"));noSession();}
    @Test void pickerModelsOwnedHiddenAndAvailableInjuriesWithRealMetadata() throws Exception {f.progression();f.targetCharacter.addTrait(f.permanent);Trait extra=f.trait("burn","injury",true,Material.BLAZE_POWDER);f.trait("wise","background",false,null);assertFalse(RpInjureService.listPickerInjuries(f.targetCharacter).contains(f.healing));assertTrue(RpInjureService.isOwned(f.targetCharacter,f.permanent));assertFalse(RpInjureService.isOwned(f.targetCharacter,null));assertFalse(RpInjureService.isAvailable(null,f.healing));assertFalse(RpInjureService.isAvailable(f.targetCharacter,null));assertFalse(RpInjureService.isAvailable(f.targetCharacter,f.permanent));assertFalse(RpInjureService.isAvailable(f.targetCharacter,f.healing));assertTrue(RpInjureService.listPickerInjuries(null).contains(f.healing));begin();var inv=f.attacker.getOpenInventory().getTopInventory();var holder=(RpInjureGui.Holder)inv.getHolder();assertSame(inv,holder.getInventory());assertSame(f.attacker,holder.getOwner());assertEquals(RpInjureGui.Kind.PICKER,holder.getKind());assertEquals(Material.GRAY_DYE,inv.getItem(11).getType());assertNull(RpInjureGui.readTraitId(inv.getItem(11)));assertTrue(inv.getItem(11).getItemMeta().getLore().stream().anyMatch(s->s.contains("already have")));assertEquals(Material.BLAZE_POWDER,inv.getItem(10).getType());assertEquals(extra.getId(),RpInjureGui.readTraitId(inv.getItem(10)));assertEquals(Material.GRAY_STAINED_GLASS_PANE,inv.getItem(0).getType());}
    @Test void pickerDoesNotHideTheOnlyAvailableInjuryBehindSevenOwnedEntries(){TraitLoader.oList.clear();for(int i=0;i<7;i++)f.targetCharacter.addTrait(f.trait("owned"+i,"injury",false,null));Trait available=f.trait("available","injury",false,null);begin();var inv=f.attacker.getOpenInventory().getTopInventory();assertTrue(Arrays.stream(inv.getContents()).anyMatch(item->available.getId().equals(RpInjureGui.readTraitId(item))),"The only available injury must be reachable from the picker");}
    @Test void noSessionAndInvalidOrAlreadyOwnedChoicesDoNothing(){RpInjureService.chooseInjury(f.attacker,"missing");RpInjureService.accept(f.target);RpInjureService.decline(f.target);RpInjureService.cancelFromClose(f.target);RpInjureService.cancelInvolving(f.target,null);begin();RpInjureService.chooseInjury(f.attacker,"missing");assertTrue(f.text(f.attacker).contains("cannot apply"));f.targetCharacter.addTrait(f.healing);RpInjureService.chooseInjury(f.attacker,f.healing.getId());assertEquals(RpInjureService.RpInjureSession.Phase.PICKING,RpInjureService.getByAttacker(f.attacker.getUniqueId()).phase);RpInjureService.accept(f.target);assertEquals(List.of(f.healing),f.targetCharacter.getTraits());}
    @Test void choosingAfterTheTargetLeavesOrMovesCancelsTheRequest(){begin();f.target.disconnect();RpInjureService.chooseInjury(f.attacker,f.healing.getId());assertTrue(f.text(f.attacker).contains("no longer online"));noSession();}
    @Test void selectingAfterPermissionOrRangeChangesCancelsTheRequest(){begin();f.target.teleport(new Location(f.world,100,64,0));RpInjureService.chooseInjury(f.attacker,f.healing.getId());assertTrue(f.text(f.attacker).contains("within"));noSession();}
    @Test void clickingPickerThenAcceptAddsExactlyOneTraitAndPublishesItsEvent(){begin();var picking=f.click(f.attacker,10);listener.onClick(picking);assertTrue(picking.isCancelled());assertEquals("accept",RpInjureGui.readAction(f.target.getOpenInventory().getTopInventory().getItem(11)));assertEquals("decline",RpInjureGui.readAction(f.target.getOpenInventory().getTopInventory().getItem(15)));assertTrue(f.text(f.attacker).contains("Waiting for"));assertTrue(f.text(f.target).contains("wants to injure"));RpInjureService.chooseInjury(f.attacker,f.permanent.getId());RpInjureService.cancelFromClose(f.attacker);assertNotNull(RpInjureService.getInvolving(f.target.getUniqueId()));f.runImmediate();RpInjureService.cancelFromClose(f.attacker);var accept=f.click(f.target,11);listener.onClick(accept);assertTrue(accept.isCancelled());assertEquals(List.of(f.healing),f.targetCharacter.getTraits());assertTrue(f.text(f.attacker).contains("Applied wound"));var event=(CharacterInjuredEvent)f.events.stream().filter(CharacterInjuredEvent.class::isInstance).findFirst().orElseThrow();assertSame(f.target,event.getTarget());assertSame(f.attacker,event.getAttacker());assertSame(f.targetCharacter,event.getCharacter());assertEquals(f.healing.getId(),event.getTraitId());assertSame(CharacterInjuredEvent.getHandlerList(),event.getHandlers());verify(f.delayed.getFirst().task()).cancel();noSession();}
    @Test void permanentPreviewHasItsIconAndPermanentDescription(){begin();RpInjureService.chooseInjury(f.attacker,f.permanent.getId());var item=f.target.getOpenInventory().getTopInventory().getItem(13);assertEquals(Material.BONE,item.getType());assertTrue(item.getItemMeta().getLore().stream().anyMatch(s->s.contains("Permanent injury")));assertTrue(item.getItemMeta().getLore().stream().anyMatch(s->s.contains("description")));}
    @Test void targetCharacterSwitchInvalidatesTheOriginalConsent(){request();RPCharacter replacement=f.character(f.target,"Replacement",false);f.targetData.addCharacter(replacement);f.targetData.setActiveCharacter(replacement);RpInjureService.accept(f.target);assertTrue(replacement.getTraits().isEmpty(),"Consent was requested for the previous character");assertTrue(f.targetCharacter.getTraits().isEmpty());noSession();}
    @Test void attackerCharacterSwitchInvalidatesTheOriginalRequest(){request();RPCharacter replacement=f.character(f.attacker,"Replacement",false);f.attackerData.addCharacter(replacement);f.attackerData.setActiveCharacter(replacement);RpInjureService.accept(f.target);assertTrue(f.targetCharacter.getTraits().isEmpty(),"An injury request belongs to the initiating character");noSession();}
    @Test void acceptingAfterAttackerLeavesCancelsWithoutApplyingAnInjury(){request();f.attacker.disconnect();RpInjureService.accept(f.target);assertTrue(f.text(f.target).contains("no longer online"));assertTrue(f.targetCharacter.getTraits().isEmpty());noSession();}
    @Test void acceptingAfterPlayersMoveTooFarApartNotifiesBoth(){request();f.target.teleport(new Location(f.world,100,64,0));RpInjureService.accept(f.target);assertTrue(f.text(f.attacker).contains("too far apart now"));assertTrue(f.text(f.target).contains("too far apart now"));assertTrue(f.targetCharacter.getTraits().isEmpty());noSession();}
    @Test void acceptingRemovedOrNewlyOwnedInjuriesRejectsTheStaleChoice(){request();TraitLoader.oList.remove(f.healing);RpInjureService.accept(f.target);assertTrue(f.text(f.target).contains("can no longer be applied"));assertTrue(f.targetCharacter.getTraits().isEmpty());noSession();TraitLoader.oList.add(0,f.healing);request();f.targetCharacter.addTrait(f.healing);RpInjureService.accept(f.target);assertEquals(List.of(f.healing),f.targetCharacter.getTraits());noSession();}
    @Test void declineAndTargetClosingTheMenuPreserveTraits(){request();listener.onClick(f.click(f.target,15));assertTrue(f.text(f.attacker).contains("declined"));assertTrue(f.text(f.target).contains("declined"));noSession();request();listener.onClose(new InventoryCloseEvent(f.target.getOpenInventory()));noSession();assertTrue(f.targetCharacter.getTraits().isEmpty());}
    @Test void decliningWhenTheAttackerIsOfflineStillFinishes(){request();f.attacker.disconnect();RpInjureService.decline(f.target);assertTrue(f.text(f.target).contains("declined"));noSession();}
    @Test void closeQuitAndDeathCancelAtBothPhases(){begin();RpInjureService.cancelFromClose(f.target);assertNotNull(RpInjureService.getInvolving(f.target.getUniqueId()));listener.onClose(new InventoryCloseEvent(f.attacker.getOpenInventory()));noSession();request();listener.onQuit(new PlayerQuitEvent(f.attacker,"left"));assertTrue(f.text(f.target).contains("cancelled"));noSession();request();var death=mock(PlayerDeathEvent.class);when(death.getEntity()).thenReturn(f.target);listener.onDeath(death);noSession();}
    @Test void cancellationWithAReasonPreservesAnUnrelatedInventory(){request();var unrelated=Bukkit.createInventory(null,9);f.target.openInventory(unrelated);RpInjureService.cancelInvolving(f.attacker,"Changed plans");assertTrue(f.text(f.attacker).contains("Changed plans"));assertSame(unrelated,f.target.getOpenInventory().getTopInventory());noSession();}
    @Test void timeoutNotifiesBothPlayersAndOldCallbacksDoNotCancelNewRequests(){request();var old=f.delayed.getFirst();assertEquals(Cache.rpInjureTimeoutSeconds*20L,old.delay());old.run().run();assertTrue(f.text(f.attacker).contains("timed out"));assertTrue(f.text(f.target).contains("timed out"));noSession();begin();old.run().run();assertNotNull(RpInjureService.getByAttacker(f.attacker.getUniqueId()));}
    @Test void timeoutHandlesBothDisconnectedPlayers(){request();f.attacker.disconnect();f.target.disconnect();f.delayed.getFirst().run().run();noSession();}
    @Test void listenerIgnoresUnrelatedBottomOutsideAndUnknownButtons(){var ordinary=f.click(f.attacker,0);listener.onClick(ordinary);assertFalse(ordinary.isCancelled());listener.onClose(new InventoryCloseEvent(f.attacker.getOpenInventory()));begin();var bottom=f.click(f.attacker,30);listener.onClick(bottom);assertTrue(bottom.isCancelled());var outside=f.click(f.attacker,-999);listener.onClick(outside);assertTrue(outside.isCancelled());listener.onClick(f.click(f.attacker,0));assertEquals(RpInjureService.RpInjureSession.Phase.PICKING,RpInjureService.getByAttacker(f.attacker.getUniqueId()).phase);assertNull(RpInjureGui.readTraitId(null));assertNull(RpInjureGui.readTraitId(new ItemStack(Material.STONE)));assertNull(RpInjureGui.readAction(null));assertNull(RpInjureGui.readAction(new ItemStack(Material.STONE)));RpInjureService.chooseInjury(f.attacker,f.healing.getId());listener.onClick(f.click(f.target,0));assertNotNull(RpInjureService.getByTarget(f.target.getUniqueId()));}
    @Test void listenerRejectsForeignOwnersAndNonPlayerViews(){begin();var own=f.attacker.getOpenInventory().getTopInventory();f.target.openInventory(own);var stolen=f.click(f.target,10);listener.onClick(stolen);assertTrue(stolen.isCancelled());assertEquals(RpInjureService.RpInjureSession.Phase.PICKING,RpInjureService.getByAttacker(f.attacker.getUniqueId()).phase);var view=mock(InventoryView.class);when(view.getTopInventory()).thenReturn(own);when(view.getPlayer()).thenReturn(mock(HumanEntity.class));var click=new InventoryClickEvent(view,InventoryType.SlotType.CONTAINER,10,ClickType.LEFT,InventoryAction.PICKUP_ALL);listener.onClick(click);assertTrue(click.isCancelled());listener.onClose(new InventoryCloseEvent(view));}

    @Test void paginationMakesEveryAvailableInjurySelectableAndClampsNavigation() {
        TraitLoader.oList.clear();List<Trait> all=new ArrayList<>();for(int i=0;i<16;i++)all.add(f.trait("injury"+i,"injury",false,null));begin();Set<String> seen=new LinkedHashSet<>();
        for(int page=0;page<3;page++){var inv=f.attacker.getOpenInventory().getTopInventory();for(var item:inv.getContents()){String id=RpInjureGui.readTraitId(item);if(id!=null)seen.add(id);}assertEquals(page==0?null:"previous",RpInjureGui.readAction(inv.getItem(21)));assertEquals(page==2?null:"next",RpInjureGui.readAction(inv.getItem(25)));if(page<2){var click=f.click(f.attacker,25);listener.onClick(click);assertTrue(click.isCancelled());f.runImmediate();}}
        assertEquals(new LinkedHashSet<>(all.stream().map(Trait::getId).toList()),seen);listener.onClick(f.click(f.attacker,21));f.runImmediate();assertEquals("injury7",RpInjureGui.readTraitId(f.attacker.getOpenInventory().getTopInventory().getItem(10)));RpInjureService.changePickerPage(f.attacker,Integer.MAX_VALUE);f.runImmediate();assertEquals("injury14",RpInjureGui.readTraitId(f.attacker.getOpenInventory().getTopInventory().getItem(10)));RpInjureService.changePickerPage(f.attacker,Integer.MIN_VALUE);f.runImmediate();assertEquals("injury0",RpInjureGui.readTraitId(f.attacker.getOpenInventory().getTopInventory().getItem(10)));listener.onClick(f.click(f.attacker,25));f.runImmediate();listener.onClick(f.click(f.attacker,10));f.runImmediate();listener.onClick(f.click(f.target,11));assertEquals(List.of(all.get(7)),f.targetCharacter.getTraits());noSession();
    }
    @Test void pageNavigationCannotCancelItsOwnPickerCloseEvent(){for(int i=0;i<9;i++)f.trait("extra"+i,"injury",false,null);begin();var oldView=f.attacker.getOpenInventory();RpInjureService.changePickerPage(f.attacker,1);listener.onClose(new InventoryCloseEvent(oldView));assertNotNull(RpInjureService.getByAttacker(f.attacker.getUniqueId()));f.runImmediate();listener.onClose(new InventoryCloseEvent(f.attacker.getOpenInventory()));noSession();}
    @Test void pageRequestsWithoutASessionOrDuringConsentDoNothing(){RpInjureService.changePickerPage(f.attacker,1);noSession();request();var view=f.target.getOpenInventory();RpInjureService.changePickerPage(f.attacker,1);assertSame(view,f.target.getOpenInventory());assertEquals(RpInjureService.RpInjureSession.Phase.AWAITING_ACCEPT,RpInjureService.getByAttacker(f.attacker.getUniqueId()).phase);}
    @Test void pageNavigationRejectsDisconnectedTargets(){begin();f.target.disconnect();RpInjureService.changePickerPage(f.attacker,1);assertTrue(f.text(f.attacker).contains("no longer online"));noSession();}
    @Test void pageNavigationRejectsChangedPermissionOrRange(){begin();f.attacker.addAttachment(f.plugin,"rpchar.injure",false);RpInjureService.changePickerPage(f.attacker,1);assertTrue(f.text(f.attacker).contains("cannot injure anyone"));noSession();f.attacker.addAttachment(f.plugin,"rpchar.injure",true);begin();f.target.teleport(new Location(f.world,100,64,0));RpInjureService.changePickerPage(f.attacker,1);assertTrue(f.text(f.attacker).contains("within"));noSession();}
    @Test void targetCharacterSwitchInvalidatesThePickerBeforeChoosing(){begin();var next=f.character(f.target,"Next",false);f.targetData.addCharacter(next);f.targetData.setActiveCharacter(next);RpInjureService.chooseInjury(f.attacker,f.healing.getId());assertTrue(f.text(f.attacker).contains("character changed"));assertTrue(next.getTraits().isEmpty());noSession();}
    @Test void attackerCharacterSwitchInvalidatesPageNavigation(){begin();var next=f.character(f.attacker,"Next",false);f.attackerData.addCharacter(next);f.attackerData.setActiveCharacter(next);RpInjureService.changePickerPage(f.attacker,1);assertTrue(f.text(f.attacker).contains("character changed"));assertTrue(f.targetCharacter.getTraits().isEmpty());noSession();}
    @Test void emptyPickerAndRemovedEntriesKeepPaginationWithinBounds(){TraitLoader.oList.clear();RpInjureGui.openPicker(f.attacker,f.target,f.targetCharacter);assertTrue(Arrays.stream(f.attacker.getOpenInventory().getTopInventory().getContents()).allMatch(item->item.getType()==Material.GRAY_STAINED_GLASS_PANE));TraitLoader.oList.add(f.healing);for(int i=0;i<9;i++)f.trait("extra"+i,"injury",false,null);begin();RpInjureService.changePickerPage(f.attacker,1);f.runImmediate();TraitLoader.oList.clear();TraitLoader.oList.add(f.healing);RpInjureService.changePickerPage(f.attacker,1);f.runImmediate();assertEquals("wound",RpInjureGui.readTraitId(f.attacker.getOpenInventory().getTopInventory().getItem(10)));}

    /** Real Bukkit inventory and character state; mocks stop at external integration boundaries. */
    private static final class InventoryPlayer extends PlayerMock {
        private final Inventory defaultTop=Bukkit.createInventory(null,9);
        InventoryPlayer(ServerMock server,String name){super(server,name);}
        @Override public InventoryView getOpenInventory(){var view=super.getOpenInventory();return view.getTopInventory()!=null||defaultTop==null?view:new org.mockbukkit.mockbukkit.inventory.PlayerInventoryViewMock(this,defaultTop);}
    }

    public static final class Fixture implements AutoCloseable {
        public final Path folder;public final ServerMock server;public final RuntimeTestState state;public final RPCharacters plugin;public final Logger logger;public final World world;public final PlayerMock attacker,target;public final RPCharacter attackerCharacter,targetCharacter;public final PlayerData attackerData,targetData;public final PlayerManager manager;public final Trait healing,permanent;public final Race race;
        public final Map<Player,PlayerData> loaded=new HashMap<>();public final List<AutoCloseable> boundaries=new ArrayList<>();public final List<Event> events=new ArrayList<>();public final Deque<Runnable> immediate=new ArrayDeque<>();public final List<Scheduled> delayed=new ArrayList<>();public final List<Scheduled> timers=new ArrayList<>();public final MockedStatic<Bukkit> bukkit;public final MockedConstruction<Integrator> integrations;public final ItemAPI items;public java.util.function.Consumer<Player> integrationCallback=player->{};
        public record Scheduled(Runnable run,long delay,BukkitTask task){}
        public Fixture(Path directory) throws Exception {
            folder=directory;server=MockBukkit.mock();state=new RuntimeTestState(RPCharacters.class,RpInjureService.class,TraitLoader.class,InjuryProgressionLoader.class,ProstheticLoader.class,FuelTemplateLoader.class,InjuryPoolLoader.class,PermadeathService.class);try { Cache.attributes=new ArrayList<>();Cache.professions=new ArrayList<>();Cache.backgroundTraitTypes=new ArrayList<>();Cache.rpInjureRange=5;Cache.rpInjureTimeoutSeconds=30;TraitLoader.oList=new ArrayList<>();plugin=mock(RPCharacters.class);logger=mock(Logger.class);when(plugin.getName()).thenReturn("RPCharacters");when(plugin.namespace()).thenReturn("rpcharacters");when(plugin.getLogger()).thenReturn(logger);when(plugin.getDataFolder()).thenReturn(folder.toFile());when(plugin.getServer()).thenReturn(server);when(plugin.isEnabled()).thenReturn(true);RPCharacters.plugin=plugin;world=server.addSimpleWorld("injuries");
            manager=mock(PlayerManager.class);var root=boundary(RPCharacters.class);root.when(RPCharacters::getPlayerManager).thenReturn(manager);var players=boundary(PlayerManager.class);players.when(()->PlayerManager.get(any(Player.class))).thenAnswer(call->loaded.get(call.getArgument(0)));boundary(Database.class);boundary(AttributePointService.class);boundary(ProfessionIntegrator.class);boundary(MmoCorePlayerReady.class);boundary(CharacterLifecycle.class);integrations=mockConstruction(Integrator.class,(instance,context)->doAnswer(call->{integrationCallback.accept(call.getArgument(0));return null;}).when(instance).integrate(any(Player.class),any(RPCharacter.class)));boundaries.add(integrations);
            var pm=mock(PluginManager.class);doAnswer(call->{events.add(call.getArgument(0));return null;}).when(pm).callEvent(any());var scheduler=mock(BukkitScheduler.class);when(scheduler.runTask(eq(plugin),any(Runnable.class))).thenAnswer(call->{immediate.add(call.getArgument(1));return mock(BukkitTask.class);});when(scheduler.runTaskLater(eq(plugin),any(Runnable.class),anyLong())).thenAnswer(call->{var task=mock(BukkitTask.class);delayed.add(new Scheduled(call.getArgument(1),call.getArgument(2),task));return task;});when(scheduler.runTaskTimer(eq(plugin),any(Runnable.class),anyLong(),anyLong())).thenAnswer(call->{var task=mock(BukkitTask.class);timers.add(new Scheduled(call.getArgument(1),call.getArgument(2),task));return task;});bukkit=mockStatic(Bukkit.class,CALLS_REAL_METHODS);boundaries.add(bukkit);bukkit.when(Bukkit::getScheduler).thenReturn(scheduler);bukkit.when(Bukkit::getPluginManager).thenReturn(pm);
            var raceConfig=new YamlConfiguration();raceConfig.set("name","Human");race=new Race("human",raceConfig);attacker=player("Attacker",0);target=player("Target",1);attackerData=loaded.get(attacker);targetData=loaded.get(target);attackerCharacter=attackerData.getActiveCharacter();targetCharacter=targetData.getActiveCharacter();healing=trait("wound","injury",true,null);permanent=trait("maimed","injury",false,Material.BONE);var empty=folder.resolve("empty.yml");Files.writeString(empty,"");new InjuryProgressionLoader().load(empty.toFile());new ProstheticLoader().load(empty.toFile());new FuelTemplateLoader().load(empty.toFile());new InjuryPoolLoader().load(empty.toFile());items=mock(ItemAPI.class,RETURNS_DEEP_STUBS);var tlibs=boundary(TLibs.class);tlibs.when(TLibs::getItemAPI).thenReturn(items);when(items.getChecker().checkItemWithPath(any(ItemStack.class),anyString())).thenAnswer(call->{ItemStack stack=call.getArgument(0);return stack.getType().name().equalsIgnoreCase(call.getArgument(1));});
            } catch (Exception | Error failure) { try { close(); } catch (Exception cleanup) { failure.addSuppressed(cleanup); } throw failure; }
        }
        public <T> MockedStatic<T> boundary(Class<T> type){var mock=mockStatic(type);boundaries.add(mock);return mock;}
        public PlayerMock player(String name,double x){var p=new InventoryPlayer(server,name);server.addPlayer(p);p.teleport(new Location(world,x,64,0));p.addAttachment(plugin,"rpchar.injure",true);var data=new PlayerData(p);data.addCharacter(character(p,name,true));loaded.put(p,data);return p;}
        public RPCharacter character(Player owner,String name,boolean active){return new RPCharacter(owner,UUID.randomUUID().toString(),name,active,Status.ALIVE,race,new ArrayList<>(),"HUMAN");}
        public Trait trait(String id,String key,boolean healing,Material icon){var yaml=new YamlConfiguration();yaml.set("name",id);yaml.set("description",List.of("description for "+id));yaml.set("key",key);if(healing)yaml.set("duration","1h");if(icon!=null)yaml.set("icon",icon.name());return trait(id,yaml);}
        public Trait trait(String id,YamlConfiguration yaml){var trait=new Trait(id,yaml);TraitLoader.oList.add(trait);return trait;}
        public void progression() throws Exception {var path=folder.resolve("progression.yml");Files.writeString(path,"progression:\n  wound: maimed\n");new InjuryProgressionLoader().load(path.toFile());}
        public String text(PlayerMock p){var out=new ArrayList<String>();String message;while((message=p.nextMessage())!=null)out.add(message);return ChatColor.stripColor(String.join("\n",out));}
        public InventoryClickEvent click(Player player,int slot){return new InventoryClickEvent(player.getOpenInventory(),InventoryType.SlotType.CONTAINER,slot,ClickType.LEFT,InventoryAction.PICKUP_ALL);}
        public void runImmediate(){while(!immediate.isEmpty())immediate.removeFirst().run();}
        public void close() throws Exception {try{for(int i=boundaries.size()-1;i>=0;i--)boundaries.get(i).close();state.close();}finally{MockBukkit.unmock();}}
    }
}
