package net.tfminecraft.rpcharacters.clues.discovery;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.*;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.loaders.ClueDiscoveryLoader;
import net.tfminecraft.rpcharacters.managers.*;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.speechbubble.fake.*;
import net.tfminecraft.rpcharacters.chat.smart.*;
import net.tfminecraft.rpcharacters.utils.ClueHologram;
import org.bukkit.*;
import org.junit.jupiter.api.*;
import org.mockito.MockedStatic;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;

class ClueVisualRuntimeTest {
    ServerMock server; World world; PlayerMock player; PlayerData data; RPCharacter character;RuntimeTestState state;
    ClueDiscoverySettings settings;ClueDiscoveryVisualManager visual;FakeTextDisplayPackets packets;SpawnedClueManager manager;
    List<AutoCloseable> mocks=new ArrayList<>();MockedStatic<PlayerManager> players;MockedStatic<ProtocolLibBridge> bridge;MockedStatic<ClueHologram> holograms;
    @BeforeEach void setup(){server=MockBukkit.mock();world=server.addSimpleWorld("clues");world.getChunkAt(0,0).load();player=server.addPlayer();player.teleport(new Location(world,0,65,0));state=new RuntimeTestState(ClueAdminModeService.class,RPCharacters.class);RPCharacters.plugin=mock(RPCharacters.class);when(RPCharacters.plugin.namespace()).thenReturn("rpcharacters");settings=new ClueDiscoverySettings();boundary(ClueDiscoveryLoader.class).when(ClueDiscoveryLoader::getSettings).thenReturn(settings);players=boundary(PlayerManager.class);data=new PlayerData(player);var config=new org.bukkit.configuration.file.YamlConfiguration();config.set("name","Human");character=new RPCharacter(player,UUID.randomUUID().toString(),"Scout",true,net.tfminecraft.rpcharacters.enums.Status.ALIVE,new net.tfminecraft.rpcharacters.objects.races.Race("human",config),new ArrayList<>(),null);data.getCharacters().add(character);players.when(()->PlayerManager.get(player)).thenReturn(data);
        manager=mock(SpawnedClueManager.class);boundary(SpawnedClueManager.class).when(SpawnedClueManager::get).thenReturn(manager);packets=mock(FakeTextDisplayPackets.class);bridge=boundary(ProtocolLibBridge.class);bridge.when(ProtocolLibBridge::isReady).thenReturn(true);bridge.when(ProtocolLibBridge::getPackets).thenReturn(packets);holograms=boundary(ClueHologram.class);visual=ClueDiscoveryVisualManager.get();visual.shutdown();Cache.spawnedClueLineLength=40;
    }
    <T> MockedStatic<T> boundary(Class<T> type){var m=mockStatic(type);mocks.add(m);return m;}
    @AfterEach void cleanup()throws Exception{try {if(visual!=null)visual.shutdown();} finally {for(int i=mocks.size()-1;i>=0;i--)mocks.get(i).close();if(state!=null)state.close();MockBukkit.unmock();}}
    SpawnedClue clue(){var clue=new SpawnedClue(UUID.randomUUID(),world.getName(),0,65,0,"Footprint",Long.MAX_VALUE,player.getUniqueId());clue.markDiscovered(UUID.fromString(character.getId()));return clue;}
    void nearby(SpawnedClue... clues){when(manager.getCluesNear(any(),anyDouble())).thenReturn(List.of(clues));}
    @Test void visibleCluesSpawnRefreshAndDestroyAsTheViewerMovesAway(){var clue=clue();nearby(clue);visual.refreshViewer(player);verify(packets).spawn(eq(player),anyInt(),any(),any(),contains("Footprint"),anyFloat(),eq(200));visual.refreshViewer(player);verify(packets).destroy(eq(player),anyList());nearby();visual.refreshViewer(player);verify(packets,times(2)).destroy(eq(player),anyList());visual.clearViewer(player.getUniqueId());visual.clearViewer(UUID.randomUUID());}
    @Test void removingAClueAndClearingAViewerDisposeOnlyTrackedDisplays(){var clue=clue();nearby(clue);visual.refreshViewer(player);visual.removeClue(UUID.randomUUID());verify(packets,never()).destroy(any(),anyList());visual.removeClue(clue.getId());verify(packets).destroy(eq(player),anyList());visual.refreshViewer(player);visual.clearViewer(player.getUniqueId());verify(packets,times(2)).destroy(eq(player),anyList());}
    @Test void offlineAndUnavailableBridgeSkipRenderingAndDataLossClearsOldStacks(){var clue=clue();nearby(clue);visual.refreshViewer(null);visual.tickParticles(null);bridge.when(ProtocolLibBridge::isReady).thenReturn(false);visual.refreshViewer(player);verifyNoInteractions(packets);bridge.when(ProtocolLibBridge::isReady).thenReturn(true);visual.refreshViewer(player);players.when(()->PlayerManager.get(player)).thenReturn(null);visual.refreshViewer(player);verify(packets).destroy(eq(player),anyList());visual.tickParticles(player);player.disconnect();visual.refreshViewer(player);visual.tickParticles(player);visual.clearViewer(player.getUniqueId());}
    @Test void particlesAndDisplaysRequireDiscoveryAndLoadedChunksUnlessAdmin(){var known=clue();var unknown=new SpawnedClue(UUID.randomUUID(),world.getName(),2,65,0,"Secret",Long.MAX_VALUE,player.getUniqueId());var unloaded=new SpawnedClue(UUID.randomUUID(),"absent",0,65,0,"Absent",Long.MAX_VALUE,player.getUniqueId());nearby(known,unknown,unloaded);visual.refreshViewer(player);verify(packets,times(1)).spawn(any(),anyInt(),any(),any(),anyString(),anyFloat(),anyInt());visual.tickParticles(player);holograms.verify(()->ClueHologram.spawnClueParticles(known));holograms.verify(()->ClueHologram.spawnClueParticles(unknown),never());assertFalse(ClueAdminModeService.canUse(null));assertFalse(ClueAdminModeService.setEnabled(player,true));player.setOp(true);assertTrue(ClueAdminModeService.setEnabled(player,true));assertTrue(ClueAdminModeService.isEnabled(player));assertFalse(ClueAdminModeService.isEnabled(null));players.when(()->PlayerManager.get(player)).thenReturn(null);visual.refreshViewer(player);verify(packets,times(3)).spawn(any(),anyInt(),any(),any(),anyString(),anyFloat(),anyInt());visual.tickParticles(player);holograms.verify(()->ClueHologram.spawnClueParticles(unknown));assertTrue(ClueAdminModeService.setEnabled(player,false));ClueAdminModeService.clear(null);ClueAdminModeService.clear(player);assertFalse(ClueAdminModeService.isEnabled(player));}
    @Test void legacyOrphansAreRemovedAndMissingPacketBridgeDoesNotThrowDuringCleanup(){var clue=clue();clue.getDisplayEntityIds().add(UUID.randomUUID());visual.cleanupLegacyOrphans(List.of(clue,clue()));holograms.verify(()->ClueHologram.remove(clue));nearby(clue);visual.refreshViewer(player);bridge.when(ProtocolLibBridge::isReady).thenReturn(false);bridge.when(ProtocolLibBridge::getPackets).thenReturn(null);visual.removeClue(clue.getId());visual.refreshViewer(player);visual.shutdown();verify(packets,never()).destroy(any(),anyList());}
    @Test void readabilityPreservesFullTextAndAdminContextWhileFaintCluesUsePlaceholder(){var clue=clue();assertEquals("",ClueReadabilityResolver.resolve(null,null));assertEquals("",ClueReadabilityResolver.resolveForAdmin(null));assertTrue(ClueReadabilityResolver.resolve(clue,null).contains("Footprint"));assertTrue(ClueReadabilityResolver.resolve(clue,null,true).contains("100%"));clue.setPotency(.01);settings.setReadabilityTooFaintPlaceholder("&7Faint");assertEquals("§7Faint",ClueReadabilityResolver.resolve(clue,null));settings.setReadabilityTooFaintPlaceholder("");assertEquals("",ClueReadabilityResolver.resolve(clue,null));clue.setPotency(.5);
        try(var engine=mockStatic(MuffleEngine.class)){engine.when(()->MuffleEngine.apply(anyString(),anyDouble(),any(),any(),any())).thenReturn("§7Muffled","plain","",null);assertEquals("§7Muffled",ClueReadabilityResolver.resolve(clue,UUID.randomUUID()));assertTrue(ClueReadabilityResolver.resolve(clue,null).contains("plain"));assertEquals("",ClueReadabilityResolver.resolve(clue,null));assertEquals("",ClueReadabilityResolver.resolve(clue,null));}
    }
    @Test void malformedLegacyCharacterIdsNeverRevealUndiscoveredClues(){var config=new org.bukkit.configuration.file.YamlConfiguration();config.set("name","Human");var race=new net.tfminecraft.rpcharacters.objects.races.Race("human",config);var clue=clue();nearby(clue);for(String id:Arrays.asList(null,"legacy")){data.getCharacters().clear();data.getCharacters().add(new RPCharacter(player,id,"Legacy",true,net.tfminecraft.rpcharacters.enums.Status.ALIVE,race,new ArrayList<>(),null));visual.refreshViewer(player);visual.tickParticles(player);}verifyNoInteractions(packets);holograms.verifyNoInteractions();}

}
