package net.tfminecraft.rpcharacters.managers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.util.*;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.junit.jupiter.api.*;
import org.mockito.*;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.clues.discovery.ClueDiscoverySettings;
import net.tfminecraft.rpcharacters.creation.CharacterCreation;
import net.tfminecraft.rpcharacters.database.Database;
import net.tfminecraft.rpcharacters.enums.*;
import net.tfminecraft.rpcharacters.loaders.ClueDiscoveryLoader;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.objects.races.Race;
import net.tfminecraft.rpcharacters.utils.*;

class ClueCreationRuntimeTest extends ClueRuntimeFixture {
    final ClueInputManager input=new ClueInputManager();final PlaceClueManager placement=new PlaceClueManager();MockedConstruction<InventoryManager> inventories;
    @BeforeEach void setupInput(){inventories=mockConstruction(InventoryManager.class);mocks.add(inventories);}
    AsyncPlayerChatEvent chat(String message){return new AsyncPlayerChatEvent(false,player,message,new HashSet<>());}
    void submit(String message){input.onChat(chat(message));server.getScheduler().performOneTick();}
    CharacterCreation creator(boolean editing){var cc=mock(CharacterCreation.class);when(cc.getCharacter()).thenReturn(character);when(cc.isEditing()).thenReturn(editing);CreationManager.activeCreators.put(player,cc);return cc;}
    Block target(){var original=world.getBlockAt(5,70,5);original.setType(Material.STONE);var location=original.getLocation().clone();var block=spy(original);doAnswer(call->location.clone()).when(block).getLocation();return block;}

    @Test void beginningInputClosesMenusAndExposesItsPendingCharacter(){player.openInventory(server.createInventory(null,9,"Before clue"));ClueInputManager.beginInput(player,character.getId());assertTrue(ClueInputManager.isPending(player));assertEquals(character.getId(),ClueInputManager.getPendingCharacterId(player));assertNotEquals("Before clue",player.getOpenInventory().getTitle());assertTrue(messages(player).contains("between 3 and 60"));ClueInputManager.cancel(player);assertFalse(ClueInputManager.isPending(player));assertNull(ClueInputManager.getPendingCharacterId(player));}
    @Test void ordinaryChatIsNotCaptured(){var event=chat("Ordinary chat");input.onChat(event);assertFalse(event.isCancelled());assertFalse(ClueInputManager.consumeConversationSkip(player.getUniqueId()));assertTrue(character.getPlayerClues().isEmpty());}
    @Test void submittedClueRunsOnMainThreadAndIsExcludedFromConversationOnce(){ClueInputManager.beginInput(player,character.getId());var event=chat("&aA muddy footprint");input.onChat(event);assertTrue(event.isCancelled());assertFalse(ClueInputManager.isPending(player));assertTrue(character.getPlayerClues().isEmpty());assertTrue(ClueInputManager.consumeConversationSkip(player.getUniqueId()));assertFalse(ClueInputManager.consumeConversationSkip(player.getUniqueId()));server.getScheduler().performOneTick();assertEquals(List.of("A muddy footprint"),character.getPlayerClues().stream().map(ClueFormatter::stripColor).toList());verify(manager).savePlayer(player);verify(manager).reevaluateFreeze(player);verify(inventories.constructed().getFirst()).cluesView(player,character);}
    @Test void unloadedAndRemovedCharactersReportFailureWithoutCreatingClues(){loaded.clear();ClueInputManager.beginInput(player,character.getId());submit("A muddy footprint");assertTrue(messages(player).contains("Could not find"));loaded.put(player,data);ClueInputManager.beginInput(player,"removed");submit("A muddy footprint");assertTrue(messages(player).contains("Could not find"));verifyNoInteractions(manager);assertTrue(inventories.constructed().isEmpty());}
    @Test void aCharacterLoadedBetweenResolutionAttemptsCanStillReceiveItsClue(){players.when(()->PlayerManager.get(player)).thenReturn(null,data);ClueInputManager.beginInput(player,character.getId());submit("A muddy footprint");assertEquals(1,character.getPlayerClues().size());verify(manager).savePlayer(player);}
    @Test void inputCannotModifyAnotherPlayersCharacter(){var other=server.addPlayer("Other");var foreign=character(other,"Elf");var cc=creator(false);when(cc.getCharacter()).thenReturn(foreign);ClueInputManager.beginInput(player,foreign.getId());submit("A muddy footprint");assertTrue(foreign.getPlayerClues().isEmpty());assertTrue(messages(player).contains("own characters"));verifyNoInteractions(manager);}
    @Test void invalidCluesKeepTheDraftInputOpenForRetry(){creator(false);ClueInputManager.beginInput(player,character.getId(),true);submit("x");assertTrue(ClueInputManager.isPending(player));assertTrue(messages(player).contains("between 3 and 60"));submit("A muddy footprint");assertFalse(ClueInputManager.isPending(player));assertEquals(1,character.getPlayerClues().size());verifyNoInteractions(manager);verify(inventories.constructed().getFirst()).cluesView(eq(player),eq(character),eq(CreationGuiContext.CREATION_SUMMARY),any(CharacterCreation.class));}
    @Test void overlongDuplicateAndFullClueListsStayRetryable(){ClueInputManager.beginInput(player,character.getId());submit("x".repeat(61));assertTrue(ClueInputManager.isPending(player));submit("A muddy footprint");ClueInputManager.beginInput(player,character.getId());submit("&bA MUDDY FOOTPRINT");String duplicateMessage=messages(player);assertTrue(duplicateMessage.contains("already have"),duplicateMessage+"; stored clues="+character.getPlayerClues());Cache.maxClues=1;submit("A broken twig");assertTrue(messages(player).contains("more than 1"));assertEquals(1,character.getPlayerClues().size());assertTrue(ClueInputManager.isPending(player));}
    @Test void editingAnExistingCharacterReturnsToItsEditSummary(){var cc=creator(true);ClueInputManager.beginInput(player,character.getId());submit("A muddy footprint");verify(manager).savePlayer(player);verify(manager).reevaluateFreeze(player);verify(inventories.constructed().getFirst()).cluesView(player,character,CreationGuiContext.EDIT_SUMMARY,cc);}
    @Test void quittingCancelsAnUnsubmittedRequest(){ClueInputManager.beginInput(player,character.getId(),true);input.onQuit(new PlayerQuitEvent(player,"bye"));assertFalse(ClueInputManager.isPending(player));var event=chat("A muddy footprint");input.onChat(event);assertFalse(event.isCancelled());}
    @Test void quittingAfterSubmittingCannotMutateOrReopenAnOfflineCharactersMenu(){ClueInputManager.beginInput(player,character.getId());input.onChat(chat("A muddy footprint"));player.disconnect();input.onQuit(new PlayerQuitEvent(player,"bye"));server.getScheduler().performOneTick();assertTrue(character.getPlayerClues().isEmpty());verifyNoInteractions(manager);assertTrue(inventories.constructed().isEmpty());}
    @Test void quittingRemovesAnUnconsumedConversationSkip(){ClueInputManager.beginInput(player,character.getId());input.onChat(chat("A muddy footprint"));input.onQuit(new PlayerQuitEvent(player,"bye"));assertFalse(ClueInputManager.consumeConversationSkip(player.getUniqueId()));}

    @Test void placementRejectsInvalidTextAndIgnoresUnrelatedInteractions(){assertFalse(placement.startAwaiting(player,"x"));assertTrue(messages(player).contains("at least 3"));assertFalse(placement.startAwaiting(player,"x".repeat(61)));assertTrue(messages(player).contains("cannot exceed 60"));var event=interact(Action.RIGHT_CLICK_BLOCK,target(),EquipmentSlot.HAND,null);placement.onPlayerInteract(event);assertFalse(event.isCancelled());assertTrue(placement.startAwaiting(player,"A muddy footprint"));var left=interact(Action.LEFT_CLICK_BLOCK,target(),EquipmentSlot.HAND,null);placement.onPlayerInteract(left);assertFalse(left.isCancelled());var missing=interact(Action.RIGHT_CLICK_BLOCK,null,EquipmentSlot.HAND,null);placement.onPlayerInteract(missing);assertFalse(missing.isCancelled());}
    @Test void placementLinksToTheClickedBlockAndConsumesTheRequestOnlyOnce(){try(var giver=mockStatic(ClueGiver.class)){var anchor=new Location(world,5.5,71,5.5);var block=target();var targetLocation=block.getLocation();giver.when(()->ClueGiver.getRandomValidClueLocation(any(Location.class))).thenReturn(anchor);var clue=clue();giver.when(()->ClueGiver.spawnClueWithText(eq(anchor),eq(targetLocation),eq(player),anyString(),eq(false))).thenReturn(clue);placement.startAwaiting(player,"&aA muddy footprint");var event=interact(Action.RIGHT_CLICK_BLOCK,block,EquipmentSlot.HAND,null);placement.onPlayerInteract(event);assertTrue(event.isCancelled());assertTrue(messages(player).contains("linked to that block"));var captured=ArgumentCaptor.forClass(String.class);giver.verify(()->ClueGiver.spawnClueWithText(eq(anchor),eq(new Location(world,5,70,5)),eq(player),captured.capture(),eq(false)));assertEquals(ClueFormatter.format("A muddy footprint"),captured.getValue(),"Placement strips formatting before storing the clue");var next=interact(Action.RIGHT_CLICK_BLOCK,block,EquipmentSlot.HAND,null);placement.onPlayerInteract(next);assertFalse(next.isCancelled());server.getScheduler().performTicks(601);assertFalse(messages(player).contains("timed out"));}}
    @Test void placementSearchesNearThePlayerWhenTheTargetHasNoAnchor(){try(var giver=mockStatic(ClueGiver.class)){var anchor=new Location(world,.5,70,.5);giver.when(()->ClueGiver.getRandomValidClueLocation(any(Location.class))).thenReturn(null,anchor);placement.startAwaiting(player,"A muddy footprint");placement.onPlayerInteract(interact(Action.RIGHT_CLICK_BLOCK,target(),EquipmentSlot.HAND,null));giver.verify(()->ClueGiver.getRandomValidClueLocation(player.getLocation()));giver.verify(()->ClueGiver.spawnClueWithText(eq(anchor),any(Location.class),eq(player),anyString(),eq(false)));assertTrue(messages(player).contains("Could not spawn world clue"));}}
    @Test void placementReportsWhenNeitherSearchFindsAnAnchor(){try(var giver=mockStatic(ClueGiver.class)){placement.startAwaiting(player,"A muddy footprint");placement.onPlayerInteract(interact(Action.RIGHT_CLICK_BLOCK,target(),EquipmentSlot.HAND,null));assertTrue(messages(player).contains("No valid clue anchor"));giver.verify(()->ClueGiver.spawnClueWithText(any(),any(),any(),any(),anyBoolean()),never());}}
    @Test void replacingAPlacementRestartsItsTimeoutAndQuitCancelsIt(){assertTrue(placement.startAwaiting(player,"First footprint"));server.getScheduler().performTicks(300);assertTrue(placement.startAwaiting(player,"Second footprint"));messages(player);server.getScheduler().performTicks(301);assertFalse(messages(player).contains("timed out"));server.getScheduler().performTicks(300);assertTrue(messages(player).contains("timed out"));placement.startAwaiting(player,"Third footprint");placement.onPlayerQuit(new PlayerQuitEvent(player,"bye"));messages(player);server.getScheduler().performTicks(601);assertFalse(messages(player).contains("timed out"));}
    @Test void placementTimeoutToleratesAPlayerWhoHasDisconnected(){placement.startAwaiting(player,"A muddy footprint");messages(player);player.disconnect();assertDoesNotThrow(()->server.getScheduler().performTicks(601));assertEquals("",messages(player));}
}

abstract class ClueRuntimeFixture {
    ServerMock server;World world;CluePlayer player;RPCharacters plugin;RuntimeTestState state;RPCharacter character;PlayerData data;PlayerManager manager;SpawnedClueManager spawned;ClueDiscoverySettings settings;MockedStatic<PlayerManager> players;final Map<Player,PlayerData> loaded=new HashMap<>();final List<AutoCloseable> mocks=new ArrayList<>();
    @BeforeEach void setupClueRuntime(){server=MockBukkit.mock();state=new RuntimeTestState(RPCharacters.class,ClueInputManager.class,CreationManager.class,ClueDiscoveryLoader.class);world=server.addSimpleWorld("clue-runtime");player=new CluePlayer(server,"Scout");server.addPlayer(player);player.teleport(new Location(world,.5,70,.5));plugin=mock(RPCharacters.class);when(plugin.getServer()).thenReturn(server);when(plugin.getName()).thenReturn("RPCharacters");when(plugin.namespace()).thenReturn("rpcharacters");when(plugin.isEnabled()).thenReturn(true);when(plugin.getLogger()).thenReturn(java.util.logging.Logger.getAnonymousLogger());RPCharacters.plugin=plugin;Cache.attributes=new ArrayList<>();Cache.professions=new ArrayList<>();Cache.backgroundTraitTypes=new ArrayList<>();Cache.traitClueOverrides=new HashMap<>();Cache.clueMinLength=3;Cache.clueMaxLength=60;Cache.maxClues=8;Cache.defaultCluesRequired=1;Cache.raceClueTemplate="This belongs to {a/an} {race}.";Cache.clueSpawnRadius=1;Cache.spawnedClueTimerHours=2;CreationManager.activeCreators.clear();character=character(player,"Human");data=new PlayerData(player);data.addCharacter(character);loaded.put(player,data);players=boundary(PlayerManager.class);players.when(()->PlayerManager.get(any(Player.class))).thenAnswer(call->loaded.get(call.getArgument(0)));manager=mock(PlayerManager.class);boundary(RPCharacters.class).when(RPCharacters::getPlayerManager).thenReturn(manager);boundary(Database.class);spawned=mock(SpawnedClueManager.class);boundary(SpawnedClueManager.class).when(SpawnedClueManager::get).thenReturn(spawned);settings=new ClueDiscoverySettings();boundary(ClueDiscoveryLoader.class).when(ClueDiscoveryLoader::getSettings).thenReturn(settings);}
    RPCharacter character(Player owner,String raceName){var config=new YamlConfiguration();config.set("name",raceName);return new RPCharacter(owner,UUID.randomUUID().toString(),"Scout",true,Status.ALIVE,new Race("test",config),new ArrayList<>(),"HUMAN");}
    <T> MockedStatic<T> boundary(Class<T> type){var boundary=mockStatic(type);mocks.add(boundary);return boundary;}
    String messages(PlayerMock recipient){var messages=new ArrayList<String>();String message;while((message=recipient.nextMessage())!=null)messages.add(message);return ChatColor.stripColor(String.join("\n",messages));}
    PlayerInteractEvent interact(Action action,Block block,EquipmentSlot hand,ItemStack item){var event=new PlayerInteractEvent(player,action,item,block,org.bukkit.block.BlockFace.UP,hand);event.setCancelled(false);return event;}
    SpawnedClue clue(){return new SpawnedClue(UUID.randomUUID(),world.getName(),.5,70,.5,"A muddy footprint",Long.MAX_VALUE,player.getUniqueId());}
    @AfterEach void cleanupClueRuntime() throws Exception {try{if(server!=null&&plugin!=null)server.getScheduler().cancelTasks(plugin);for(int i=mocks.size()-1;i>=0;i--)mocks.get(i).close();if(state!=null)state.close();}finally{MockBukkit.unmock();}}
    static final class CluePlayer extends PlayerMock {private Inventory defaultTop;CluePlayer(ServerMock server,String name){super(server,name);defaultTop=super.getOpenInventory().getTopInventory();}@Override public InventoryView getOpenInventory(){var view=super.getOpenInventory();return view.getTopInventory()!=null||defaultTop==null?view:new org.mockbukkit.mockbukkit.inventory.PlayerInventoryViewMock(this,defaultTop);}}
}
