package net.tfminecraft.rpcharacters.managers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;
import org.bukkit.*;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.event.block.Action;
import org.bukkit.inventory.*;
import org.bukkit.persistence.PersistentDataType;
import org.junit.jupiter.api.*;
import org.mockito.MockedStatic;
import net.tfminecraft.rpcharacters.Cache;
import net.tfminecraft.rpcharacters.clues.discovery.*;
import net.tfminecraft.rpcharacters.loaders.MagnifyingGlassLoader;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.objects.attributes.AttributeModifier;
import net.tfminecraft.rpcharacters.utils.*;

class ClueToolListenersTest extends ClueRuntimeFixture {
    @Test void clueRequirementsHandleUnloadedInactiveAndCompleteCharacters(){assertFalse(ClueGiver.hasEnoughClues(null));loaded.clear();assertFalse(ClueGiver.hasEnoughClues(player));loaded.put(player,new PlayerData(player));assertFalse(ClueGiver.hasEnoughClues(player));loaded.put(player,data);assertFalse(ClueGiver.hasEnoughClues(player));character.addPlayerClue("A muddy footprint");assertTrue(ClueGiver.hasEnoughClues(player));}
    @Test void automaticCluesUseUnformattedRaceNamesAndTheCorrectArticle(){assertTrue(ClueGiver.getAutomaticClues(null).isEmpty());assertTrue(ClueGiver.getAutomaticClues(new RPCharacter(player)).isEmpty());for(var entry:Map.of("&aElf","an Elf","Human","a Human","","a ").entrySet()){var person=character(player,entry.getKey());assertEquals("This belongs to "+entry.getValue()+".",ClueFormatter.stripColor(ClueGiver.getAutomaticClues(person).getFirst()));}}
    @Test void cluePoolAndExclusionsKeepPlayerCluesAndReturnNullWhenExhausted(){assertTrue(ClueGiver.getCluePool(null).isEmpty());assertNull(ClueGiver.getRandomClue(null));character.addPlayerClue("A muddy footprint");var automatic=ClueGiver.getAutomaticClues(character).getFirst();var authored=character.getPlayerClues().getFirst();assertEquals(List.of(authored,automatic),ClueGiver.getCluePool(character));assertEquals(authored,ClueGiver.getRandomClueExcluding(character,List.of(automatic)));assertNull(ClueGiver.getRandomClueExcluding(character,List.of(automatic,authored)));assertTrue(ClueGiver.getCluePool(character).contains(ClueGiver.getRandomClue(character)));}
    @Test void formattingCannotPadShortCluesOrChangeTheirVisibleText(){assertEquals("",ClueFormatter.stripColor(ClueFormatter.format("")));for(String raw:List.of("&aX","#abcdefX","&#abcdefX","§aX")){assertEquals("X",ClueFormatter.stripColor(raw));assertNotNull(ClueFormatter.validate(raw));assertEquals(1,ClueFormatter.plainLength(raw));assertEquals(ClueFormatter.format("X"),ClueFormatter.format(raw));}}
    @Test void legacyClueLoreUsesTheRequestedReadableWidth(){assertEquals(List.of("A muddy footprint"),ClueFormatter.wrapLore("A muddy footprint").stream().map(ClueFormatter::stripColor).toList());assertEquals(List.of("first","second"),ClueFormatter.wrapLore("first second",6).stream().map(ClueFormatter::stripColor).toList());}
    @Test void legacyPhysicalClueIssuanceRemainsDisabledButExistingCluePaperIsReadable(){assertEquals(Material.AIR,ClueGiver.getClueItem(player,List.of()).getType());assertEquals(Material.AIR,ClueGiver.getClueItem(character,List.of()).getType());assertFalse(ClueGiver.isClueItem(null));assertFalse(ClueGiver.isClueItem(new ItemStack(Material.STONE)));assertFalse(ClueGiver.isClueItem(new ItemStack(Material.PAPER)));assertNull(ClueGiver.getClueText(new ItemStack(Material.PAPER)));var paper=new ItemStack(Material.PAPER);var meta=paper.getItemMeta();meta.setDisplayName("Ordinary paper");paper.setItemMeta(meta);assertFalse(ClueGiver.isClueItem(paper));meta.getPersistentDataContainer().set(ClueGiver.clueItemKey(),PersistentDataType.STRING,"A muddy footprint");paper.setItemMeta(meta);assertTrue(ClueGiver.isClueItem(paper));assertEquals("A muddy footprint",ClueGiver.getClueText(paper));}
    @Test void invalidSpawnInputsAndUnloadedAccountsNeverRegisterAClue(){var anchor=player.getLocation();assertNull(ClueGiver.spawnClue(null,player,List.of()));assertNull(ClueGiver.spawnClue(anchor,null,List.of()));assertNull(ClueGiver.spawnClue(new Location(null,0,70,0),player,List.of()));assertNull(ClueGiver.spawnClueWithText(null,null,player,"trace",false));assertNull(ClueGiver.spawnClueWithText(anchor,null,null,"trace",false));assertNull(ClueGiver.spawnClueWithText(new Location(null,0,70,0),null,player,"trace",false));assertNull(ClueGiver.spawnClueWithText(anchor,null,player,null,false));assertNull(ClueGiver.spawnClueWithText(anchor,null,player,"",false));loaded.clear();assertNull(ClueGiver.spawnClue(anchor,player,List.of()));assertNull(ClueGiver.spawnClueWithText(anchor,null,player,"trace",false));loaded.put(player,new PlayerData(player));assertNull(ClueGiver.spawnClue(anchor,player,List.of()));assertNull(ClueGiver.spawnClueWithText(anchor,null,player,"trace",false));verifyNoInteractions(spawned);}
    @Test void exactSpawnsPreserveAnchorsTargetsOwnerPotencyAndLifetime(){settings.setPotencyInitial(.75);var anchor=new Location(world,2.25,70.5,3.75);var target=new Location(world,5,68,7);long before=System.currentTimeMillis();var clue=ClueGiver.spawnClue(anchor,target,player,List.of());assertNotNull(clue);assertEquals(anchor.getX(),clue.getX());assertEquals(anchor.getY(),clue.getY());assertEquals(anchor.getZ(),clue.getZ());assertEquals(5,clue.getTargetBlockX());assertEquals(68,clue.getTargetBlockY());assertEquals(7,clue.getTargetBlockZ());assertEquals(player.getUniqueId(),clue.getOwnerUuid());assertEquals(.75,clue.getPotency());assertTrue(clue.getSpawnedAtMs()>=before);assertTrue(clue.getExpiresAtMs()>=before+7200000);assertEquals(ClueGiver.getAutomaticClues(character).getFirst(),clue.getClueText());verify(spawned).register(clue);assertEquals(new Location(world,2.25,70.5,3.75),anchor);}
    @Test void unlinkedAndCrossWorldTargetsAreNotRetained(){var anchor=player.getLocation();assertFalse(ClueGiver.spawnClue(anchor,player,List.of(),false).hasTargetBlock());assertFalse(ClueGiver.spawnClueWithText(anchor,new Location(server.addSimpleWorld("other"),0,70,0),player,"trace",false).hasTargetBlock());assertFalse(ClueGiver.spawnClueWithText(anchor,new Location(null,0,70,0),player,"trace",false).hasTargetBlock());assertEquals("trace",ClueGiver.spawnClueWithText(anchor,null,player,"trace",false).getClueText());}
    @Test void occupiedOrBlockedAnchorsAndExhaustedCluesAreRejected(){var anchor=player.getLocation();when(spawned.hasClueAt(anchor)).thenReturn(true);assertNull(ClueGiver.spawnClue(anchor,player,List.of()));assertNull(ClueGiver.spawnClueWithText(anchor,null,player,"trace",false));when(spawned.hasClueAt(anchor)).thenReturn(false);assertNull(ClueGiver.spawnClue(anchor,player,ClueGiver.getCluePool(character)));world.getBlockAt(anchor).setType(Material.STONE);assertNull(ClueGiver.spawnClue(anchor,player,List.of()));assertNull(ClueGiver.spawnClueWithText(anchor,null,player,"trace",false));verify(spawned,never()).register(any());}
    @Test void fallbackTextSpawnsUseTheValidNearbyAnchorOrReportFailure(){var anchor=new Location(world,5,70,5);world.getBlockAt(anchor).setType(Material.STONE);try(var random=new RandomBoundary(0)){var clue=ClueGiver.spawnClueWithText(anchor,null,player,"trace",true);assertNotNull(clue);assertEquals(.5,clue.getX());assertEquals(70,clue.getY());when(spawned.hasClueAt(any(Location.class))).thenReturn(true);assertNull(ClueGiver.spawnClueWithText(anchor,null,player,"trace",true));}}
    @Test void randomClueFallbackUsesTheAlreadyResolvedAnchorInsteadOfRollingAgain(){var anchor=new Location(world,5,70,5);world.getBlockAt(anchor).setType(Material.STONE);world.getBlockAt(1,70,0).setType(Material.STONE);try(var random=new RandomBoundary(0)){var calls=new AtomicInteger();when(random.random.nextInt(anyInt(),anyInt())).thenAnswer(call->{int index=calls.getAndIncrement();return index<3?0:(index-3)%3==0?1:0;});var clue=ClueGiver.spawnClue(anchor,player,List.of(),true);assertNotNull(clue,"The first valid fallback must not be discarded by a second random search");assertEquals(.5,clue.getX());verify(spawned).register(clue);}}
    @Test void randomSearchHandlesNullCentersOutsideCircleAndAlreadyOccupiedCandidates(){assertNull(ClueGiver.getRandomValidClueLocation((org.bukkit.entity.Player)null));assertNull(ClueGiver.getRandomValidClueLocation((Location)null));assertNull(ClueGiver.getRandomValidClueLocation(new Location(null,0,70,0)));try(var random=new RandomBoundary(1,0,1,0,0,0)){var anchor=ClueGiver.getRandomValidClueLocation(player);assertEquals(new Location(world,.5,70,.5),anchor);}when(spawned.hasClueAt(any(Location.class))).thenReturn(true);try(var random=new RandomBoundary(0)){assertNull(ClueGiver.getRandomValidClueLocation(player.getLocation()));}}
    @Test void anchorValidationRequiresTwoAirBlocks(){assertFalse(ClueGiver.isValidClueAnchor(null));assertFalse(ClueGiver.isValidClueAnchor(new Location(null,0,70,0)));var anchor=player.getLocation();assertTrue(ClueGiver.isValidClueAnchor(anchor));world.getBlockAt(0,71,0).setType(Material.STONE);assertFalse(ClueGiver.isValidClueAnchor(anchor));world.getBlockAt(0,71,0).setType(Material.AIR);world.getBlockAt(0,70,0).setType(Material.STONE);assertFalse(ClueGiver.isValidClueAnchor(anchor));}
    @Test void anchorsOutsideTheWorldBuildHeightAreRejectedWithoutReadingInvalidBlocks(){assertFalse(ClueGiver.isValidClueAnchor(new Location(world,0,world.getMaxHeight()-1,0)));assertFalse(ClueGiver.isValidClueAnchor(new Location(world,0,world.getMinHeight()-1,0)));}

    MagnifyingGlassDefinition glass(int cost,Map<String,Integer> requires){var config=new YamlConfiguration();config.set("item","minecraft:spyglass");config.set("investigation-cost",cost);config.set("search-radius",8);requires.forEach((key,value)->config.set("requires."+key,value));return new MagnifyingGlassDefinition("lens",config);}
    MockedStatic<MagnifyingGlassLoader> lens(MagnifyingGlassDefinition glass){var loader=boundary(MagnifyingGlassLoader.class);loader.when(()->MagnifyingGlassLoader.resolve(any(ItemStack.class))).thenReturn(glass);return loader;}
    org.bukkit.event.player.PlayerInteractEvent search(){return interact(Action.RIGHT_CLICK_AIR,null,EquipmentSlot.HAND,new ItemStack(Material.SPYGLASS));}
    @Test void lensIgnoresOtherHandsActionsAndUnrecognizedItems(){var listener=new MagnifyingGlassListener();var loader=lens(null);var offhand=interact(Action.RIGHT_CLICK_AIR,null,EquipmentSlot.OFF_HAND,new ItemStack(Material.SPYGLASS));listener.onInteract(offhand);var left=interact(Action.LEFT_CLICK_AIR,null,EquipmentSlot.HAND,new ItemStack(Material.SPYGLASS));listener.onInteract(left);loader.verifyNoInteractions();var unknown=search();listener.onInteract(unknown);assertFalse(unknown.isCancelled());verifyNoInteractions(spawned);}
    @Test void recognizedLensesCancelInteractionsButCannotSearchWhenDisabledOrUnloaded(){var listener=new MagnifyingGlassListener();lens(glass(1,Map.of()));settings.setActiveDiscoveryEnabled(false);var disabled=search();listener.onInteract(disabled);assertTrue(disabled.isCancelled());settings.setActiveDiscoveryEnabled(true);loaded.clear();listener.onInteract(search());loaded.put(player,new PlayerData(player));listener.onInteract(search());verifyNoInteractions(spawned);}
    @Test void lensRequirementsRejectLowStatsBeforeChargingInvestigationPoints(){lens(glass(1,Map.of("wisdom",2)));data.setInvestigationPoints(5);data.setLastInvestigationRegenMs(System.currentTimeMillis());new MagnifyingGlassListener().onInteract(search());assertEquals(5,data.getInvestigationPoints());assertTrue(messages(player).contains("not perceptive enough"));verifyNoInteractions(spawned);}
    @Test void successfulSearchChargesOnceUsesTheLargestRadiusAndStopsAfterFirstDiscovery(){var glass=glass(2,Map.of("ignored",0,"wisdom",2));lens(glass);character.getAttributeData().addModifier(new AttributeModifier("wisdom",2));data.setInvestigationPoints(5);data.setLastInvestigationRegenMs(System.currentTimeMillis());var first=clue();var second=clue();var third=clue();when(spawned.getCluesNear(player.getLocation(),8)).thenReturn(List.of(first,second,third));var discoveries=boundary(ClueDiscoveryService.class);discoveries.when(()->ClueDiscoveryService.tryActiveDiscovery(player,character,second,glass)).thenReturn(true);var listener=new MagnifyingGlassListener();listener.onInteract(search());assertEquals(3,data.getInvestigationPoints());discoveries.verify(()->ClueDiscoveryService.tryActiveDiscovery(player,character,first,glass));discoveries.verify(()->ClueDiscoveryService.tryActiveDiscovery(player,character,second,glass));discoveries.verify(()->ClueDiscoveryService.tryActiveDiscovery(player,character,third,glass),never());listener.onInteract(search());assertEquals(3,data.getInvestigationPoints());verify(spawned,times(1)).getCluesNear(any(),anyDouble());}
    @Test void exhaustedPointsReportTheConfiguredMessageWithoutStartingCooldown(){lens(glass(1,Map.of()));data.setInvestigationPoints(0);data.setLastInvestigationRegenMs(System.currentTimeMillis());var listener=new MagnifyingGlassListener();listener.onInteract(search());assertTrue(messages(player).contains("Out of focus"));verifyNoInteractions(spawned);data.setInvestigationPoints(2);listener.onInteract(search());assertEquals(1,data.getInvestigationPoints());verify(spawned).getCluesNear(any(),anyDouble());}
    @Test void pointsRecheckedAfterCandidateLookupPreventOverspending(){lens(glass(2,Map.of()));data.setInvestigationPoints(2);data.setLastInvestigationRegenMs(System.currentTimeMillis());when(spawned.getCluesNear(any(),anyDouble())).thenAnswer(call->{data.setInvestigationPoints(0);return List.of(clue());});new MagnifyingGlassListener().onInteract(search());assertEquals(0,data.getInvestigationPoints());assertTrue(messages(player).contains("Out of focus"));}
    @Test void zeroCostLensesUseDefaultCostAndOptionalNoClueMessages(){lens(glass(0,Map.of()));settings.setActiveInvestigationCost(3);settings.setActiveRadius(10);settings.setActiveCooldownSeconds(0);settings.setMessageNoClueNearby("No traces here");data.setInvestigationPoints(10);data.setLastInvestigationRegenMs(System.currentTimeMillis());var listener=new MagnifyingGlassListener();listener.onInteract(search());assertEquals(7,data.getInvestigationPoints());assertTrue(messages(player).contains("No traces here"));verify(spawned).getCluesNear(player.getLocation(),10);settings.setMessageNoClueNearby("");listener.onInteract(search());assertEquals("",messages(player));settings.setMessageNoClueNearby(null);listener.onInteract(search());assertEquals("",messages(player));}
    @Test void blockInteractionsDisturbOnlyCluesLinkedToThatBlock(){var listener=new ClueDisturbanceListener();listener.onInteract(interact(Action.LEFT_CLICK_BLOCK,world.getBlockAt(2,70,2),EquipmentSlot.HAND,null));listener.onInteract(interact(Action.RIGHT_CLICK_BLOCK,null,EquipmentSlot.HAND,null));verifyNoInteractions(spawned);var block=world.getBlockAt(2,70,2);var first=clue();var second=clue();when(spawned.getCluesLinkedToBlock(block.getLocation())).thenReturn(List.of(first,second));settings.setTargetInteractZeroLossChance(0);settings.setTargetInteractLossMin(.2);settings.setTargetInteractLossMax(.2);listener.onInteract(interact(Action.RIGHT_CLICK_BLOCK,block,EquipmentSlot.HAND,null));assertEquals(.8,first.getPotency());assertEquals(.8,second.getPotency());}

    static final class RandomBoundary implements AutoCloseable {final ThreadLocalRandom random=mock(ThreadLocalRandom.class);final MockedStatic<ThreadLocalRandom> factory;RandomBoundary(int...values){var count=new AtomicInteger();when(random.nextInt(anyInt(),anyInt())).thenAnswer(call->values[Math.min(count.getAndIncrement(),values.length-1)]);factory=mockStatic(ThreadLocalRandom.class);factory.when(ThreadLocalRandom::current).thenReturn(random);}public void close(){factory.close();}}
}
