package net.tfminecraft.rpcharacters.chat;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.util.*;
import java.util.function.Consumer;
import java.util.logging.Logger;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.chat.smart.*;
import net.tfminecraft.rpcharacters.identity.*;
import net.tfminecraft.rpcharacters.loaders.*;
import net.tfminecraft.rpcharacters.managers.*;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.speechbubble.SpeechBubbleSettings;
import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import org.bukkit.event.player.*;
import org.bukkit.plugin.PluginManager;
import org.bukkit.scheduler.*;
import org.junit.jupiter.api.*;
import org.mockito.MockedStatic;
import org.mockbukkit.mockbukkit.MockBukkit;

class ChatManagerTest {
    RuntimeTestState state; RPCharacters plugin; Logger logger; World world;
    Player sender,near,edge,far,hidden,denied,elsewhere; RPCharacter character; PlayerData data;
    final List<AutoCloseable> boundaries=new ArrayList<>();
    final List<Player> online=new ArrayList<>(),local=new ArrayList<>();
    final Map<Player,Set<String>> permissions=new HashMap<>();
    final Map<Player,List<String>> messages=new HashMap<>();
    final Map<String,ChatChannel> channels=new HashMap<>();
    final Map<String,String> aliases=new HashMap<>();
    final List<CharacterChatEvent> events=new ArrayList<>();
    final Deque<Runnable> scheduled=new ArrayDeque<>();
    Consumer<CharacterChatEvent> eventHook=e->{};
    MockedStatic<PlayerManager> players; MockedStatic<ClueInputManager> clues;
    MockedStatic<CreationManager> creation; MockedStatic<MaskService> masks;
    MockedStatic<SmartMessageService> smart; SmartMessageSettings settings; SpeechBubbleSettings bubbles;

    @BeforeEach void setup() {
        MockBukkit.mock(); state=new RuntimeTestState(RPCharacters.class,CreationManager.class,ChatRecipientResolverRegistry.class);
        Cache.attributes=new ArrayList<>(); Cache.professions=new ArrayList<>(); CreationManager.activeCreators.clear();
        plugin=mock(RPCharacters.class);logger=mock(Logger.class);when(plugin.getLogger()).thenReturn(logger);RPCharacters.plugin=plugin;
        world=mock(World.class);when(world.getPlayers()).thenReturn(local);
        sender=player("Speaker",0);near=player("Near",3);edge=player("Edge",10);far=player("Far",11);hidden=player("Hidden",4);denied=player("Denied",4);elsewhere=player("Elsewhere",2);local.remove(elsewhere);
        when(elsewhere.getWorld()).thenReturn(mock(World.class));
        character=new RPCharacter(sender);character.setName("Aria");data=spy(new PlayerData(sender));data.addCharacter(character);doReturn(character).when(data).getActiveCharacter();
        players=boundary(PlayerManager.class);players.when(()->PlayerManager.get(sender)).thenReturn(data);
        clues=boundary(ClueInputManager.class);creation=boundary(CreationManager.class);
        var identities=boundary(DisplayIdentityService.class);identities.when(()->DisplayIdentityService.resolveDisplayUnmasked(any(Player.class))).thenReturn("Aria");identities.when(()->DisplayIdentityService.resolveDisplayTab(any(Player.class))).thenReturn("AriaTab");
        masks=boundary(MaskService.class);masks.when(MaskService::getMaskedLabel).thenReturn("Masked");
        settings=new SmartMessageSettings();settings.setEnabled(false);boundary(SmartMessageLoader.class).when(SmartMessageLoader::getSettings).thenReturn(settings);
        bubbles=new SpeechBubbleSettings();bubbles.setDebugMessages(true);boundary(SpeechBubbleLoader.class).when(SpeechBubbleLoader::getSettings).thenReturn(bubbles);
        smart=boundary(SmartMessageService.class);
        var loader=boundary(ChatLoader.class);loader.when(()->ChatLoader.getChannel(any())).thenAnswer(c->{String id=c.getArgument(0);return id==null?null:channels.get(id.toLowerCase(Locale.ROOT));});loader.when(ChatLoader::getDefaultChannel).thenAnswer(c->channels.get(Cache.chatDefaultChannel));loader.when(()->ChatLoader.resolveChannelFromCommand(any())).thenAnswer(c->aliases.get(c.getArgument(0)));
        var scheduler=mock(BukkitScheduler.class);when(scheduler.runTask(eq(plugin),any(Runnable.class))).thenAnswer(c->{scheduled.add(c.getArgument(1));return mock(BukkitTask.class);});
        var plugins=mock(PluginManager.class);doAnswer(c->{if(c.getArgument(0) instanceof CharacterChatEvent e){events.add(e);eventHook.accept(e);}return null;}).when(plugins).callEvent(any());
        var bukkit=mockStatic(Bukkit.class,CALLS_REAL_METHODS);boundaries.add(bukkit);bukkit.when(Bukkit::getScheduler).thenReturn(scheduler);bukkit.when(Bukkit::getPluginManager).thenReturn(plugins);bukkit.when(Bukkit::getOnlinePlayers).thenReturn(online);
        Cache.chatDefaultChannel="rp";Cache.chatBypassCooldownPermission="chat.bypass";Cache.chatNoCharacterMessage="No character";Cache.chatChannelCantUseWhenToggledOffMessage="Channel hidden";
        Cache.chatChannelSwitcherEnabled=true;Cache.chatChannelTogglerEnabled=true;Cache.chatSwitchableChannels=List.of("rp","ooc","missing");Cache.chatToggleableChannels=List.of("rp","ooc","missing");
        Cache.chatRunAsPlayerMessage="Players only";Cache.chatChannelSwitchDisabledMessage="Switch disabled";Cache.chatChannelToggleDisabledMessage="Toggle disabled";Cache.chatChannelCurrentMessage="Current {channel}";Cache.chatChannelInvalidUseMessage="Usage {usage}";Cache.chatChannelInvalidChannelMessage="Invalid {channels}";Cache.chatChannelAlreadySwitchedMessage="Already switched";Cache.chatChannelSwitchedMessage="Switched {channel}";Cache.chatChannelToggledOnMessage="Enabled {channel}";Cache.chatChannelToggledOffMessage="Disabled {channel}";
        channel("rp");channel("ooc","range",0,"require-character",false);aliases.put("say","rp");aliases.put("rp","rp");
    }
    @AfterEach void teardown() throws Exception {for(Player p:online){ChatChannelPreferenceManager.get().clear(p);ChatCooldownManager.get().clear(p);}for(int i=boundaries.size()-1;i>=0;i--)boundaries.get(i).close();MockBukkit.unmock();state.close();}
    <T> MockedStatic<T> boundary(Class<T> type){var m=mockStatic(type);boundaries.add(m);return m;}
    Player player(String name,double x){var p=mock(Player.class);when(p.getName()).thenReturn(name);when(p.getServer()).thenReturn(Bukkit.getServer());when(p.getUniqueId()).thenReturn(UUID.randomUUID());when(p.isOnline()).thenReturn(true);when(p.getWorld()).thenReturn(world);when(p.getLocation()).thenAnswer(c->new Location(world,x,64,0));permissions.put(p,new HashSet<>());messages.put(p,new ArrayList<>());when(p.hasPermission(anyString())).thenAnswer(c->permissions.get(p).contains(c.getArgument(0)));doAnswer(c->{messages.get(p).add(c.getArgument(0));return null;}).when(p).sendMessage(anyString());online.add(p);local.add(p);return p;}
    ChatChannel channel(String id,Object... pairs){var yaml=new org.bukkit.configuration.file.YamlConfiguration();yaml.set("commands",List.of(id));yaml.set("range",10);yaml.set("require-character",true);yaml.set("bubble",true);yaml.set("format","{display}: {message}");for(int i=0;i<pairs.length;i+=2)yaml.set((String)pairs[i],pairs[i+1]);var channel=new ChatChannel(id,yaml);channels.put(id,channel);return channel;}
    void dispatch(ChatChannel c,String message){ChatManager.dispatch(sender,c,message,false);}
    String text(Player p){return String.join("\n",messages.get(p));}
    AsyncPlayerChatEvent chat(Player p,String text){return new AsyncPlayerChatEvent(true,p,text,new HashSet<>(online));}
    Command command(String name){var c=mock(Command.class);when(c.getName()).thenReturn(name);return c;}

    @Test void localRoutingHonoursBoundaryDistanceReadPermissionAndVisibility(){var c=channel("rp","read-perm","chat.read");for(Player p:online)permissions.get(p).add("chat.read");permissions.get(denied).clear();ChatChannelPreferenceManager.get().toggleChannelVisibility(hidden,"rp");dispatch(c," hello ");assertEquals(Set.of(sender,near,edge),events.getFirst().getRecipients());assertEquals("Aria: hello",text(near));assertEquals("",text(far));assertEquals("",text(hidden));assertEquals("",text(denied));assertEquals("",text(elsewhere));assertSame(character,events.getFirst().getCharacter());assertSame(sender,events.getFirst().getSender());assertFalse(events.getFirst().isMasked());assertFalse(events.getFirst().wasCommand());}
    @Test void globalRoutingCanReachOtherWorldsAndExcludeTheSender(){var c=channel("rp","range",0,"read-perm","read");permissions.get(elsewhere).add("read");permissions.get(far).add("read");dispatch(c,"global");assertEquals(Set.of(elsewhere,far),events.getFirst().getRecipients());assertEquals("Aria: global",text(elsewhere));assertEquals("",text(sender));}
    @Test void dispatchInputAndAccessGuardsDoNotFireEventsOrConsumeCooldown(){var c=channel("rp","use-perm","use","cooldown",30);ChatManager.dispatch(null,c,"x",false);ChatManager.dispatch(sender,null,"x",false);dispatch(c,null);dispatch(c,"  ");dispatch(c,"forbidden");assertTrue(text(sender).contains("cannot use"));permissions.get(sender).add("use");ChatChannelPreferenceManager.get().toggleChannelVisibility(sender,"rp");dispatch(c,"hidden");assertTrue(text(sender).contains("Channel hidden"));ChatChannelPreferenceManager.get().toggleChannelVisibility(sender,"rp");players.when(()->PlayerManager.get(sender)).thenReturn(null);dispatch(c,"missing");assertTrue(text(sender).contains("No character"));players.when(()->PlayerManager.get(sender)).thenReturn(data);doReturn(null).when(data).getActiveCharacter();dispatch(c,"missing");assertTrue(events.isEmpty());assertFalse(ChatCooldownManager.get().isOnCooldown(sender,"rp",30));verify(logger,atLeastOnce()).info(contains("SKIP"));}
    @Test void formattingOnlyTextIsDiscardedBeforeEventAndCooldown(){dispatch(channel("rp","cooldown",30),"§a§l");assertTrue(events.isEmpty());assertTrue(text(sender).isEmpty());assertFalse(ChatCooldownManager.get().isOnCooldown(sender,"rp",30));dispatch(channels.get("rp"),"\u0000");assertTrue(events.isEmpty());}
    @Test void colorPermissionStripsEverySyntaxThatTheRendererRecognises(){var c=channel("rp","color-code-perm","color");dispatch(c," &aGreen #abcdefHex §cRed ");assertEquals("Green Hex Red",events.getFirst().getMessage(),"Ampersand and hex formatting must not bypass the channel color permission");assertEquals("Aria: Green Hex Red",text(near));}
    @Test void authorisedColorCodesAndMaskedIdentityReachTheSameEventAndChat(){var c=channel("rp","color-code-perm","color","masked",true);permissions.get(sender).add("color");masks.when(()->MaskService.isMasked(sender)).thenReturn(true);ChatManager.dispatch(sender,c," &aGreen ",true);assertTrue(events.getFirst().isMasked());assertTrue(events.getFirst().wasCommand());assertEquals("&aGreen",events.getFirst().getMessage());assertEquals("Masked",events.getFirst().getDisplayName());assertEquals("Masked: §aGreen",text(near));}
    @Test void otherPluginsCanCancelOrRewriteTheRealEventBeforeDelivery(){var c=channel("rp","cooldown",30);eventHook=e->e.setCancelled(true);dispatch(c,"cancel");assertTrue(text(near).isEmpty());assertFalse(ChatCooldownManager.get().isOnCooldown(sender,"rp",30));eventHook=e->{e.setMessage("edited");e.setDisplayName("Edited");e.setChannel("rp");e.setRecipients(new HashSet<>(Arrays.asList(near,hidden,far,null)));when(far.isOnline()).thenReturn(false);ChatChannelPreferenceManager.get().toggleChannelVisibility(hidden,"rp");};dispatch(c,"original");assertEquals("Edited: edited",text(near));assertTrue(text(hidden).isEmpty());assertTrue(text(far).isEmpty());assertEquals(CharacterChatEvent.getHandlerList(),events.getLast().getHandlers());assertThrows(UnsupportedOperationException.class,()->events.getLast().getRecipients().clear());}
    @Test void emptyRecipientAndFormatResultsDoNotConsumeCooldown(){var c=channel("rp","cooldown",30);eventHook=e->e.setRecipients(null);dispatch(c,"nobody");assertTrue(text(sender).contains("No one can hear"));assertFalse(ChatCooldownManager.get().isOnCooldown(sender,"rp",30));eventHook=e->{};dispatch(channel("rp","cooldown",30,"format",""),"no format");assertFalse(ChatCooldownManager.get().isOnCooldown(sender,"rp",30));}
    @Test void deliveryCooldownIsPerChannelAndBypassDoesNotCreateAnEntry(){var c=channel("rp","cooldown",30);dispatch(c,"first");dispatch(c,"second");assertEquals(1,events.size());assertTrue(text(sender).contains("Wait"));assertTrue(ChatCooldownManager.get().getRemainingSeconds(sender,"rp")>0);dispatch(channels.get("ooc"),"elsewhere");assertEquals(2,events.size());ChatCooldownManager.get().clear(sender);permissions.get(sender).add("chat.bypass");dispatch(c,"bypass");dispatch(c,"again");assertEquals(4,events.size());assertFalse(ChatCooldownManager.get().isOnCooldown(sender,"rp",30));}
    @Test void localSmartChannelsDelegateTheActualModifiedEventButGlobalChannelsDoNot(){settings.setEnabled(true);var c=channel("rp","smart-messages",true,"cooldown",30);eventHook=e->e.setMessage("edited");dispatch(c,"source");smart.verify(()->SmartMessageService.deliver(events.getFirst(),c,sender));assertTrue(text(near).isEmpty());assertTrue(ChatCooldownManager.get().isOnCooldown(sender,"rp",30));dispatch(channel("ooc","range",0,"smart-messages",true),"global");assertEquals("Aria: edited",text(elsewhere));}
    @Test void customResolverFailuresAreContainedAndSuccessfulSetsAreCopied(){var c=channel("rp","recipient-resolver","test:party");ChatRecipientResolverRegistry.register("test:party",(s,ch)->{assertSame(sender,s);assertSame(c,ch);return new HashSet<>(Set.of(elsewhere));});dispatch(c,"party");assertEquals(Set.of(elsewhere),events.getFirst().getRecipients());assertEquals("Aria: party",text(elsewhere));ChatRecipientResolverRegistry.register("test:party",(s,ch)->{throw new IllegalStateException("offline backend");});dispatch(c,"failed");assertTrue(text(sender).contains("No one can hear"));verify(logger).warning(contains("offline backend"));ChatRecipientResolverRegistry.unregister("test:party");dispatch(c,"missing");dispatch(c,"missing again");verify(logger,times(1)).warning(contains("No chat recipient resolver"));}
    @Test void plainChatSkipsCreationClueInputBlankAndCommandsWithoutCancelling(){var listener=new ChatManager();for(String message:List.of("","  ","  /help")){var e=chat(sender,message);listener.onPlainChat(e);assertFalse(e.isCancelled());}var malformed=mock(AsyncPlayerChatEvent.class);listener.onPlainChat(malformed);when(malformed.getPlayer()).thenReturn(sender);listener.onPlainChat(malformed);CreationManager.activeCreators.put(sender,null);var creationEvent=chat(sender,"creation answer");listener.onPlainChat(creationEvent);assertFalse(creationEvent.isCancelled());CreationManager.activeCreators.clear();clues.when(()->ClueInputManager.isPending(sender)).thenReturn(true);var clue=chat(sender,"clue answer");listener.onPlainChat(clue);assertFalse(clue.isCancelled());assertTrue(scheduled.isEmpty());}
    @Test void plainChatSchedulesMainThreadDispatchAndRevalidatesCharacter(){var e=chat(sender,"hello");new ChatManager().onPlainChat(e);assertTrue(e.isCancelled());assertEquals(1,scheduled.size());assertTrue(events.isEmpty());scheduled.remove().run();assertEquals("Aria: hello",text(near));doReturn(null).when(data).getActiveCharacter();var missing=chat(sender,"no character");new ChatManager().onPlainChat(missing);assertTrue(missing.isCancelled());assertEquals(1,scheduled.size());scheduled.remove().run();assertTrue(text(sender).contains("No character"));players.when(()->PlayerManager.get(sender)).thenReturn(null);var noData=chat(sender,"none");new ChatManager().onPlainChat(noData);scheduled.remove().run();channels.clear();new ChatManager().onPlainChat(chat(sender,"missing config"));verify(logger).warning(contains("Default chat channel not loaded"));}
    @Test void delayedPlainChatDoesNotBroadcastAfterTheSenderDisconnects(){new ChatManager().onPlainChat(chat(sender,"queued"));when(sender.isOnline()).thenReturn(false);scheduled.remove().run();assertTrue(events.isEmpty(),"A queued chat callback must not broadcast for a disconnected sender");assertTrue(text(near).isEmpty());}
    @Test void preferenceAndCooldownLifecycleKeepPlayersAndChannelsSeparate() throws Exception {var p=ChatChannelPreferenceManager.get();assertNull(p.getSwitchedChannelId(null));assertFalse(p.setSwitchedChannel(null,"rp"));assertFalse(p.setSwitchedChannel(sender,null));assertTrue(p.isChannelVisible(null,"rp"));assertTrue(p.isChannelVisible(sender,null));assertTrue(p.toggleChannelVisibility(null,"rp"));assertTrue(p.toggleChannelVisibility(sender,null));p.clear(null);assertSame(channels.get("rp"),p.getActiveChannel(sender));assertTrue(p.setSwitchedChannel(sender,"OOC"));assertSame(channels.get("ooc"),p.getActiveChannel(sender));p.setSwitchedChannel(sender,"gone");assertSame(channels.get("rp"),p.getActiveChannel(sender));assertFalse(p.toggleChannelVisibility(sender,"RP"));assertFalse(p.isChannelVisible(sender,"rp"));assertTrue(p.toggleChannelVisibility(sender,"rp"));assertTrue(p.isChannelVisible(sender,"rp"));p.onQuit(new PlayerQuitEvent(sender,"bye"));assertNull(p.getSwitchedChannelId(sender));var cd=ChatCooldownManager.get();assertFalse(cd.isOnCooldown(null,"rp",1));assertFalse(cd.isOnCooldown(sender,"rp",0));cd.applyCooldown(null,"rp",1);cd.applyCooldown(sender,"rp",0);cd.clear(null);assertEquals(0,cd.getRemainingSeconds(sender,"rp"));cd.applyCooldown(sender,"rp",1);assertEquals(0,cd.getRemainingSeconds(sender,"other"));assertFalse(cd.isOnCooldown(sender,"other",1));assertEquals(1,cd.getRemainingSeconds(sender,"rp"));Thread.sleep(1_025);assertEquals(0,cd.getRemainingSeconds(sender,"rp"));assertFalse(cd.isOnCooldown(sender,"rp",1));cd.onQuit(new PlayerQuitEvent(sender,"bye"));assertEquals(0,cd.getRemainingSeconds(sender,"rp"));}
    @Test void channelSwitchAndToggleCommandsUseConfiguredIdsAndAliases(){var h=new ChatChannelCommandHandler();var channel=command("CHANNEL");assertTrue(h.onCommand(mock(CommandSender.class),channel,"channel",null));h.onCommand(sender,channel,"channel",null);assertTrue(text(sender).contains("Current rp"));h.onCommand(sender,channel,"channel",new String[]{"rp"});assertTrue(text(sender).contains("Already switched"));h.onCommand(sender,channel,"channel",new String[]{"ooc"});assertEquals("ooc",ChatChannelPreferenceManager.get().getSwitchedChannelId(sender));assertTrue(text(sender).contains("Switched ooc"));h.onCommand(sender,channel,"channel",new String[]{"ooc"});h.onCommand(sender,channel,"channel",new String[]{"SAY"});assertEquals("rp",ChatChannelPreferenceManager.get().getSwitchedChannelId(sender));var toggle=command("channeltoggle");h.onCommand(sender,toggle,"ct",new String[]{"SAY"});assertFalse(ChatChannelPreferenceManager.get().isChannelVisible(sender,"rp"));assertTrue(text(sender).contains("Disabled rp"));h.onCommand(sender,toggle,"ct",new String[]{"rp"});assertTrue(ChatChannelPreferenceManager.get().isChannelVisible(sender,"rp"));assertTrue(text(sender).contains("Enabled rp"));}
    @Test void channelCommandErrorsAndCompletionsDoNotChangePreferences(){var h=new ChatChannelCommandHandler();var c=command("channel");var t=command("channeltoggle");h.onCommand(sender,c,"ch",new String[]{"a","b"});h.onCommand(sender,t,"ct",null);h.onCommand(sender,t,"ct",new String[0]);aliases.put("removed","missing");for(String invalid:Arrays.asList(null," ","bad","missing","removed")){h.onCommand(sender,c,"ch",new String[]{invalid});h.onCommand(sender,t,"ct",new String[]{invalid});}assertTrue(text(sender).contains("Usage ch <channel>"));assertTrue(text(sender).contains("Invalid rp, ooc, missing"));Cache.chatChannelSwitcherEnabled=false;h.onCommand(sender,c,"ch",new String[]{"ooc"});Cache.chatChannelTogglerEnabled=false;h.onCommand(sender,t,"ct",new String[]{"rp"});assertTrue(text(sender).contains("Switch disabled"));assertTrue(text(sender).contains("Toggle disabled"));h.onCommand(sender,command("other"),"other",new String[0]);Cache.chatChannelSwitcherEnabled=true;channels.clear();h.onCommand(sender,c,"ch",new String[0]);assertTrue(text(sender).contains("Current rp"));Locale.setDefault(Locale.forLanguageTag("tr-TR"));assertEquals(List.of("missing"),h.onTabComplete(sender,c,"ch",new String[]{"MI"}));assertEquals(List.of("rp"),h.onTabComplete(sender,t,"ct",new String[]{"r"}));assertTrue(h.onTabComplete(sender,c,"ch",new String[0]).isEmpty());assertTrue(h.onTabComplete(sender,command("other"),"other",new String[]{""}).isEmpty());assertNull(ChatChannelPreferenceManager.get().getSwitchedChannelId(sender));}
    @Test void commandInterceptorDistinguishesCreationInputFromUnrelatedCommands(){var h=new ChatChannelCommandInterceptor();var invalid=mock(PlayerCommandPreprocessEvent.class);h.onPlayerCommand(invalid);var unknown=new PlayerCommandPreprocessEvent(sender,"/unknown x");h.onPlayerCommand(unknown);assertFalse(unknown.isCancelled());var usage=new PlayerCommandPreprocessEvent(sender,"/say");h.onPlayerCommand(usage);assertTrue(usage.isCancelled());assertTrue(text(sender).contains("Usage: /say"));CreationManager.activeCreators.put(sender,null);var blocked=new PlayerCommandPreprocessEvent(sender,"/say blocked");h.onPlayerCommand(blocked);creation.verify(()->CreationManager.sendChatBlockedDuringCreationHint(sender));assertTrue(events.isEmpty());creation.when(()->CreationManager.isChatInputStage(sender)).thenReturn(true);var allowed=new PlayerCommandPreprocessEvent(sender,"/say allowed");h.onPlayerCommand(allowed);assertTrue(allowed.isCancelled());assertEquals("allowed",events.getFirst().getMessage());assertTrue(events.getFirst().wasCommand());}
    @Test void commandExecutorSupportsConsoleUsageUnknownAndActualDelivery(){var h=new ChatChannelExecutor();var console=mock(CommandSender.class);assertTrue(h.onCommand(console,command("say"),"say",null));verify(console).sendMessage(contains("Players only"));assertTrue(h.onCommand(sender,command("other"),"unknown",new String[]{"x"}));assertTrue(h.onCommand(sender,command("say"),"say",null));assertTrue(text(sender).contains("Usage: /say"));assertTrue(h.onCommand(sender,command("say"),"say",new String[]{"hello","world"}));assertEquals("hello world",events.getFirst().getMessage());assertTrue(events.getFirst().wasCommand());}
    @Test void commandExecutorCannotBypassCreationRestrictions(){CreationManager.activeCreators.put(sender,null);new ChatChannelExecutor().onCommand(sender,command("say"),"say",new String[]{"blocked"});assertTrue(events.isEmpty(),"Bukkit dispatchCommand must enforce the same creation guard as preprocess events");creation.verify(()->CreationManager.sendChatBlockedDuringCreationHint(sender));}
    @Test void formatterAndRecipientFilterPublicInputsRetainTheirContracts(){var c=channel("rp","format","{display}|{display_tab}|{player}|{message}");assertEquals("",ChatFormatter.format(null,sender,"Name","message"));assertEquals("",ChatFormatter.format(c,null,"Name","message"));assertEquals("Aria|AriaTab|Speaker|",ChatFormatter.format(c,sender,null,null));assertEquals("Aria|AriaTab|Speaker|hello",ChatFormatter.format(c,sender,"","hello"));assertEquals("Other|AriaTab|Speaker|hello",ChatFormatter.format(c,sender,"Other","hello"));assertFalse(ChatRecipientFilters.canReceive(null,c));assertFalse(ChatRecipientFilters.canReceive(sender,null));assertEquals(Set.of(sender),ChatRecipientFilters.filterCandidates(sender,c,null));assertEquals(Set.of(sender,near),ChatRecipientFilters.filterCandidates(sender,c,Arrays.asList(null,sender,near)));assertEquals(Set.of(near),ChatRecipientFilters.filterCandidates(null,c,List.of(near)));}
    @Test void vanillaKillSwitchCancelsBothEventTypesAndClearsBroadcastTargets(){var h=new VanillaChatKillSwitch();var legacy=chat(sender,"hello");h.onLegacyChat(legacy);assertTrue(legacy.isCancelled());assertTrue(legacy.getRecipients().isEmpty());var paper=mock(io.papermc.paper.event.player.AsyncChatEvent.class);var viewers=new HashSet<net.kyori.adventure.audience.Audience>(Set.of(sender,near));when(paper.viewers()).thenReturn(viewers);h.onPaperChat(paper);verify(paper).setCancelled(true);assertTrue(viewers.isEmpty());}
    @Test void messageColorPrefixesPreserveLegacyAndBothHexSyntaxes(){assertEquals("&7",ChatFormatUtil.extractMessageColorPrefix(null));assertEquals("&7",ChatFormatUtil.extractMessageColorPrefix(""));assertEquals("&7",ChatFormatUtil.extractMessageColorPrefix("no message"));assertEquals("&7",ChatFormatUtil.extractMessageColorPrefix("plain {message}"));assertEquals("#aBc123&L",ChatFormatUtil.extractMessageColorPrefix("Name: #aBc123&L{message}"));assertEquals("&0&9&a&f&K&l&m&n&o&r",ChatFormatUtil.extractMessageColorPrefix("&0&9&a&f&K&l&m&n&o&r{message}"));assertEquals("&7",ChatFormatUtil.extractMessageColorPrefix("&z{message}"));assertEquals("&7",ChatFormatUtil.extractMessageColorPrefix("#12345z{message}"));assertEquals("&7",ChatFormatUtil.extractMessageColorPrefix("&#1234567{message}"));assertEquals("&#aBc123&l",ChatFormatUtil.extractMessageColorPrefix("Name: &#aBc123&l{message}"));}
    @Test void resolverPublicGuardsAndEmptyResponsesNeverLeakRecipients(){var c=channels.get("rp");ChatRecipientResolverRegistry.register(null,(s,ch)->Set.of(near));ChatRecipientResolverRegistry.register(" ",(s,ch)->Set.of(near));ChatRecipientResolverRegistry.register("test:null",null);ChatRecipientResolverRegistry.unregister(null);ChatRecipientResolverRegistry.unregister(" ");assertTrue(ChatRecipientResolverRegistry.resolve(null,sender,c).isEmpty());assertTrue(ChatRecipientResolverRegistry.resolve(" ",sender,c).isEmpty());assertTrue(ChatRecipientResolverRegistry.resolve("test",null,c).isEmpty());assertTrue(ChatRecipientResolverRegistry.resolve("test",sender,null).isEmpty());ChatRecipientResolverRegistry.register("test:empty",(s,ch)->null);assertTrue(ChatRecipientResolverRegistry.resolve("test:empty",sender,c).isEmpty());ChatRecipientResolverRegistry.register("test:empty",(s,ch)->Set.of());assertTrue(ChatRecipientResolverRegistry.resolve("test:empty",sender,c).isEmpty());RPCharacters.plugin=null;assertTrue(ChatRecipientResolverRegistry.resolve("test:absent",sender,c).isEmpty());}

}
