package net.tfminecraft.rpcharacters.identity;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.*;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.mockito.*;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.managers.PlayerManager;
import net.tfminecraft.rpcharacters.enums.Status;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.objects.races.Race;
import net.tfminecraft.rpcharacters.persona.AliasValidator;

class IdentityRuntimeTest {
 ServerMock server;PlayerMock player;RuntimeTestState state;PlayerData data;RPCharacter character;Map<Player,PlayerData> loaded=new HashMap<>();MockedStatic<PlayerManager> players;MockedStatic<MaskService> masks;
 @BeforeEach void setup(){server=MockBukkit.mock();state=new RuntimeTestState();Cache.attributes=new ArrayList<>();Cache.professions=new ArrayList<>();Cache.personaNoCharacterFallback="None";Cache.personaGenderDefault="Unknown";Cache.calendarAgeUnsetLabel="Unset";Cache.personaAliasAllowedChars="abcdefghijklmnopqrstuvwxyz -";Cache.personaDisplayNameMinLength=2;Cache.personaDisplayNameMaxLength=20;player=server.addPlayer();data=new PlayerData(player);character=character("Aria",true);data.getCharacters().add(character);loaded.put(player,data);players=mockStatic(PlayerManager.class);players.when(()->PlayerManager.get(any(Player.class))).thenAnswer(c->loaded.get(c.getArgument(0)));masks=mockStatic(MaskService.class);masks.when(MaskService::getMaskedLabel).thenReturn("Masked");}
 @AfterEach void cleanup(){masks.close();players.close();state.close();MockBukkit.unmock();}
 RPCharacter character(String name,boolean active){var cfg=new YamlConfiguration();cfg.set("name","Elf");return new RPCharacter(player,UUID.randomUUID().toString(),name,active,Status.ALIVE,new Race("elf",cfg),new ArrayList<>(),null);}
 @Test void personaFieldsResolveActiveDataAndFallbacks(){assertFalse(PersonaService.hasActiveCharacter(null));assertNull(PersonaService.getActiveCharacter(null));loaded.remove(player);assertFalse(PersonaService.hasActiveCharacter(player));assertNull(PersonaService.getActiveCharacter(player));assertEquals("",PersonaService.resolveRace(player));assertEquals("Unknown",PersonaService.resolveGender(player));assertEquals("Unset",PersonaService.resolveAge(player));assertEquals("Unset",PersonaService.resolveBirthday(player));assertEquals("",PersonaService.resolveDescription(player));loaded.put(player,data);assertTrue(PersonaService.hasActiveCharacter(player));assertSame(character,PersonaService.getActiveCharacter(player));assertEquals("Elf",PersonaService.resolveRace(player));assertEquals("Unknown",PersonaService.resolveGender(player));character.setGender("Woman");assertEquals("Woman",PersonaService.resolveGender(character));assertEquals("Unset",PersonaService.resolveAge(character));Cache.personaDescriptionDefaultTemplate="A{n} {race} from {continent}";Cache.continent="Vardera";assertEquals("An Elf from Vardera",PersonaService.resolveDescription(player));character.setPersonaDescription("A traveller");assertEquals("A traveller",PersonaService.resolveDescription(character));character.setPersonaDescription(null);Cache.personaDescriptionDefaultTemplate=" ";assertEquals("",PersonaService.resolveDescription(character));character.setRace(null);assertEquals("",PersonaService.resolveRace(character));Cache.personaDescriptionDefaultTemplate="A{n} {race} {continent}";Cache.continent=null;assertEquals("A  ",PersonaService.resolveDescription(character));character.setBirthday("invalid");assertNotNull(PersonaService.resolveAge(character));assertNotNull(PersonaService.resolveBirthday(character));}
 @Test void displayIdentityHonoursAliasesMasksAndHiddenFacades(){assertEquals("",DisplayIdentityService.resolveCharacterName((Player)null));assertEquals("",DisplayIdentityService.resolveCharacterName((RPCharacter)null));assertEquals("",DisplayIdentityService.resolveEffectivePlain((RPCharacter)null));assertEquals("None",DisplayIdentityService.resolveDisplayTab((RPCharacter)null));assertEquals("None",DisplayIdentityService.resolveDisplaySafe(null));assertNull(DisplayIdentityService.resolveSafeCharacter(null));assertEquals("Aria",DisplayIdentityService.resolveCharacterName(player));assertEquals("Aria",DisplayIdentityService.resolveCharacterName(character));character.setAlias("Alias");assertEquals("Alias",DisplayIdentityService.resolveEffectivePlain(player));assertEquals("§fAlias",DisplayIdentityService.resolveDisplayTab(player));assertEquals("§fAlias",DisplayIdentityService.resolveDisplay(player));assertEquals("§fAlias",DisplayIdentityService.resolveDisplay(character));masks.when(()->MaskService.isMasked(player)).thenReturn(true);assertTrue(DisplayIdentityService.isMasked(player));assertEquals("Masked",DisplayIdentityService.resolveDisplay(player));assertEquals("Masked",DisplayIdentityService.resolveDisplay(character));assertEquals("§fAlias",DisplayIdentityService.resolveDisplayUnmasked(character));character.setHidden(true);assertEquals("None",DisplayIdentityService.resolveDisplaySafe(player));var facade=character("Public",false);data.getCharacters().add(facade);assertSame(facade,DisplayIdentityService.resolveSafeCharacter(player));assertEquals("§fPublic",DisplayIdentityService.resolveDisplaySafe(player));character.setHidden(false);assertSame(character,DisplayIdentityService.resolveSafeCharacter(player));data.setTempAlias("Temporary");assertEquals("Temporary",DisplayIdentityService.resolveDisplayUnmasked(player));assertEquals("Temporary",DisplayIdentityService.resolveDisplayUnmasked(character));character.setNameColour(NameColour.solid("#aabbcc"));assertEquals("Temporary",ChatColor.stripColor(DisplayIdentityService.resolveDisplayUnmasked(player)));data.getCharacters().clear();assertEquals("Temporary",DisplayIdentityService.resolveDisplayUnmasked(player));assertEquals("None",DisplayIdentityService.resolveDisplayUnmasked((RPCharacter)null));}
 @Test void whitePrefixesAndTemporaryAliasesAreConsistent(){assertEquals("",DisplayIdentityService.colourPlain(null,null));assertEquals("",DisplayIdentityService.colourPlain("",null));assertEquals("",DisplayIdentityService.ensureDisplayTabWhite(null));assertEquals("",DisplayIdentityService.ensureDisplayTabWhite(""));assertEquals("§fName",DisplayIdentityService.ensureDisplayTabWhite("§fName"));assertEquals("§fName",DisplayIdentityService.colourPlain("Name",null));assertEquals("",TempAliasService.getPlain(player));assertNotNull(TempAliasService.set(player,"!"));assertNull(TempAliasService.set(player,"Alias"));assertEquals("Alias",TempAliasService.getPlain(player));assertNull(TempAliasService.setPlain(player," §aTrimmed "));assertEquals("Trimmed",TempAliasService.getPlain(player));TempAliasService.clear(player);assertEquals("",TempAliasService.getPlain(player));loaded.remove(player);assertEquals("",TempAliasService.getPlain(player));assertNotNull(TempAliasService.setPlain(player,"Alias"));TempAliasService.clear(player);}
 @Test void namesAndAliasesValidateLengthColoursAndAllowedCharacters(){assertNotNull(AliasValidator.validate(null));assertNotNull(AliasValidator.validate(""));assertNotNull(AliasValidator.validate("a"));assertNotNull(AliasValidator.validate("a".repeat(21)));assertNotNull(AliasValidator.validate("abc!"));assertNull(AliasValidator.validate("Aria-A"));assertNull(AliasValidator.validate("a".repeat(21),false));assertNotNull(AliasValidator.validateCharacterName(null));assertNotNull(AliasValidator.validateCharacterName(" "));assertNotNull(AliasValidator.validateCharacterName("§aAria"));assertNotNull(AliasValidator.validateCharacterName("&rAria"));assertNotNull(AliasValidator.validateCharacterName("#abcdefAria"));assertNull(AliasValidator.validateCharacterName(" Aria "));assertNotNull(AliasValidator.validateLength("a","Name"));assertNull(AliasValidator.validateLength("Aria","Name"));Cache.personaAliasAllowedChars=null;assertNotNull(AliasValidator.validate("Aria"));} @Test void masksResolveHelmetDefinitionsAndConfiguredOrDefaultLabels(){masks.close();masks=mockStatic(MaskService.class,CALLS_REAL_METHODS);try(var loader=mockStatic(net.tfminecraft.rpcharacters.loaders.MaskLoader.class)){assertFalse(MaskService.isMasked(null));assertNull(MaskService.resolveMask(null));assertFalse(MaskService.isMasked(player));var item=new org.bukkit.inventory.ItemStack(Material.CARVED_PUMPKIN);player.getInventory().setHelmet(item);var mask=mock(MaskDefinition.class);loader.when(()->net.tfminecraft.rpcharacters.loaders.MaskLoader.resolveMask(item)).thenReturn(mask);assertTrue(MaskService.isMaskItem(item));assertSame(mask,MaskService.resolveMask(player));assertTrue(MaskService.isMasked(player));Cache.maskedLabel=null;assertEquals("Masked",MaskService.getMaskedLabel());Cache.maskedLabel="Disguised";assertEquals("Disguised",MaskService.getMaskedLabel());}}
 @Test void nameColourModelsRoundTripDefensivelyAndSlugsHaveSafeFallbacks(){assertNull(NameColour.of(null));assertNull(NameColour.of(List.of()));assertNull(NameColour.of(Arrays.asList(null," ")));var colour=NameColour.gradient(" #abcdef ","#123456");assertEquals(List.of("#abcdef","#123456"),colour.getHexCodes());assertThrows(UnsupportedOperationException.class,()->colour.getHexCodes().clear());assertEquals(colour.getHexCodes(),NameColour.fromJson(colour.toJsonObject()).getHexCodes());assertEquals(colour.getHexCodes(),colour.toJsonMap().get("colours"));assertNull(NameColour.fromJson(null));assertNull(NameColour.fromJson(new org.json.simple.JSONObject()));assertNull(NameColour.fromJson(new org.json.simple.JSONObject(Map.of("colours","invalid"))));var arr=new org.json.simple.JSONArray();arr.add(null);arr.add("#112233");assertEquals(List.of("#112233"),NameColour.fromJson(new org.json.simple.JSONObject(Map.of("colours",arr))).getHexCodes());assertEquals("character",CharacterSlug.fromDisplayName(null));assertEquals("character",CharacterSlug.fromDisplayName(" "));assertEquals("character",CharacterSlug.fromDisplayName("!!!"));assertEquals("aria_elf",CharacterSlug.fromDisplayName("§aAria  Elf"));assertNull(IaItemPath.mythicIaTag(null));assertNull(IaItemPath.mythicIaTag("ia. : "));assertNull(IaItemPath.mythicIaTag("ia.ns:a:b"));assertTrue(IaItemPath.tagMatches("ia.ns:item","NS.ITEM"));}
 @Test void descriptionAndColourInputsRejectMissingOrOversizedValues(){assertTrue(net.tfminecraft.rpcharacters.persona.NameColourParser.parse(null).isEmpty());assertTrue(net.tfminecraft.rpcharacters.persona.NameColourParser.parse(" ").isEmpty());Cache.characterDescriptionMinLength=2;Cache.characterDescriptionMaxLength=4;assertNotNull(net.tfminecraft.rpcharacters.persona.DescriptionValidator.validate(null));assertNotNull(net.tfminecraft.rpcharacters.persona.DescriptionValidator.validate(" "));assertNotNull(net.tfminecraft.rpcharacters.persona.DescriptionValidator.validate("a"));assertNotNull(net.tfminecraft.rpcharacters.persona.DescriptionValidator.validate("abcde"));assertNull(net.tfminecraft.rpcharacters.persona.DescriptionValidator.validate("abc"));}

}
