package net.tfminecraft.rpcharacters.utils;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.nio.file.*;
import java.util.*;
import org.bukkit.*;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.*;
import org.mockbukkit.mockbukkit.*;
import org.mockbukkit.mockbukkit.entity.PlayerMock;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.database.Database;
import net.tfminecraft.rpcharacters.enums.Status;
import net.tfminecraft.rpcharacters.loaders.*;
import net.tfminecraft.rpcharacters.managers.PlayerManager;
import net.tfminecraft.rpcharacters.mmocore.AttributePointService;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.objects.attributes.AttributeModifier;
import net.tfminecraft.rpcharacters.objects.races.Race;
import net.tfminecraft.rpcharacters.objects.trait.Trait;

class ProstheticTraitRulesRuntimeTest {
    @TempDir Path folder;ServerMock server;PlayerMock player;RuntimeTestState state;RPCharacters plugin;PlayerManager manager;RPCharacter character;PlayerData data;Trait injury,prosthetic,unrelated;MockedConstruction<Integrator> integrations;MockedStatic<AttributePointService> points;final List<AutoCloseable> mocks=new ArrayList<>();
    @BeforeEach void setup() throws Exception {server=MockBukkit.mock();state=new RuntimeTestState(RPCharacters.class,TraitLoader.class,ProstheticLoader.class);Cache.attributes=new ArrayList<>(List.of("strength"));Cache.professions=new ArrayList<>();Cache.backgroundTraitTypes=new ArrayList<>();TraitLoader.oList=new ArrayList<>();player=server.addPlayer("Owner");plugin=mock(RPCharacters.class);when(plugin.getLogger()).thenReturn(java.util.logging.Logger.getAnonymousLogger());RPCharacters.plugin=plugin;manager=mock(PlayerManager.class);boundary(RPCharacters.class).when(RPCharacters::getPlayerManager).thenReturn(manager);boundary(Database.class);points=boundary(AttributePointService.class);integrations=mockConstruction(Integrator.class);mocks.add(integrations);injury=trait("missing_arm","injury",-5);prosthetic=trait("wooden_arm","prosthetic",2);unrelated=trait("wise","background",1);character=character(true,List.of());data=new PlayerData(player);data.addCharacter(character);mappings("replacements:\n  missing_arm:\n    wooden_arm: minecraft:stick\n");}
    <T> MockedStatic<T> boundary(Class<T> type){var mocked=mockStatic(type);mocks.add(mocked);return mocked;}
    Trait trait(String id,String key,int strength){var yaml=new YamlConfiguration();yaml.set("name",id);yaml.set("key",key);yaml.set("attribute-modifiers",List.of("strength."+strength));return trait(id,yaml);}
    Trait trait(String id,YamlConfiguration yaml){var trait=new Trait(id,yaml);TraitLoader.oList.add(trait);return trait;}
    RPCharacter character(boolean active,List<Trait> traits){var yaml=new YamlConfiguration();yaml.set("name","Human");return new RPCharacter(player,UUID.randomUUID().toString(),"Aria",active,Status.ALIVE,new Race("human",yaml),new ArrayList<>(traits),"HUMAN");}
    void mappings(String yaml) throws Exception {var file=folder.resolve("prosthetics.yml");Files.writeString(file,yaml);new ProstheticLoader().load(file.toFile());}
    int strength(RPCharacter character){return character.getAttributeData().getAmount(new AttributeModifier("strength",0));}
    String messages(){var out=new ArrayList<String>();String message;while((message=player.nextMessage())!=null)out.add(message);return ChatColor.stripColor(String.join("\n",out));}
    @AfterEach void cleanup() throws Exception {try{for(int i=mocks.size()-1;i>=0;i--)mocks.get(i).close();if(state!=null)state.close();}finally{MockBukkit.unmock();}}

    @Test void incompleteDraftsAndMissingPlayerDataNeedNoSanitization(){assertFalse(ProstheticTraitRules.stripReplacedInjuries(null));assertFalse(ProstheticTraitRules.stripReplacedInjuries(new RPCharacter(player)));assertFalse(ProstheticTraitRules.sanitize(null));assertFalse(ProstheticTraitRules.sanitize(new PlayerData(player)));assertFalse(ProstheticTraitRules.stripReplacedInjuries(character));}
    @Test void strippingKeepsProstheticsAndUnrelatedTraitsWhileRemovingTheirMatchingInjuries(){character.setTraits(new ArrayList<>(List.of(injury,prosthetic,unrelated)));assertTrue(ProstheticTraitRules.stripReplacedInjuries(character));assertEquals(List.of(prosthetic,unrelated),character.getTraits());assertFalse(ProstheticTraitRules.stripReplacedInjuries(character));}
    @Test void unmappedOrReloadedAwayProstheticsCannotDeleteInjuries() throws Exception {var unmapped=trait("unmapped_arm","prosthetic",0);character.setTraits(new ArrayList<>(List.of(injury,unmapped)));assertFalse(ProstheticTraitRules.stripReplacedInjuries(character));character.setTraits(new ArrayList<>(List.of(injury,prosthetic)));TraitLoader.oList.remove(prosthetic);assertFalse(ProstheticTraitRules.stripReplacedInjuries(character));TraitLoader.oList.add(prosthetic);mappings("");assertFalse(ProstheticTraitRules.stripReplacedInjuries(character));assertEquals(List.of(injury,prosthetic),character.getTraits());}
    @Test void sanitizationProcessesEveryCharacterAndReportsWhetherAnythingChanged(){var affected=character(false,List.of(injury,prosthetic));var unaffected=character(false,List.of(injury,unrelated));data.addCharacter(affected);data.addCharacter(unaffected);assertTrue(ProstheticTraitRules.sanitize(data));assertEquals(List.of(prosthetic),affected.getTraits());assertEquals(List.of(injury,unrelated),unaffected.getTraits());assertFalse(ProstheticTraitRules.sanitize(data));}
    @Test void sanitizingLoadedCharactersRefreshesTheirCachedAttributes(){var loaded=character(true,List.of(injury,prosthetic));assertEquals(-3,strength(loaded));var account=new PlayerData(player);account.addCharacter(loaded);assertTrue(ProstheticTraitRules.sanitize(account));assertEquals(List.of(prosthetic),loaded.getTraits());assertEquals(2,strength(loaded),"Login must not retain penalties from an injury removed by sanitization");}
    @Test void installResolutionRejectsBlankTargetsAndIgnoresServerLocale(){assertEquals(ProstheticTraitRules.InstallAction.NONE,ProstheticTraitRules.resolveInstall(true,null,null));assertEquals(ProstheticTraitRules.InstallAction.NONE,ProstheticTraitRules.resolveInstall(true,null," "));assertEquals(ProstheticTraitRules.InstallAction.INSTALL,ProstheticTraitRules.resolveInstall(true," ","IRON_ARM"));Locale.setDefault(Locale.forLanguageTag("tr-TR"));assertEquals(ProstheticTraitRules.InstallAction.ALREADY_OWNED,ProstheticTraitRules.resolveInstall(false,"IRON_ARM","iron_arm"));}
    @Test void inactiveCharacterChangesRefreshDataAndPersistWithoutLiveIntegrations(){var inactive=character(false,List.of());TraitChangeService.addTrait(player,inactive,unrelated);assertEquals(List.of(unrelated),inactive.getTraits());assertEquals(1,strength(inactive));TraitChangeService.removeTrait(player,inactive,unrelated);assertTrue(inactive.getTraits().isEmpty());assertEquals(0,strength(inactive));assertTrue(integrations.constructed().isEmpty());points.verifyNoInteractions();verify(manager,times(2)).savePlayer(player);verify(manager,times(2)).reevaluateFreeze(player);}
    @Test void activeCharacterChangesRemoveOldEffectsThenRefreshTheNewCreationLayer(){TraitChangeService.addTrait(player,character,unrelated);assertEquals(1,strength(character));TraitChangeService.removeTrait(player,character,unrelated);assertEquals(0,strength(character));assertEquals(2,integrations.constructed().size());for(var integration:integrations.constructed()){var order=inOrder(integration);order.verify(integration).remove(player,character,false);order.verify(integration).integrate(player,character);}points.verify(()->AttributePointService.refreshAfterCreationLayerChange(player,character),times(2));verify(manager,times(2)).savePlayer(player);}
    @Test void configuredTraitNotificationsOverrideDefaultsAndBlankMessagesFallBack(){var yaml=new YamlConfiguration();yaml.set("name","Named");yaml.set("key","background");yaml.set("gained-message","&aCustom gain");yaml.set("lost-message","&cCustom loss");var custom=trait("custom",yaml);TraitChangeService.sendGainedMessage(player,custom);TraitChangeService.sendLostMessage(player,custom);assertEquals("Custom gain\nCustom loss",messages());yaml.set("gained-message"," ");yaml.set("lost-message","");var blank=trait("blank",yaml);assertTrue(TraitChangeService.resolveGainedMessage(blank).contains("You gained the trait Named"));assertTrue(TraitChangeService.resolveLostMessage(blank).contains("You lost the trait Named"));TraitChangeService.sendGainedMessage(player,unrelated);TraitChangeService.sendLostMessage(player,unrelated);assertTrue(messages().contains("wise"));}
    @Test void replacementRejectsMissingSourcesAndTargetsWithoutChangingTheCharacter(){character.addTrait(injury);for(String missing:Arrays.asList(null," ","absent")){assertFalse(TraitChangeService.replaceInjuryWithProsthetic(player,character,missing,prosthetic.getId()));assertFalse(TraitChangeService.replaceProsthetic(player,character,missing,prosthetic.getId()));}assertFalse(TraitChangeService.replaceInjuryWithProsthetic(player,character,injury.getId(),"unknown"));assertFalse(TraitChangeService.replaceProsthetic(player,character,injury.getId(),"unknown"));assertEquals(List.of(injury),character.getTraits());verifyNoInteractions(manager);assertEquals("",messages());}
    @Test void replacingAnInjuryAndThenUpgradingItsProstheticPersistsAndExplainsEachChange(){var advanced=trait("iron_arm","prosthetic",4);character.addTrait(injury);assertTrue(TraitChangeService.replaceInjuryWithProsthetic(player,character,"MISSING_ARM","wooden_arm"));assertEquals(List.of(prosthetic),character.getTraits());assertEquals(2,strength(character));assertTrue(TraitChangeService.replaceProsthetic(player,character,"WOODEN_ARM","iron_arm"));assertEquals(List.of(advanced),character.getTraits());assertEquals(4,strength(character));String notifications=messages();assertTrue(notifications.contains("lost the trait missing_arm"));assertTrue(notifications.contains("gained the trait wooden_arm"));assertTrue(notifications.contains("lost the trait wooden_arm"));assertTrue(notifications.contains("gained the trait iron_arm"));verify(manager,times(4)).savePlayer(player);}
}
