package net.tfminecraft.rpcharacters.chat.smart;

import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import org.junit.jupiter.api.*;

class MuffleEngineTest {
    final UUID utterance=new UUID(0,1),viewer=new UUID(1,2);
    SmartMessageSettings settings(){var s=new SmartMessageSettings();s.setMinAudible(0);s.setFullClarity(.95);s.setLowIntelligibilityThreshold(.1);return s;}
    MuffleOutcome apply(String text,double clarity,SmartMessageSettings s){return MuffleEngine.applyDetailed(text,clarity,utterance,viewer,s);}
    @Test void audibleThresholdsPreserveClearSpeechAndHideOnlyPlaceholderIdentity(){var s=settings();assertEquals("empty-input",apply(null,.5,s).getStage());assertEquals("empty-input",apply(" ",.5,s).getStage());assertEquals("empty-input",apply("hello",.5,null).getStage());s.setMinAudible(.05);var silent=apply("hello",.01,s);assertFalse(silent.isAudible());assertEquals("inaudible-below-min",silent.getStage());assertFalse(silent.hidesSender());assertEquals("Full Voice",apply("Full Voice",1,s).getText());assertEquals("full-clarity",apply("Full Voice",1,s).getStage());s.setLowIntelligibilityPlaceholder("&7Murmur");var hidden=apply("hello",.06,s);assertEquals("§7Murmur",hidden.getText());assertTrue(hidden.hidesSender());assertTrue(hidden.isAudible());s.setLowIntelligibilityPlaceholder("");assertTrue(apply("hello",.06,s).getText().contains("muffled voices"));s.setLowIntelligibilityPlaceholder(null);assertTrue(apply("hello",.06,s).getText().contains("muffled voices"));var empty=new MuffleOutcome(null,null);assertEquals("unknown",empty.getStage());assertEquals("",empty.getText());}
    @Test void configuredRulesAreCaseInsensitiveOrderedAndDeterministic(){var s=settings();s.setLowIntelligibilityThreshold(0);s.setGenericMuffle(false);s.setMuffleRules(List.of(new MuffleRule("unmatched","x",0,1,100),new MuffleRule("hello","hidden",.5,1,100),new MuffleRule("hello","never",0,1,0),new MuffleRule("HELLO","hmm",0,1,100),new MuffleRule("-end-","",0,1,100)));var result=apply("Hello HELLO",0,s);assertEquals("hmm HELLO...",result.getText());assertEquals("muffle-rules",result.getStage());assertEquals(result.getText(),MuffleEngine.apply("Hello HELLO",0,utterance,viewer,s));s.setMuffleRules(List.of(new MuffleRule("-end-","",0,1,100)));assertEquals("already...",apply("already...",0,s).getText());assertEquals("unchanged",apply("already...",0,s).getStage());}
    @Test void probabilisticRulesCanLeaveSpeechUnchangedAndGenericModeIsOptional(){var s=settings();s.setLowIntelligibilityThreshold(0);s.setGenericMuffle(false);s.setMuffleRules(List.of(new MuffleRule("word","murmur",0,1,1),new MuffleRule("-end-","",0,1,1)));assertEquals("word",apply("word",.5,s).getText());assertEquals("unchanged",apply("word",.5,s).getStage());s.setMuffleRules(List.of());s.setGenericMuffle(true);assertEquals("generic-muffle",apply("st ss",.5,s).getStage());assertEquals("unchanged",apply("I !",.5,s).getStage());}
    @Test void clearNullEmptyAndSingleCharacterTokensArePreserved(){var r=new Random(1);assertNull(PhoneticMuffler.muffle(null,.5,r));assertEquals("",PhoneticMuffler.muffle("",.5,r));assertEquals("Full Clarity",PhoneticMuffler.muffle("Full Clarity",.99,r));assertEquals("I, a! 123 é.",PhoneticMuffler.muffle("I, a! 123 é.",.5,r));}
    @Test void highDistortionUsesRecognisableSoundClustersWithoutChangingSeparators(){var always=new Random(){@Override public double nextDouble(){return 0;}@Override public boolean nextBoolean(){return false;}};assertEquals("sn sm",PhoneticMuffler.muffle("st ss",.5,new Random(0)));assertEquals("n m m m m k n tn n l nt n f",PhoneticMuffler.muffle("th sh ch mp mb ck ng tt dd ll ght tion ff",0,always));}
    @Test void seededDistortionIsReproducibleAcrossVocabularyAndPreservesPunctuation(){String words="coffee stuffing stopped swamping robed settle running singing led incoming completely unforgettable knighthood letter address balloon thought action manner mother zebra quick rhythm scuffle winter";for(double clarity:new double[]{0,.25,.5,.7,.9})for(int seed=0;seed<120;seed++){String text=words+", 123!";String actual=PhoneticMuffler.muffle(text,clarity,new Random(seed));assertEquals(actual,PhoneticMuffler.muffle(text,clarity,new Random(seed)));assertTrue(actual.endsWith(", 123!"));assertEquals(words.split(" ").length,actual.substring(0,actual.length()-6).split(" ").length);assertFalse(actual.contains("...."));}}
}
