package net.tfminecraft.rpcharacters.chat.smart;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.util.*;
import java.util.logging.Logger;
import net.tfminecraft.rpcharacters.*;
import net.tfminecraft.rpcharacters.chat.*;
import net.tfminecraft.rpcharacters.conversation.ConversationManager;
import net.tfminecraft.rpcharacters.identity.*;
import net.tfminecraft.rpcharacters.loaders.*;
import net.tfminecraft.rpcharacters.managers.PlayerManager;
import net.tfminecraft.rpcharacters.objects.*;
import net.tfminecraft.rpcharacters.speechbubble.SpeechBubbleSettings;
import net.tfminecraft.rpcharacters.speechbubble.fake.*;
import org.bukkit.entity.Player;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.mockito.MockedStatic;
import org.mockbukkit.mockbukkit.MockBukkit;

class SmartMessageServiceTest {
    RuntimeTestState state; RPCharacters plugin;Logger logger;Player speaker,listener,other;SmartMessageSettings settings;SpeechBubbleSettings bubbleSettings;
    final List<AutoCloseable> boundaries=new ArrayList<>();final Map<Player,List<String>> messages=new HashMap<>();
    final Map<Player,Double> powers=new HashMap<>();final Map<Player,PlayerData> accounts=new HashMap<>();
    final Map<UUID,net.Indyuce.mmocore.api.player.PlayerData> mmoAccounts=new HashMap<>();
    final Map<UUID,MuffleOutcome> outcomes=new HashMap<>();final List<Heard> heard=new ArrayList<>();
    record Heard(String message,double power,UUID utterance,UUID listener){}
    MockedStatic<SpeechPowerCalculator> power;MockedStatic<ProtocolLibBridge> protocol;FakeBubbleManager fake;
    MockedStatic<net.Indyuce.mmocore.api.player.PlayerData> mmo;
    @BeforeEach void setup(){
        MockBukkit.mock();state=new RuntimeTestState(RPCharacters.class,ConversationManager.class);Cache.attributes=new ArrayList<>();Cache.professions=new ArrayList<>();Cache.conversationReplyTimeoutSeconds=60;
        plugin=mock(RPCharacters.class);logger=mock(Logger.class);when(plugin.getLogger()).thenReturn(logger);RPCharacters.plugin=plugin;
        speaker=player("Speaker");listener=player("Listener");other=player("Other");settings=new SmartMessageSettings();settings.setDebugMessages(true);settings.setCharismaHearingEnabled(false);
        boundary(SmartMessageLoader.class).when(SmartMessageLoader::getSettings).thenReturn(settings);bubbleSettings=new SpeechBubbleSettings();bubbleSettings.setUtteranceTimeoutSeconds(5);boundary(SpeechBubbleLoader.class).when(SpeechBubbleLoader::getSettings).thenReturn(bubbleSettings);
        power=boundary(SpeechPowerCalculator.class);power.when(()->SpeechPowerCalculator.evaluate(any(),any(),any(),eq(settings))).thenAnswer(c->snapshot(powers.getOrDefault(c.<Player>getArgument(1),1.0)));
        boundary(MuffleEngine.class).when(()->MuffleEngine.applyDetailed(any(),anyDouble(),any(),any(),eq(settings))).thenAnswer(c->{heard.add(new Heard(c.getArgument(0),c.getArgument(1),c.getArgument(2),c.getArgument(3)));return outcomes.getOrDefault(c.getArgument(3),new MuffleOutcome(c.getArgument(0),"clear"));});
        boundary(PlayerManager.class).when(()->PlayerManager.get(any(Player.class))).thenAnswer(c->accounts.get(c.getArgument(0)));
        mmo=boundary(net.Indyuce.mmocore.api.player.PlayerData.class);mmo.when(()->net.Indyuce.mmocore.api.player.PlayerData.get(any(UUID.class))).thenAnswer(c->mmoAccounts.get(c.getArgument(0)));
        var identity=boundary(DisplayIdentityService.class);identity.when(()->DisplayIdentityService.resolveDisplayUnmasked(any(Player.class))).thenReturn("Aria");identity.when(()->DisplayIdentityService.resolveDisplayTab(any(Player.class))).thenReturn("AriaTab");boundary(MaskService.class);
        protocol=boundary(ProtocolLibBridge.class);fake=mock(FakeBubbleManager.class);boundary(FakeBubbleManager.class).when(FakeBubbleManager::get).thenReturn(fake);
    }
    @AfterEach void cleanup() throws Exception {for(Player p:messages.keySet())ChatChannelPreferenceManager.get().clear(p);for(int i=boundaries.size()-1;i>=0;i--)boundaries.get(i).close();MockBukkit.unmock();state.close();}
    <T> MockedStatic<T> boundary(Class<T> type){var m=mockStatic(type);boundaries.add(m);return m;}
    Player player(String name){var p=mock(Player.class);when(p.getName()).thenReturn(name);when(p.getUniqueId()).thenReturn(UUID.randomUUID());when(p.isOnline()).thenReturn(true);when(p.hasLineOfSight(any(org.bukkit.entity.Entity.class))).thenReturn(true);messages.put(p,new ArrayList<>());doAnswer(c->{messages.get(p).add(c.getArgument(0));return null;}).when(p).sendMessage(anyString());return p;}
    ChatChannel channel(Object... pairs){var c=new YamlConfiguration();c.set("range",20);c.set("format","{display}: {message}");for(int i=0;i<pairs.length;i+=2)c.set((String)pairs[i],pairs[i+1]);return new ChatChannel("rp",c);}
    CharacterChatEvent event(String message,Player... recipients){return new CharacterChatEvent(speaker,null,"rp",message,"Aria",new HashSet<>(Arrays.asList(recipients)),false,false);}
    void deliver(ChatChannel c,String text,Player... recipients){SmartMessageService.deliver(event(text,recipients),c,speaker);}
    String text(Player p){return String.join("\n",messages.get(p));}
    SpeechPowerSnapshot snapshot(double amount){return SpeechPowerSnapshot.resolved(amount,"",8,20,1,amount,0,0,1,"0,0");}
    void charisma(Player p,int amount){var data=mock(net.Indyuce.mmocore.api.player.PlayerData.class,RETURNS_DEEP_STUBS);when(data.getAttributes().getInstance("charisma").getTotal()).thenReturn(amount);mmoAccounts.put(p.getUniqueId(),data);}
    RPCharacter account(Player p){var c=spy(new RPCharacter(p));var d=new PlayerData(p);doReturn(true).when(c).isActive();d.addCharacter(c);accounts.put(p,d);return c;}

    @Test void clearDeliveryKeepsOneUtteranceAcrossChatAndBubbles(){protocol.when(ProtocolLibBridge::isReady).thenReturn(true);long before=System.currentTimeMillis();var c=channel("bubble",true);deliver(c,"Hello",listener,other);long after=System.currentTimeMillis();assertEquals("Aria: Hello",text(listener));assertEquals("Aria: Hello",text(other));assertEquals(2,heard.size());assertEquals(heard.getFirst().utterance(),heard.getLast().utterance());for(Player p:List.of(listener,other))verify(fake).show(eq(p),eq(speaker),eq(heard.getFirst().utterance()),eq("Hello"),eq(c),longThat(t->t>=before+5000&&t<=after+5000));verify(logger).info(contains("heardCount=2"));}
    @Test void offlineHiddenNullAndBelowAudibilityRecipientsNeverReachMuffling(){when(other.isOnline()).thenReturn(false);ChatChannelPreferenceManager.get().toggleChannelVisibility(listener,"rp");powers.put(speaker,.01);deliver(channel(),"Secret",null,listener,other,speaker);assertTrue(heard.isEmpty());assertTrue(text(listener).isEmpty());assertTrue(text(other).isEmpty());assertTrue(text(speaker).contains("No one can hear"));verify(logger,times(2)).info(contains("offline/null"));verify(logger).info(contains("channel toggled off"));verify(logger).info(contains("below min-audible"));verify(logger).info(contains("heardCount=0"));}
    @Test void emptyMuffleOutcomeAndEmptyChannelFormatAreNotDelivered(){outcomes.put(listener.getUniqueId(),new MuffleOutcome("","inaudible"));deliver(channel(),"No sound",listener);assertTrue(text(listener).isEmpty());assertTrue(text(speaker).contains("No one can hear"));verify(logger).info(contains("muffle stage=inaudible"));outcomes.clear();deliver(channel("format",""),"No format",listener);assertTrue(text(listener).isEmpty());verify(logger).info(contains("empty formatted message"));}
    @Test void anonymousMuffledMessagesHideTheSpeakerOnlyWithoutLineOfSight(){settings.setAnonymousMuffledVoiceEnabled(true);powers.put(listener,.4);when(listener.hasLineOfSight(speaker)).thenReturn(false);deliver(channel(),"Half heard",listener);assertEquals("???: Half heard",text(listener));verify(logger).info(contains("chat=anonymous-muffled"));messages.get(listener).clear();when(listener.hasLineOfSight(speaker)).thenReturn(true);deliver(channel(),"Visible",listener);assertEquals("Aria: Visible",text(listener));verifyNoInteractions(fake);}
    @Test void placeholderMessagesBypassSpeakerFormattingAndRemainAnonymous(){outcomes.put(listener.getUniqueId(),new MuffleOutcome("§7*muffled voices*","placeholder"));deliver(channel(),"Secret",listener);assertEquals("§7*muffled voices*",text(listener));assertFalse(text(listener).contains("Aria"));verify(logger).info(contains("chat=anonymous"));}
    @Test void activeConversationSuppressesOnlyPlaceholderOutcomes(){var c=account(listener);var partner=account(other);ConversationManager.refreshActiveSession(c,partner,System.currentTimeMillis());outcomes.put(listener.getUniqueId(),new MuffleOutcome("muffled","placeholder"));deliver(channel(),"Secret",listener);assertTrue(text(listener).isEmpty());assertTrue(text(speaker).contains("No one can hear"));verify(logger).info(contains("sessions=1"));outcomes.put(listener.getUniqueId(),new MuffleOutcome("Words","partial"));deliver(channel(),"Secret",listener);assertEquals("Aria: Words",text(listener));settings.setPlaceholderSuppressionEnabled(false);outcomes.put(listener.getUniqueId(),new MuffleOutcome("muffled","placeholder"));deliver(channel(),"Secret",listener);assertTrue(text(listener).contains("muffled"));}
    @Test void charismaBoostIsAppliedBeforeMufflingAndIncludedInDiagnostics(){settings.setCharismaHearingEnabled(true);charisma(listener,40);powers.put(listener,.4);deliver(channel(),"Quiet",listener);assertEquals(.49,heard.getFirst().power(),.000001);assertEquals("Aria: Quiet",text(listener));verify(logger).info(contains("chaBoost=0.090"));heard.clear();deliver(channel("range",0),"Global",listener);assertEquals(.4,heard.getFirst().power());}
    @Test void absentCharismaDataRetainsOriginalPowerAndDebugCanBeDisabled(){settings.setCharismaHearingEnabled(true);settings.setDebugMessages(false);powers.put(listener,.4);deliver(channel("bubble",true),"Words",listener);assertEquals(.4,heard.getFirst().power());assertEquals("Aria: Words",text(listener));verifyNoInteractions(logger,fake);}
    @Test void debugPreviewTruncatesLongMessagesAndAcceptsPluginModifiedNullText(){String longText="§a"+"x".repeat(80);deliver(channel(),longText,listener);verify(logger).info(contains("message=\"&a"+"x".repeat(43)+"...\""));deliver(channel(),null,listener);assertTrue(text(speaker).contains("No one can hear"));verify(logger).info(contains("message=null"));}
    @Test void debugLoggingIsSafeDuringPluginShutdown(){settings.setDebugMessages(false);SmartMessageDebug.log("test","hidden");verifyNoInteractions(logger);settings.setDebugMessages(true);SmartMessageDebug.logSkip("test","reason");verify(logger).info("[SmartMessages] test: SKIP — reason");RPCharacters.plugin=null;assertDoesNotThrow(()->SmartMessageDebug.log("test","shutdown"));}
    @Test void charismaLookupHandlesMissingInputsAttributesAndSdkFailures(){assertEquals(0,CharismaHearingCalculator.getCharisma(null,settings));assertEquals(0,CharismaHearingCalculator.getCharisma(listener,null));settings.setCharismaAttribute(" ");assertEquals(0,CharismaHearingCalculator.getCharisma(listener,settings));settings.setCharismaAttribute("charisma");assertEquals(0,CharismaHearingCalculator.getCharisma(listener,settings));charisma(listener,24);assertEquals(24,CharismaHearingCalculator.getCharisma(listener,settings));mmo.when(()->net.Indyuce.mmocore.api.player.PlayerData.get(listener.getUniqueId())).thenThrow(new IllegalStateException("unloaded"));assertEquals(0,CharismaHearingCalculator.getCharisma(listener,settings));}
    @Test void charismaBoostHonoursAudibilityClarityAndConfiguredCaps(){settings.setCharismaHearingEnabled(true);charisma(listener,40);assertEquals(.4,CharismaHearingCalculator.applyBoost(null,.4,settings));assertEquals(.4,CharismaHearingCalculator.applyBoost(listener,.4,null));settings.setCharismaHearingEnabled(false);assertEquals(.4,CharismaHearingCalculator.applyBoost(listener,.4,settings));settings.setCharismaHearingEnabled(true);assertEquals(.01,CharismaHearingCalculator.applyBoost(listener,.01,settings));assertEquals(.9,CharismaHearingCalculator.applyBoost(listener,.9,settings));assertEquals(.49,CharismaHearingCalculator.applyBoost(listener,.4,settings),.000001);assertEquals(.175,CharismaHearingCalculator.applyBoost(listener,.1,settings),.000001);charisma(listener,0);assertEquals(.4,CharismaHearingCalculator.applyBoost(listener,.4,settings));charisma(listener,400);settings.setCharismaMaxBoost(10);assertEquals(.85,CharismaHearingCalculator.applyBoost(listener,.4,settings));assertEquals(0,CharismaHearingCalculator.computeBoostFactor(10,.4,null));assertEquals(0,CharismaHearingCalculator.computeBoostFactor(0,.4,settings));settings.setCharismaScale(0);assertEquals(0,CharismaHearingCalculator.computeBoostFactor(10,.4,settings));}
    @Test void anonymousResolverGuardsAndThresholdsKeepIdentityWhenAppropriate(){var c=channel();settings.setAnonymousMuffledVoiceEnabled(false);assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(speaker,listener,c,.4,settings));settings.setAnonymousMuffledVoiceEnabled(true);assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(null,listener,c,.4,settings));assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(speaker,null,c,.4,settings));assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(speaker,listener,null,.4,settings));assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(speaker,speaker,c,.4,settings));assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(speaker,listener,channel("range",0),.4,settings));assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(speaker,listener,c,.65,settings));assertEquals("Aria",AnonymousMuffledVoiceResolver.resolveDisplayName("Aria",false,settings));settings.setAnonymousMuffledDisplay(" ");assertEquals("???",AnonymousMuffledVoiceResolver.resolveDisplayName("Aria",true,settings));settings.setAnonymousMuffledDisplay("Voice");assertEquals("Voice",AnonymousMuffledVoiceResolver.resolveDisplayName("Aria",true,settings));}
    @Test void anonymousResolverNullSettingsFollowItsPublicInputGuard(){assertFalse(AnonymousMuffledVoiceResolver.shouldAnonymize(speaker,listener,channel(),.4,null));}
    @Test void placeholderSuppressionRequiresAnActualActiveCharacterAndSession(){assertFalse(PlaceholderSuppressionResolver.shouldSuppress(null,settings));assertEquals(0,PlaceholderSuppressionResolver.activeSessionCount(null));assertFalse(PlaceholderSuppressionResolver.shouldSuppress(listener,settings));assertEquals(0,PlaceholderSuppressionResolver.activeSessionCount(listener));accounts.put(listener,new PlayerData(listener));assertFalse(PlaceholderSuppressionResolver.shouldSuppress(listener,settings));assertEquals(0,PlaceholderSuppressionResolver.activeSessionCount(listener));var c=account(listener);assertFalse(PlaceholderSuppressionResolver.shouldSuppress(listener,settings));assertEquals(0,PlaceholderSuppressionResolver.activeSessionCount(listener));var partner=account(other);ConversationManager.refreshActiveSession(c,partner,System.currentTimeMillis());assertTrue(PlaceholderSuppressionResolver.shouldSuppress(listener,settings));assertEquals(1,PlaceholderSuppressionResolver.activeSessionCount(listener));settings.setPlaceholderSuppressionEnabled(false);assertFalse(PlaceholderSuppressionResolver.shouldSuppress(listener,settings));}
    @Test void publicDeliveryWithNoSenderCannotThrowOrBroadcast() {
        power.when(()->SpeechPowerCalculator.evaluate(isNull(),any(),any(),eq(settings))).thenCallRealMethod();
        assertDoesNotThrow(()->SmartMessageService.deliver(event("orphan",listener),channel(),null));assertTrue(text(listener).isEmpty());
    }

}
