package net.tfminecraft.rpcharacters.chat.smart;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.*;
import net.tfminecraft.rpcharacters.chat.ChatChannel;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.block.data.*;
import org.bukkit.entity.Player;
import org.bukkit.util.*;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import org.mockbukkit.mockbukkit.MockBukkit;

class SpeechPowerCalculatorTest {
    World world;Player speaker,listener;SmartMessageSettings settings;Map<String,Block> blocks;Block air;
    @BeforeEach void setup(){MockBukkit.mock();world=mock(World.class);when(world.getName()).thenReturn("speech");blocks=new HashMap<>();air=mock(Block.class);when(air.isEmpty()).thenReturn(true);when(world.getBlockAt(anyInt(),anyInt(),anyInt())).thenAnswer(c->blocks.getOrDefault(c.getArgument(0)+","+c.getArgument(1)+","+c.getArgument(2),air));speaker=player(.5,.5);listener=player(4.5,.5);settings=new SmartMessageSettings();settings.setListenerAnchorSearch(false);settings.setFadeStartPercent(.5);settings.setBlockAttenuation(Map.of(Material.STONE,.5));}
    @AfterEach void cleanup(){MockBukkit.unmock();}
    Player player(double x,double z){var p=mock(Player.class);when(p.getWorld()).thenReturn(world);when(p.getLocation()).thenAnswer(c->new Location(world,x,64,z));when(p.getEyeHeight()).thenReturn(1.6);return p;}
    ChatChannel channel(int range){var c=new YamlConfiguration();c.set("range",range);return new ChatChannel("rp",c);}
    Block block(Material material,double volume){var b=mock(Block.class);when(b.getType()).thenReturn(material);when(b.getBlockData()).thenReturn(mock(BlockData.class));var shape=mock(VoxelShape.class);when(shape.getBoundingBoxes()).thenReturn(List.of(new BoundingBox(0,0,0,1,volume,1)));when(b.getCollisionShape()).thenReturn(shape);return b;}
    @Test void invalidDifferentWorldGlobalAndSelfHaveExplicitOutcomes(){assertEquals("invalid-input",SpeechPowerCalculator.evaluate(null,listener,channel(10),settings).getReason());assertEquals("invalid-input",SpeechPowerCalculator.evaluate(speaker,null,channel(10),settings).getReason());assertEquals("invalid-input",SpeechPowerCalculator.evaluate(speaker,listener,null,settings).getReason());assertEquals("invalid-input",SpeechPowerCalculator.evaluate(speaker,listener,channel(10),null).getReason());when(listener.getWorld()).thenReturn(mock(World.class));assertEquals("different-world",SpeechPowerCalculator.evaluate(speaker,listener,channel(10),settings).getReason());when(listener.getWorld()).thenReturn(world);settings.setSenderHearsSelf(true);assertEquals("sender-hears-self",SpeechPowerCalculator.evaluate(speaker,speaker,channel(10),settings).getReason());assertEquals("global-channel",SpeechPowerCalculator.evaluate(speaker,listener,channel(0),settings).getReason());settings.setSenderHearsSelf(false);assertEquals(1,SpeechPowerCalculator.compute(speaker,speaker,channel(10),settings));assertEquals("out-of-range",SpeechPowerCalculator.evaluate(speaker,listener,channel(2),settings).getReason());}
    @Test void distanceFadesSmoothlyAndEachSolidBlockIsCountedOnlyOnce(){assertEquals(1,SpeechPowerCalculator.compute(speaker,listener,channel(10),settings));listener=player(8,.5);var faded=SpeechPowerCalculator.evaluate(speaker,listener,channel(10),settings);assertEquals(.5,faded.getDistanceFactor(),.0001);blocks.put("2,65,0",block(Material.STONE,1));blocks.put("3,65,0",block(Material.STONE,1));settings.setOcclusionCurve(1);settings.setOcclusionMaxWeight(.75);var muffled=SpeechPowerCalculator.evaluate(speaker,listener,channel(10),settings);assertEquals(2,muffled.getBlockingBlocks());assertEquals(.75,muffled.getOcclusionWeight());assertEquals(Math.exp(-.75),muffled.getOcclusionFactor(),.0001);assertEquals(.5*Math.exp(-.75),muffled.getIntelligibility(),.0001);assertEquals(1,muffled.getAnchorRays());assertEquals("0,0",muffled.getAnchorOffset());}
    @Test void listenerAnchorSearchCanFindAnOpeningBesideABlockedRay(){settings.setListenerAnchorSearch(true);settings.setListenerAnchorEarlyExitClearLos(true);assertEquals(1,SpeechPowerCalculator.evaluate(speaker,listener,channel(10),settings).getAnchorRays());blocks.put("3,65,0",block(Material.STONE,1));settings.setListenerAnchorEarlyExitClearLos(false);settings.setListenerAnchorDiagonals(true);var result=SpeechPowerCalculator.evaluate(speaker,listener,channel(10),settings);assertTrue(result.getAnchorRays()>1);assertTrue(result.getOcclusionFactor()>.1);settings.setListenerAnchorDiagonals(false);assertTrue(SpeechPowerCalculator.evaluate(speaker,listener,channel(10),settings).getAnchorRays()<=5);blocks.put("4,65,1",block(Material.STONE,1));assertTrue(SpeechPowerCalculator.evaluate(speaker,listener,channel(10),settings).getAnchorRays()<5);}
    @Test void soundRulesDistinguishPassableOpenPermeableAndSolidBlocks(){assertFalse(SoundOcclusionRules.blocksSound(null,settings));assertTrue(SoundOcclusionRules.isOpenAnchor(null,settings));assertTrue(SoundOcclusionRules.isOpenAnchor(air,settings));var stone=block(Material.STONE,1);assertTrue(SoundOcclusionRules.blocksSound(stone,settings));assertFalse(SoundOcclusionRules.isOpenAnchor(stone,settings));when(stone.isPassable()).thenReturn(true);assertFalse(SoundOcclusionRules.blocksSound(stone,settings));assertFalse(SoundOcclusionRules.blocksSound(block(Material.STONE,.1),settings));assertTrue(SoundOcclusionRules.blocksSound(block(Material.OAK_STAIRS,.2),settings));var door=block(Material.OAK_DOOR,.1);var open=mock(Openable.class);when(door.getBlockData()).thenReturn(open);assertTrue(SoundOcclusionRules.blocksSound(door,settings));when(open.isOpen()).thenReturn(true);assertFalse(SoundOcclusionRules.blocksSound(door,settings));var trap=block(Material.OAK_TRAPDOOR,.1);when(trap.getBlockData()).thenReturn(open);when(open.isOpen()).thenReturn(false);assertTrue(SoundOcclusionRules.blocksSound(trap,settings));var fence=block(Material.OAK_FENCE,1);when(fence.getBlockData()).thenReturn(mock(org.bukkit.block.data.type.Fence.class));assertFalse(SoundOcclusionRules.blocksSound(fence,settings));var wall=block(Material.COBBLESTONE_WALL,1);when(wall.getBlockData()).thenReturn(mock(org.bukkit.block.data.type.Wall.class));assertFalse(SoundOcclusionRules.blocksSound(wall,settings));assertFalse(SoundOcclusionRules.blocksSound(block(Material.OAK_LEAVES,1),settings));assertFalse(SoundOcclusionRules.blocksSound(block(Material.IRON_BARS,1),settings));}
    @Test void materialAttenuationHonoursExplicitOverridesAndBlastResistanceBands(){assertEquals(settings.getDefaultBlockAttenuation(),SoundOcclusionRules.attenuation(null,settings));assertEquals(.5,SoundOcclusionRules.attenuation(block(Material.STONE,1),settings));assertEquals(0,SoundOcclusionRules.attenuationFromBlastResistance(null));assertEquals(0,SoundOcclusionRules.attenuationFromBlastResistance(Material.AIR));for(Material m:List.of(Material.GLASS,Material.DIRT,Material.WHITE_WOOL,Material.COAL_ORE,Material.ACACIA_LOG,Material.ANDESITE,Material.WHITE_CARPET,Material.OAK_PLANKS,Material.STONE,Material.OBSIDIAN)){double value=SoundOcclusionRules.attenuation(block(m,1),settings);assertTrue(value>=0&&value<=1);}}
    @Test void snapshotsRetainRawPowerAndProduceUsefulDiagnostics(){var s=SpeechPowerSnapshot.resolved(.4,null,4,10,.8,.5,.5,1,4,"1,0");assertEquals(4,s.getDistance());assertEquals(10,s.getRange());assertEquals(.4,s.getRawIntelligibility());assertTrue(s.formatBreakdown().contains("anchorRays=4"));var boost=s.withCharismaBoost(.6,3,.2);assertEquals(.4,boost.getRawIntelligibility());assertEquals(3,boost.getListenerCharisma());assertEquals(.2,boost.getCharismaBoost());assertTrue(boost.formatBreakdown().contains("chaBoost=0.200"));assertTrue(SpeechPowerSnapshot.skipped("invalid").formatBreakdown().contains("reason=invalid"));assertTrue(SpeechPowerSnapshot.resolved(1," ",0,0,1,1,0,0,0," ").formatBreakdown().contains("intelligibility=1.000"));}
    @Test void roundedRayEndpointIsNotSampledBeyondTheListener(){listener=player(.8,.5);settings.setRayStep(.1);assertEquals(1,SpeechPowerCalculator.compute(speaker,listener,channel(10),settings));}

}
